<h2>Equipe Coordenadora</h2>
<ul>
    <li><b>Coordenadora:</b></li>
    <li>Fernanda Jordão Guimarães</li><br/>

    <li><b>Pesquisadores:</b></li>
    <li>Alexandre Malta</li>
    <li>Camilo Moutinho Ferreira</li>
    <li>Carla Burda</li>
    <li>Daniela Trigueirinho</li>
    <li>Debora Portiz Bluhu</li>
    <li>Gustavo da Cruz</li>
    <li>Marcelo Ossamu Honda</li>
    <li>Marco Aurelio Avila</li>    
</ul>
