<h2>Desembarque->Porto</h2>
<h3>Editar</h3>

<a href="<?=$this->url(array("controller"=>"porto","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>

<form action="<?=$this->url(array("controller"=>"porto","action"=>"atualizar"),null,true)?>" method="post">
   <input type="hidden" name="idPorto" value="<?= $this->porto['PTO_ID'] ?>" />
   <fieldset id="Desembarque">
     <div id="esquerda">   
       <div id="form-esq"> 
            <label>Nome: </label>
            <input type="text" name="nome" value="<?= $this->porto['PTO_Nome'] ?>"/> <br />
        </div>

        <div id="form-esq">
            <label>Municipio: </label>
                <select name="municipio">
                    <?php foreach ($this->municipios as $key => $municipio): ?>
                    <option name="municipio" value="<?= $municipio['TMun_ID']; ?>"><?= $municipio['TMun_Municipio']; ?></option>
                    <?php endforeach; ?>
                </select>
            <br />
        </div>
           <div id="Submit">
            <input type="submit" value="Cadastrar" />
        </div>
      </div> 
    </fieldset>
</form>