
<div id="titulos">
    <h2>Desembarque->Porto</h2>
    <h3>Novo</h3>
</div>

<form action="<?=$this->url(array("controller"=>"porto","action"=>"criar"),null,true)?>" method="post">
   <input type="hidden" name="idPorto" placeholder="ID" />
   <fieldset id="Desembarque">
      <div id="esquerda">
      
        <div id="form-esq"> 
            <label>Nome: </label>
            <input type="text" name="nome" placeholder="Nome"/> <br />
        </div>

        <div id="form-esq"> 
            <label>Local: </label>
            <input type="text" name="local" placeholder="Local"/> <br />
        </div>

        <div id="form-dir">
            <label for="municipio">Município</label>
            <select name="municipio" id="municipio">
                <?php foreach ($this->municipios as $key => $municipio): ?>
                <option value="<?= $municipio['tmun_id']; ?>"><?= $municipio['tuf_sigla'], ' ',$municipio['tmun_municipio']; ?></option>
                <?php endforeach; ?>
            </select>            
        </div>
        
          <div id="Submit">
            <a href="<?=$this->url(array("controller"=>"porto","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>
            <input type="submit" value="Cadastrar" />
        </div>
      </div>   
    </fieldset>
</form>