<h2>Desembarque--Porto</h2>

<form>
    <fieldset id="Desembarque">
              <legend ><h3>Porto:</h3></legend>
              <label for="id">ID:</label>
              <input type="text" name="id_porto" id="id_porto"/><br />
              <label for="tipo">Nome do Porto:</label>
              <input type="text" id="nome_porto" name="nome_porto"/><br />
              <label for="tipo">Cidade:</label>
              <input type="text" id="cidade_porto" name="cidade_porto"/><br />
              <input type="submit" value="Enviar"/>
    </fieldset>
</form>