<div id="titulos">
    <h2>Desembarque->Pesca de Manzuá</h2>
    <h3>Entrevista</h3>
</div>

<div id="esquerda-entrevista">
    <form action="<?= $this->url(array("controller" => "manzua", "action" => "criar"), null, true) ?>">
        <fieldset id="Desembarque">
            <div id="esquerda">
                <div id="form-esq">
                    <label>ID da ficha diária:</label>
                    <input type="text" name="id_fichaDiaria" placeholder="ID" disabled="true" value="<?= $this->fichaDiaria['fd_id'] ?>" /><br />
                </div>
                <div id="form-esq">
                    <label>ID monitoramento:</label>
                    <input type="text" name="id_monitoramento" placeholder="ID"  value="<?= $this->monitoramento['mnt_id'] ?>" /><br />
                </div>
                <div id="form-esq">
                    <label for="tipo">ID Entrevista:</label>
                    <input type="text" placeholder = "ID" name="id_entrevista" disabled="true"/><br />
                </div>
            </div>
            <br/>
            <div id="esquerda">
                <legend><h4>Embarcação:</h4></legend>
                <div id="form-esq">
                    <label>Utilizou Barco?</label>
                    <input type="checkbox"  name="embarcada" checked="true"/><br />
                </div>
                <div id="form-esq">
                    <label>Motor?</label>
                    <input type="checkbox"  name="motor"/><br />
                </div>
                <div id="form-esq">
                    <label>Barco:</label>
                    <select name="nomeBarco" placeholder="Nome do Barco" />
                    <?php
                    foreach ($this->barcos as $key => $barco):
                        ?>
                        <option value="<?= $barco['bar_id'] ?>"><?= $barco['bar_nome'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                    <br />
                </div>
                <div id="form-esq">
                    <label>Tipo de Barco:</label>
                    <select name="tipoBarco" />
                    <?php
                    foreach ($this->tipoEmbarcacoes as $key => $tipoEmbarcacao):
                        ?>
                        <option value="<?= $tipoEmbarcacao['tte_id'] ?>"><?= $tipoEmbarcacao['tte_tipoembarcacao'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                    <br />
                </div>

            </div>
            <div id="direita-entrevista">
                <div id="form-esq">    
                    <label>Pescador Entrevistado:</label>
                    <select name="pescadorEntrevistado" />
                    <?php
                    foreach ($this->pescadores as $key => $pescador):
                        ?>
                        <option value="<?= $pescador['tp_id'] ?>"><?= $pescador['tp_nome'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                    <br />
                </div>
                <div id="form-esq">
                    <label>Qtd de Pescadores:</label>
                    <input type="number" name="numPescadores" placeholder="Quantidade Pescadores"/><br />
                </div>
            </div>
            <div id="esquerda">
                <legend><h4>Saída e Volta:</h4></legend>
                <div id="form-esq">

                    <label>Data:</label>
                    <input type="date" name="dataSaida" placeholder="Data da Saída"/>
                </div>
                <div id="form-esq">
                    <label>Horas:</label>
                    <input type="time" name="horaSaida" placeholder="Hora da Saída"/>
                </div>
            </div>
            <div id="direita-entrevista">
                <div id="form-esq">
                    <label>Data:</label>
                    <input type="date" name="dataVolta" placeholder="Data da Volta"/>
                </div>
                <div id="form-esq">
                    <label>Horas:</label>
                    <input type="time" name="horaVolta" placeholder="Hora da Volta"/>
                </div>
            </div>
            <div id="esquerda">
                <div id="form-esq">
                    <label>Tempo Gasto:</label>
                    <input type="time" name="tempoGasto" placeholder="Data da Saída"/>
                </div>
            </div>
            <div id="esquerda">
                <div id="form-esq">
                    <legend><h4>Maré:</h4></legend>
                    <label>Tipo:</label>
                    <select name="mare" >
                        <?php
                        foreach ($this->mare as $key => $mare):
                            ?>
                            <option value="<?= $mare['mre_id'] ?>"><?= $mare['mre_tipo'] ?></option>
                            <?php
                        endforeach;
                        ?>
                    </select>
                </div>
                <div id="form-dir">    
                    <label>Maré Viva?</label>
                    <input type="checkbox" name="mareviva"> 
                </div>
            </div><br/>
            <div id="esquerda">
                <div id="form-esq">
                    <legend><h4>Esforço:</h4></legend>
                    <label>Número de Armadilhas:</label>
                    <input type="text" name="numArmadilhas" placeholder="Armadilhas"/>
                </div>
            </div>
            <div id="esquerda">
                <legend><h4>Outros dados:</h4></legend>
                <div id="form-esq">    
                    <label>Avistou:</label>
                    <input type="text" name="avistamento" placeholder="Avistamento"/><br />
                </div>
                <div id="form-esq">
                    <label for="tipo">Subamostra?:</label>
                    <input type="checkbox" name="subamostra" /><br />
                </div>
                <div id="form-esq">
                    <label for="tipo">Observacao:</label>
                    <input type="text" name="observacao" placeholder="Observacao" /><br />
                </div>
                <div id="Submit">
                    <input type="submit" value="Salvar Entrevista"/>
                </div>
            </div>

        </fieldset>
        <fieldset class="noEditable"><legend>Pesqueiro:</legend>
            <fieldset class="noEditable"><legend>Pesqueiro e tempo até o pesqueiro:</legend>
                <div id="base">
                    <input onclick="jsInsertPesqueiroWithTimeAndRange(this.form, '<?= $this->url(array("controller" => "manzua", "action" => "insertpesqueiro"), null, true) ?>', '<?= $this->entrevista['man_id'] ?>')" type="button" value="Add row" />
                    <select style="float:left;" name="nomePesqueiro">
                        <?php foreach ($this->pesqueiros as $key => $pesqueiro): ?>
                            <option value="<?= $pesqueiro['paf_id']; ?>"><?= $pesqueiro['paf_pesqueiro']; ?></option>
                        <?php endforeach; ?>
                    </select>
                    <input style="float:left;" type="time" name="tempoAPesqueiro" placeholder="Tempo Até pesqueiro" size="10px"/>
                    <input style="float:left;" type="number" name="distAPesqueiro" placeholder="Distância Até pesqueiro (km)" size="23px"/>

                </div>

            </fieldset>
            <br>
            <fieldset class="noEditable" id="itemArteTipoRows"><legend>Pesqueiros:</legend>
                <table id="pesqueiros">
                    <tr>
                        <th width="5%">Id Entrevista</th>
                        <th width="50%">Pesqueiro</th>
                        <th width="30%">Tempo até o Pesqueiro</th>
                        <th width="30%">Distância até o Pesqueiro</th>
                    </tr>
                    <?php
                    foreach ($this->vManzua as $key => $vManzua):
                        ?>
                        <tr id="itemArrastoRows">
                            <td name="inputIdEntrevista"> <?= $vManzua['man_id'] ?> </td>
                            <td name="inputPesqueiro" > <?= $vManzua['paf_pesqueiro'] ?> </td>
                            <td name="inputTempoaPesqueiro"> <?= $vManzua['t_tempoapesqueiro'] ?> </td>
                            <td name="inputTempoaPesqueiro"> <?= $vManzua['t_distapesqueiro'] ?> </td>
                            <td><input type="button" class="button-del" width="5%" onclick="jsDeletePesqueiro(<?= $this->entrevista['man_id'] ?>, '<?= $this->url(array("controller" => "manzua", "action" => "deletepesqueiro"), null, true) ?>', <?= $vManzua['man_paf_id'] ?>)"></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </fieldset>
        </fieldset>
        <fieldset class="noEditable"><legend>Espécies Capturadas:</legend>
            <fieldset class="noEditable"><legend>Dados das Espécies Capturadas:</legend>

                <div id="base_espc">
                    <input onclick="jsInsertMonitoramento(this.form, '<?= $this->url(array("controller" => "ficha-diaria", "action" => "insertmonitoramento"), null, true) ?>')" type="button" value="Add row" />
                    <select style="float:left;" name="SelectEspecie">
                        <?php foreach ($this->especies as $key => $especie): ?>
                            <option value="<?= $especie['esp_id']; ?>"><?= $especie['esp_nome_comum']; ?></option>
                        <?php endforeach; ?>
                    </select>
                    <input style="float:left;" type="text" name="quantidade" placeholder="Quantidade" size="10px">
                    <input style="float:left;" type="text" name="peso" placeholder="Peso" size="10px">
                    <input style="float:left;" type="text" name="precokg" placeholder="Preço" size="10px">

                    <input type="hidden" name="id_entrevista"  value="<?= a//$this->fichadiaria['fd_id']     ?>"/>

                </div>

            </fieldset>
            <br>
            <fieldset class="noEditable" id="itemArteTipoRows"><legend>Espécies Capturadas:</legend>
                <table id="especiesCapturadas">
                    <tr>
                        <th width="20%">Id Entrevista</th>
                        <th width="30%">Espécie Capturada</th>
                        <th width="20%">Quantidade</th>
                        <th width="20%">Peso (kg)</th>
                        <th width="20%">Preço por kg</th>
                    </tr>
                    <?php
                    foreach ($this->vEspecieCapturadas as $key => $vEspecieCapturada):
                        ?>
                        <tr id="itemEmbarcacoesRows">
                            <td name="inputEntrevista"> <?= $vEspecieCapturada['af_id'] ?> </td>
                            <td name="inputEspecie" > <?= $vEspecieCapturada['esp_nome_comum'] ?> </td>
                            <td name="inputQuantidade"> <?= $vEspecieCapturada['spc_quantidade'] ?> </td>
                            <td name="inputPeso"> <?= $vEspecieCapturada['spc_peso_kg'] ?> </td>
                            <td name="inputPreco"> <?= $vEspecieCapturada['spc_preco'] ?> </td>
                            <td><input type="button" class="button-del" width="5%" onclick="jsDeleteEspecie(<?= $vEspecieCapturada['spc_id'] ?>, this.form, '<?= $this->url(array("controller" => "arrasto-fundo", "action" => "deletespecie"), null, true) ?>', <?= $vEspecieCapturada['af_id'] ?>)"></td>
                            
                        </tr>
                    <?php endforeach; ?>
                </table>
            </fieldset>
        </fieldset>   

    </form> 

</div>