<div id="titulos">
    <h2>Desembarque->Pesca de Manzuá</h2>
    <h3>Entrevista</h3>
</div>

<div id="esquerda-entrevista">
    <form action="<?= $this->url(array("controller" => "manzua", "action" => "atualizar"), null, true) ?>">
        <fieldset id="Entrevista">
            <div id="esquerda">
                <div id="form-esq">
                    <label>ID da ficha diária:</label>
                    <input type="text" name="id_fichaDiaria" placeholder="ID" disabled="true" value="<?= $this->monitoramento['fd_id'] ?>" /><br />
                </div>
                <div id="form-esq">
                    <label>ID monitoramento:</label>
                    <input type="text" name="id_monitoramento" placeholder="ID" disabled="true" value="<?= $this->monitoramento['mnt_id'] ?>" /><br />
                </div>
                <div id="form-esq">
                    <label for="tipo">ID Entrevista:</label>
                    <input type="text" placeholder = "ID" name="id_entrevista" disabled="true" value="<?= $this->entrevista['man_id'] ?>"/><br />
                </div>
            </div>
            <br/>
            <div id="esquerda">
                <legend><h4>Embarcação:</h4></legend>
                <div id="form-esq">
                    <label>Utilizou Barco?</label>
                    <input type="checkbox"  name="embarcada" <?php if($this->entrevista['man_embarcada'] === true){ echo 'checked';} else{ echo '';}?>/><br />
                </div>
                <div id="form-esq">
                    <label>Motor?</label>
                    <input type="checkbox"  name="motor"  <?php if($this->entrevista['man_motor'] === true){ echo 'checked';} else{ echo '';}?>/><br />
                </div>
                <div id="form-esq">
                    <label>Barco:</label>
                    <select name="nomeBarco" placeholder="Nome do Barco" />
                    <?php
                    foreach ($this->barcos as $key => $barco):
                        ?>
                        <option value="<?= $barco['bar_id'] ?>" <?=( $barco['bar_id'] == $this->entrevista['bar_id'])? 'selected="selected"': '';?>><?= $barco['bar_nome'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                    <br />
                </div>
                <div id="form-esq">
                    <label>Tipo de Barco:</label>
                    <select name="tipoBarco" />
                    <?php
                    foreach ($this->tipoEmbarcacoes as $key => $tipoEmbarcacao):
                        ?>
                        <option value="<?= $tipoEmbarcacao['tte_id'] ?>" <?=( $tipoEmbarcacao['tte_id'] == $this->entrevista['tte_id'])? 'selected="selected"': '';?>><?= $tipoEmbarcacao['tte_tipoembarcacao'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                    <br />
                </div>

            </div>
            <div id="direita-entrevista">
                <div id="form-esq">    
                    <label>Pescador Entrevistado:</label>
                    <select name="pescadorEntrevistado" />
                    <?php
                    foreach ($this->pescadores as $key => $pescador):
                        ?>
                        <option value="<?= $pescador['tp_id'] ?>" <?=( $pescador['tp_id'] == $this->entrevista['tp_id_entrevistado'])? 'selected="selected"': '';?>><?= $pescador['tp_nome'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                    <br />
                </div>
                <div id="form-esq">
                    <label>Quant. de Pescadores:</label>
                    <input type="number" name="numPescadores" min ="1" placeholder="QuantidadePescadores" value="<?=$this->entrevista['man_quantpescadores']?>"/><br />
                </div>
            </div>
            <div id="esquerda">
                <legend><h4>Saída e Volta:</h4></legend>
                <div id="form-esq">

                    <label>Data:</label>
                    <input type="date" name="dataSaida" min="2013-11-01" placeholder="Data da Saída" value="<?=$this->dataSaida?>"/>
                </div>
                <div id="form-esq">
                    <label>Horas:</label>
                    <input type="time" name="horaSaida" placeholder="Hora da Saída" value="<?=$this->horaSaida?>"/>
                </div>
            </div>
            <div id="direita-entrevista">
                <div id="form-esq">
                    <label>Data:</label>
                    <input type="date" name="dataVolta" min="2013-11-01" placeholder="Data da Volta" value="<?=$this->dataVolta?>"/>
                </div>
                <div id="form-esq">
                    <label>Horas:</label>
                    <input type="time" name="horaVolta" placeholder="Hora da Volta" value="<?=$this->horaVolta?>"/>
                </div>
            </div>
            <div id="esquerda">
                <div id="form-esq">
                    <label>Tempo Gasto:</label>
                    <input type="time" name="tempoGasto" placeholder="Data da Saída" value="<?=$this->entrevista['man_tempogasto']?>"/>
                </div>
            </div>
            <div id="esquerda">
                <div id="form-esq">
                    <legend><h4>Maré:</h4></legend>
                    <label>Tipo:</label>
                    <select name="mare" >
                        <?php
                        foreach ($this->mare as $key => $mare):
                            ?>
                            <option value="<?= $mare['mre_id'] ?>" <?=( $mare['mre_id'] == $this->entrevista['mre_id'])? 'selected="selected"': '';?>><?= $mare['mre_tipo'] ?></option>
                            <?php
                        endforeach;
                        ?>
                    </select>
                </div>
                <div id="form-dir">    
                    <label>Maré Viva?</label>
                    <input type="checkbox" name="mareviva" <?php if($this->entrevista['man_mreviva'] === true){ echo 'checked';} else{ echo '';}?>> 
                </div>
            </div><br/>
            <div id="esquerda">
                <div id="form-esq">
                    <legend><h4>Esforço:</h4></legend>
                    <label>Número de Armadilhas:</label>
                    <input type="text" name="numArmadilhas" placeholder="Armadilhas" value="<?=$this->entrevista['man_numarmadilhas']?>"/>
                </div>
            </div>
            <div id="esquerda">
                <legend><h4>Outros dados:</h4></legend>
                <div id="form-esq">    
                    <label>Destino do Pescado:</label>
                    <select name="destinoPescado" />
                    <?php
                    foreach ($this->destinos as $key => $destino):
                        ?>
                        <option value="<?= $destino['dp_id'] ?>" <?=( $destino['dp_id'] == $this->entrevista['dp_id'])? 'selected="selected"': '';?>><?= $destino['dp_destino'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                </div>
                <div id="form-esq">
                    <label for="tipo">Subamostra?:</label>
                    <input type="checkbox" name="subamostra" <?php if($this->entrevista['man_subamostra'] === true){ echo 'checked';} else{ echo '';}?>/><br />
                </div>
                <div id="form-esq">
                    <label for="tipo">Observacao:</label>
                    <input type="text" name="observacao" placeholder="Observacao" value="<?=$this->entrevista['man_obs']?>"/><br />
                </div>
                <div id="form-esq">
                    <label for="tipo">Combustível(L):</label>
                    <input type="text" name="combustivel" placeholder="Combustível" value="<?=$this->entrevista['man_combustivel']?>"/><br />
                </div>
                <input type="hidden" name="id_entrevista" value="<?= $this->entrevista['man_id'] ?>"/><br />
                
                <div id="Submit">
                    <input type="submit" value="Salvar Alterações"/>
                </div>
            </div>

        </fieldset>
    </form>
    <form>
        <input type="hidden" placeholder = "ID" name="id_entrevista"  value="<?= $this->entrevista['man_id'] ?>"/><br />
        <input type="hidden" name="id_monitoramento" placeholder="ID"  value="<?= $this->entrevista['mnt_id'] ?>" /><br />
        <input type="hidden" name="id_fichaDiaria" placeholder="ID"  value="<?= $this->monitoramento['fd_id'] ?>" /><br />
       
        <fieldset class="noEditable"><legend>Pesqueiro:</legend>
            <fieldset class="noEditable"><legend>Pesqueiro e tempo até o pesqueiro:</legend>
                <div id="base">
                    <input onclick="jsInsertPesqueiroWithTimeAndRange(this.form, '<?= $this->url(array("controller" => "manzua", "action" => "insertpesqueiro"), null, true) ?>', '<?= $this->entrevista['man_id'] ?>')" type="button" value="Adicionar" />
                    <select style="float:left;" name="nomePesqueiro">
                        <?php foreach ($this->pesqueiros as $key => $pesqueiro): ?>
                            <option value="<?= $pesqueiro['paf_id']; ?>"><?= $pesqueiro['paf_pesqueiro']; ?></option>
                        <?php endforeach; ?>
                    </select>
                    <input style="float:left;" type="time" name="tempoAPesqueiro" placeholder="Tempo Até pesqueiro" size="10px"/>
                    <input style="float:left;" type="number" name="distAPesqueiro" placeholder="Distância Até pesqueiro (km)" size="23px"/>

                </div>

            </fieldset>
            <br>
            <fieldset class="noEditable" id="itemArteTipoRows"><legend>Pesqueiros:</legend>
                <table id="pesqueiros">
                    <tr>
                        <th width="5%">Id Entrevista</th>
                        <th width="50%">Pesqueiro</th>
                        <th width="30%">Tempo até o Pesqueiro</th>
                        <th width="30%">Distância até o Pesqueiro</th>
                    </tr>
                    <?php
                    foreach ($this->vManzua as $key => $vManzua):
                        ?>
                        <tr id="itemManzuaRows">
                            <td name="inputIdEntrevista"> <?= $vManzua['man_id'] ?> </td>
                            <td name="inputPesqueiro" > <?= $vManzua['paf_pesqueiro'] ?> </td>
                            <td name="inputTempoaPesqueiro"> <?= $vManzua['t_tempoapesqueiro'] ?> </td>
                            <td name="inputTempoaPesqueiro"> <?= $vManzua['t_distapesqueiro'] ?> </td>
                            <td><input type="button" class="button-del" width="5%" onclick="jsDeletePesqueiro(<?= $this->entrevista['man_id'] ?>, '<?= $this->url(array("controller" => "manzua", "action" => "deletepesqueiro"), null, true) ?>', <?= $vManzua['man_paf_id'] ?>)"></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </fieldset>
        </fieldset>
<fieldset class="noEditable"><legend>Espécies Capturadas:</legend>
        <fieldset class="noEditable"><legend>Dados das Espécies Capturadas:</legend>

            <div id="base">
                <input onclick="jsInsertEspecieCapturadaTipoVenda(this.form, '<?= $this->url(array("controller" => "manzua", "action" => "insertespeciecapturada"), null, true) ?>','<?=$this->entrevista['man_id']?>')" type="button" value="Adicionar" />
                <select style="float:left;" name="SelectEspecie" class="espc">
                    <?php foreach ($this->especies as $key => $especie): ?>
                        <option value="<?= $especie['esp_id']; ?>"><?= $especie['esp_nome_comum']; ?></option>
                    <?php endforeach; ?>
                </select>
                <input style="float:left;" type="text" name="quantidade" placeholder="Quantidade" size="10px">
                <input style="float:left;" type="text" name="peso" placeholder="Peso" size="10px">
                <input style="float:left;" type="text" name="precokg" placeholder="Preço por kg" size="10px">
                <select name="tipoVenda" class="espc">
                     <?php foreach ($this->tipovenda as $key => $tipovenda): ?>
                        <option value="<?= $tipovenda['ttv_id']?>"><?= $tipovenda['ttv_tipovenda']; ?></option>
                     <?php endforeach; ?>
                </select>
                <input type="hidden" name="id_entrevista"  value="<?= $this->entrevista['man_id'] ?>"/>

            </div>

        </fieldset>
        <br>
         <fieldset class="noEditable" id="itemArteTipoRows"><legend>Espécies Capturadas:</legend>
                <table id="especiesCapturadas">
                    <tr>
                        <th width="20%">Id Entrevista</th>
                        <th width="30%">Espécie Capturada</th>
                        <th width="20%">Quantidade</th>
                        <th width="20%">Peso (kg)</th>
                        <th width="20%">Preço por kg</th>
                        <th width="10%">Venda</th>
                    </tr>
                    <?php
                    foreach ($this->vEspecieCapturadas as $key => $vEspecieCapturada):
                        ?>
                        <tr id="itemEmbarcacoesRows">
                            <td name="inputEntrevista"> <?= $vEspecieCapturada['man_id'] ?> </td>
                            <td name="inputEspecie" > <?= $vEspecieCapturada['esp_nome_comum'] ?> </td>
                            <td name="inputQuantidade"> <?= $vEspecieCapturada['spc_quantidade'] ?> </td>
                            <td name="inputPeso"> <?= $vEspecieCapturada['spc_peso_kg'] ?> </td>
                            <td name="inputPreco"> <?= $vEspecieCapturada['spc_preco'] ?> </td>
                            <td name="inputTVenda"> <?= $vEspecieCapturada['ttv_tipovenda']?></td>
                            <td><input type="button" class="button-del" width="5%" onclick="jsDeleteEspecieCapturada(<?= $this->entrevista['man_id'] ?>, '<?= $this->url(array("controller" => "manzua", "action" => "deletespecie"), null, true) ?>', <?= $vEspecieCapturada['spc_man_id'] ?>)"></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </fieldset>
    </fieldset>
    <fieldset class="noEditable"><legend>Avistamento:</legend>
        <fieldset class="noEditable"><legend>O Que foi avistado:</legend>
            <div id="base">
                <input onclick="jsInsertAvistamento(this.form, '<?= $this->url(array("controller" => "manzua", "action" => "insertavistamento"), null, true) ?>', '<?=$this->entrevista['man_id']?>')" type="button" value="Adicionar" />
                
                <select style="float:left;" name="SelectAvistamento">
                    <?php foreach ($this->avistamentos as $key => $avistamento): ?>
                        <option value="<?= $avistamento['avs_id']; ?>"><?= $avistamento['avs_descricao']; ?></option>
                    <?php endforeach; ?>
                </select>
                
            </div>

        </fieldset>
        <br>
        <fieldset class="noEditable" id="itemArteTipoRows"><legend>Avistamentos:</legend>
            <table id="pesqueiros">
                <tr>
                    <th width="5%">Id Avistamento</th>
                    <th width="50%">Avistamento</th>
                </tr>
                <?php
                foreach ($this->vManzuaAvistamento as $key => $vManzuaAvistamento):
                    ?>
                    <tr id="itemManzuaRows">
                        <td name="inputIdEntrevista"> <?= $vManzuaAvistamento['avs_id'] ?> </td>
                        <td name="inputAvistamento" > <?= $vManzuaAvistamento['avs_descricao'] ?> </td>
                        <td><input type="button" class="button-del" width="5%" onclick="jsDeleteAvistamento(<?= $this->entrevista['man_id'] ?>, '<?= $this->url(array("controller" => "manzua", "action" => "deleteavistamento"), null, true) ?>', <?= $vManzuaAvistamento['avs_id'] ?>)"></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </fieldset>
    </fieldset>    
    </form>        
    <br/> <br/>
    <a href="<?= $this->url(array("controller" => "ficha-diaria", "action" => "editar","id" => $this->monitoramento['fd_id']), null, true) ?>" id="botao-ancora">Voltar à Ficha-Diária</a>
    

</div>