<div id="titulos">
    <h2>Perfil Social->Tipo Telefone</h2>
    <h3>Editar</h3>
</div>

<form action="<?=$this->url(array("controller"=>"tipo-telefone","action"=>"atualizar"),null,true)?>" method="post">
   <input type="hidden" name="idTipoTelefone" value="<?= $this->assignTipoTelefone['ttel_id'] ?>" />
   <fieldset id="TipoTelefone">
     <div id="esquerda">   

     <div id="form-esq"> 
            <label>Tipo Telefone: </label>
            <input type="text" name="tipoTelefone" value="<?= $this->assignTipoTelefone['ttel_desc'] ?>"/> <br />
        </div>
        
        
         <div id="Submit">
            <a href="<?=$this->url(array("controller"=>"tipo-telefone","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a> 
            <input type="submit" value="Atualizar" />
        </div>
      </div> 
    </fieldset>
</form>