<?php
$this->headScript()->appendFile('/js/jquery.maskedinput.min.js');
$this->headScript()->appendFile('/js/mascaras.js');
?>

<div id="titulos">
    <h2>Desembarque->Ficha Diária</h2>
    <h3>Editar</h3>
</div>

<form id="formulario" action="<?=$this->url(array("controller"=>"ficha-diaria","action"=>"criar"),null,true)?>" method="post">
   <fieldset id="Desembarque">
      <div id="esquerda">
       <div id="form-esq">
         <label for="id">ID:</label>
         <input type="text" name="id_fichaDiaria" placeholder="Id" id="id_fichaDiaria" value="<?=$this->fichadiara['FD_ID']?>"/><br />
       </div>
       
       <div id="form-esq">
         <label for="tipo">Estagiário:</label>
         <select name="select_nome_estagiario" id="ficha_diaria_estagiario">
              <?php
                    foreach ($this->dados as $key => $estagiario):
               ?>
              
		<option nome="nome_estagiario" value="<?=$estagiario['TU_ID']?>"><?= $estagiario['TU_Nome']?></option>
              
              <?php
                endforeach;
              ?>
               
          </select></br>
        </div>
       
         <div id="form-esq">
            <label for="tipo">Monitor:</label>
            <select name="select_nome_monitor" id="ficha_diaria_monitor">
                 <?php
                       foreach ($this->dados as $key => $monitor):
                  ?>

                   <option nome="nome_monitor" value="<?=$monitor['TU_ID']?>"><?= $monitor['TU_Nome']?></option>

                 <?php
                   endforeach;
                 ?>
            </select></br>
         </div>
       
       <div id="form-esq">
         <label for="tipo">Data:</label>
         <input type="text" id="data_Viagem" placeholder="Data" name="data_ficha"value="<?=$this->fichadiara['FD_Data']?>"/><br />
       </div>
       
       <div id="form-esq">
         <label for="tipo">Turno:</label>
         <select name="select_turno" id="ficha_diaria_porto">
		<option nome="turno" value="Matutino">Matutino</option>
                <option nome="turno" value="Vespertino">Vespertino</option>
         </select></br>
       </div>
       
       
       <div id="form-esq">  
         <label for="tipo">Porto:</label>
         <select name="select_nome_porto" id="ficha_diaria_porto">
              <?php
                    foreach ($this->dados_porto as $key => $porto):
               ?>
              
		<option nome="nome_porto" value="<?=$porto['PTO_ID']?>"><?= $porto['PTO_Nome']?></option>
              
              <?php
                endforeach;
              ?>
         </select></br>
       </div>   
      
      <div id="form-esq">        
          <label for="tipo">Tempo: </label>
         <select name="select_tempo" id="ficha_diaria_tempo">
             <?php
                  foreach ($this->dados_tempo as $key => $tempo):
               ?>
              
		<option nome="tempo" value="<?=$tempo['TMP_ID']?>"><?= $vento['TMP_Estado']?></option>
              
              <?php
                endforeach;
              ?>
         </select><br/>
      </div>   
         
       <div id="form-esq"> 
         <label>Vento:</label> 
         <select name="select_vento" id="ficha_diaria_vento">
             <?php
                  foreach ($this->dados_vento as $key => $vento):
               ?>
              
		<option nome="tempo" value="<?=$vento['VNT_ID']?>"><?= $vento['VNT_Forca']?></option>
              
              <?php
                endforeach;
              ?>
             
         </select><br/><br/>  
       </div>
       
       <div id="form-esq">  
         <label for="tipo">Observação:</label>
         <input type="text-area" id="obs" name="obs"  value="<?=$this->fichadiara['OBS']?>"/><br />
         <br/>
       </div>
       
         <fieldset id="ArtePesca">
		Monitoramento:
		<table id="listas" >
		<tr class="linhas">
		<td>
		<select id="tam_medio" name="Arte_pesca[]" style="float:left" id="arte_da_pesca">
			<option   value="" selected="selected">Arte de Pesca...</option>
			<option   value="Arrasto de Fundo">Arrasto de Fundo</option>
                        <option   value="Pesca de Rede">Pesca de Rede</option>
                        <option   value="Pesca_de_Linha">Pesca de Linha</option>
			<option   value="Mariscagem">Mariscagem</option>
		</select>
		</td><br/>
		<td>Quantidade:<input type="text" name="qtd[]" id="numeric" /></td>
		<td>
		<select id="tam_medio" name="Embarcação[]"style="float:left">
                        <option   value="Embarcada" selected="selected">Embarcada</option>
                        <option   value="Não Embarcada">Não Embarcada</option>            
		</select>
		</td>
		<td>
		<select id="tam_medio" name="Monitorada[]"style="float:left">
                    <option   value="Monitorada" selected="selected">Monitorada</option>
                    <option   value="Não Monitorada">Não Monitorada</option>            
		</select>
		</td>
		<td class="td-botao">
                    <a  id="novaEntrevista" target="_blank">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-arrowreturnthick-1-e"></span></li>
                    </ul>
                    </a>
                </td>
		<td class="td-botao"> 
                    <a  class="removerCampo" title="Remover linha">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-circle-close"></span></li>
                    </ul>
                    </a>
		</td>
		</tr>
		</table>
		<br/>
                    <a class="adicionarCampo" title="Adicionar item">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-circle-plus"></span></li>
                    </ul>
                    </a>
      
           </fieldset>
	</div>
       <br/>
        <div id="Submit">
            <a href="<?=$this->url(array("controller"=>"ficha-diaria","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a> 
            <input type="submit" value="Atualizar" />
        </div>
   </fieldset>
</form> 