<?php   
//$this->headScript()->appendFile('/js/jquery.maskedinput.min.js');
//$this->headScript()->appendFile('/js/mascaras.js');
?>

<div id="titulos">
    <h2>Desembarque->Ficha Diária</h2>
    <h3>Editar</h3>
</div>
<head>
    <script type="text/javascript">
        var rowNumArte = 0;
        var Entrevista;
        function addRowArte(frm) {
            rowNumArte++;
            
            var linhaArte = '<div class="noEditable"><p id="itemArteTipoRows' + rowNumArte + '">';
            linhaArte = linhaArte.concat('<input type="button" value="Entrevista">');
            linhaArte = linhaArte.concat('<input type="button" value="Remove" onclick="removeRowNumArte(' + rowNumArte + ');">');

            linhaArte = linhaArte.concat('<input type="text" readonly size="10" name="inputEmbarcacao[]" value="' + frm.SelectEmbarcacao[frm.SelectEmbarcacao.selectedIndex].text + '">');
                
            linhaArte = linhaArte.concat('<input type="text" readonly size="10" name="inputMonitorada[]"  value="' + frm.SelectMonitorada[frm.SelectMonitorada.selectedIndex].text + '">');
            
            linhaArte = linhaArte.concat('<input type="text" readonly size="10" name="inputQuantidade[]"  value="' + frm.QuantidadeEmbarcacoes.value + '">');

            linhaArte = linhaArte.concat('<input type="text" readonly size=13 name="inputArte[]"  value="' + frm.SelectArtePesca[frm.SelectArtePesca.selectedIndex].text + '">');
            linhaArte = linhaArte.concat('<input type="text" readonly size="2" name="inputArteID[]"  value="' + frm.SelectArtePesca.value + '">');
            
            
            linhaArte = linhaArte.concat('<br></p></div>');

            jQuery('#itemArteTipoRows').append(linhaArte);
        }

        function removeRowNumArte(localRowNumArte) {
            jQuery('#itemArteTipoRows' + localRowNumArte).remove();
        }
    </script>
</head>
    <fieldset id="Desembarque">
        <div id="esquerda">
            <div id="form-esq">
                <label for="id">ID:</label>
                <input type="text" name="id_fichaDiaria" disabled="true" value="<?= $this->fichadiaria['fd_id'] ?>"/><br />
            </div>

            <div id="form-esq">
                <label for="tipo">Estagiário:</label>
                <select name="select_nome_estagiario" disabled="true">
                    <?php
                    foreach ($this->users as $key => $estagiario):
                        ?>

                        <option nome="nome_estagiario" value="<?= $estagiario['tu_id']; ?>"<?= ($estagiario['tu_id'] == $this->fichadiaria['t_estagiario_tu_id']) ? 'selected="selected"' : '' ?>><?= $estagiario['tu_nome'] ?></option>

                        <?php
                    endforeach;
                    ?>

                </select></br>
            </div>

            <div id="form-esq">
                <label for="tipo">Monitor:</label>
                <select name="select_nome_monitor" disabled="true">
                    <?php
                    foreach ($this->users as $key => $monitor):
                        ?>

                        <option nome="nome_monitor" value="<?= $monitor['tu_id']; ?>"<?= ($monitor['tu_id'] == $this->fichadiaria['t_monitor_tu_id1']) ? 'selected="selected"' : '' ?>><?= $monitor['tu_nome'] ?></option>

                        <?php
                    endforeach;
                    ?>
                </select></br>
            </div>

            <div id="form-esq">
                <label for="tipo">Data:</label>
                <input type="date" id="data_Viagem" placeholder="Data" name="data_ficha" disabled="true"value="<?= $this->fichadiaria['fd_data'] ?>"/><br />
            </div>

            <div id="form-esq">
                <label for="tipo">Turno:</label>
                <input disabled="true" nome="turno" <?= ('Matutino' == $this->fichadiaria['fd_turno']) ? 'value = "Matutino"' : 'value="Vespertino"' ?> >

            </div>


            <div id="form-esq">
                <label for="tipo">Porto:</label>
                <select name="select_nome_porto" disabled="true">
                    <?php
                    foreach ($this->dados_porto as $key => $porto):
                        ?>

                        <option nome="nome_porto" value="<?= $porto['pto_id'] ?>"<?= ($porto['pto_id'] == $this->fichadiaria['pto_id']) ? 'selected ="selected"' : '' ?> ><?= $porto['pto_nome'] ?></option>

                        <?php
                    endforeach;
                    ?>
                </select></br>
            </div>

            <div id="form-esq">
                <label for="tipo">Tempo: </label>
                <select name="select_tempo" disabled="true">
                    <?php
                    foreach ($this->dados_tempo as $key => $tempo):
                        ?>

                        <option nome="tempo" value="<?= $tempo['tmp_id'] ?>"<?= ($tempo['tmp_id'] == $this->fichadiaria['tmp_id']) ? 'selected ="selected"' : '' ?> ><?= $tempo['tmp_estado'] ?></option>

                        <?php
                    endforeach;
                    ?>
                </select><br/>
            </div>

            <div id="form-esq">
                <label>Vento:</label>
                <select name="select_vento" disabled="true">
                    <?php
                    foreach ($this->dados_vento as $key => $vento):
                        ?>

                        <option nome="tempo" value="<?= $vento['vnt_id'] ?>"<?= ($vento['vnt_id'] == $this->fichadiaria['vnt_id']) ? 'selected ="selected"' : '' ?> ><?= $vento['vnt_forca'] ?></option>

                        <?php
                    endforeach;
                    ?>

                </select><br/><br/>
            </div>

            <div id="form-esq">
                <label for="tipo">Observação:</label>
                <input type="text" id="obs" name="obs" disabled="true" value="<?= $this->fichadiaria['obs'] ?>"/><br />
                <br/>
            </div>

        </div>

        <br/>
        <br/>
<form id="formulario" action="<?= $this->url(array("controller" => "ficha-diaria", "action" => "atualizar"), null, true) ?>" method="post">
    </fieldset>
    <fieldset class="noEditable"><legend>Monitoramento:</legend>
        <fieldset class="noEditable"><legend>Artes de Pesca e quantidade de embarcacoes:</legend>
            
            <div id="base">
                <input onclick="addRowArte(this.form);" type="button" value="Add row" />
                <select id="tam_medio" name="SelectEmbarcacao"style="float:left">
                    <option   value="1" selected="selected">Embarcada</option>
                    <option   value="0">Não Embarcada</option>
                </select>
                <select id="tam_medio" name="SelectMonitorada"style="float:left">
                    <option   value="1" selected="selected">Monitorada</option>
                    <option   value="0">Não Monitorada</option>
                </select>
                <input type="text"name="QuantidadeEmbarcacoes" placeholder="Quantidade" size="10px">

                <select name="SelectArtePesca" id="artePesca">
                    <?php foreach ($this->artesPesca as $key => $artePesca): ?>
                        <option value="<?= $artePesca['tap_id']; ?>"><?= $artePesca['tap_artepesca']; ?></option>
                    <?php endforeach; ?>
                </select>

            </div>

        </fieldset>
        <br>
        <fieldset class="noEditable" id="itemArteTipoRows"><legend>Artes de Pesca e quantidade de embarcacoes listados:</legend>
            <!--Area para inserir os itens-->
        </fieldset>
        
    </fieldset>

</form>