<?php
$this->headLink()->appendStylesheet('/css/forms-nr-min.css');
?>
<h2>Desembarque->Ficha Diária</h2>

<a href="<?=$this->url(array("controller"=>"ficha-diaria","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>
<form id="formulario" action="<?=$this->url(array("controller"=>"ficha-diaria","action"=>"criar"),null,true)?>" method="post">
   <fieldset id="Desembarque">
      <legend ><h3>Ficha Diária:</h3></legend>
         <label for="id">ID:</label>
         <input type="text" name="id_fichaDiaria" id="id_fichaDiaria"/><br />
         <label for="tipo">Estagiário:</label>
         <select name="select_nome_estagiario" id="ficha_diaria_estagiario">
              <?php
                    foreach ($this->dados as $key => $estagiario):
               ?>
              
		<option nome="nome_estagiario" value="<?=$estagiario['TU_ID']?>"><?= $genero['TU_Nome']?></option>
              
              <?php
                endforeach;
              ?>
         </select></br>
         <label for="tipo">Monitor:</label>
         <select name="select_nome_monitor" id="ficha_diaria_monitor">
              <?php
                    foreach ($this->dados as $key => $monitor):
               ?>
              
		<option nome="nome_monitor" value="<?=$monitor['TU_ID']?>"><?= $monitor['TU_Nome']?></option>
              
              <?php
                endforeach;
              ?>
         </select></br>
         <label for="tipo">Data:</label>
         <input type="date" id="data" name="data_ficha"/><br />
         <label for="tipo">Hora de Chegada:</label>
         <input type="time" id="hora_chegada" name="hora_saida"/>
         <label for="tipo">Hora de Saída:</label>
         <input type="time" id="hora_saida" name="hora_saida"/><br />
         <label for="tipo">Porto:</label>
         <select name="select_nome_porto" id="ficha_diaria_porto">
              <?php
                    foreach ($this->dados_porto as $key => $porto):
               ?>
              
		<option nome="nome_porto" value="<?=$porto['PTO_ID']?>"><?= $porto['PTO_Nome']?></option>
              
              <?php
                endforeach;
              ?>
         </select></br>
              
         Tempo:
         <select name="select_tempo" id="ficha_diaria_tempo">
             <option nome="tempo" value="Sol">Sol</option>
             <option nome="tempo" value="Nublado">Nublado</option>
             <option nome="tempo" value="Chuva">Chuva</option>
         </select><br/>
         Vento:
         <select name="select_vento" id="ficha_diaria_vento">
             <option nome="vento" value="Forte">Forte</option>
             <option nome="vento" value="Moderado">Moderado</option>
             <option nome="vento" value="Fraco">Fraco</option>
             
         </select><br/><br/>
         <label for="tipo">Observação:</label>
         <input type="text" id="estado_tempo" name="estado_tempo" size="60px"/><br />
         <br/>
         <fieldset id="ArtePesca">
		Monitoramento:
		<table id="listas" >
		<tr class="linhas">
		<td>
		<select name="Arte_pesca[]" style="float:left" id="arte_da_pesca">
			<option value="" selected="selected">Arte de Pesca...</option>
			<option value="Arrasto de Fundo">Arrasto de Fundo</option>
                        <option value="Pesca de Rede">Pesca de Rede</option>
                        <option value="Pesca_de_Linha">Pesca de Linha</option>
			<option value="Mariscagem">Mariscagem</option>
		</select>
		</td><br/>
		<td>Quantidade:<input type="text" name="qtd[]" id="numeric"/></td>
		<td>
		<select name="Embarcação[]"style="float:left">
                        <option value="Embarcada" selected="selected">Embarcada</option>
                        <option value="Não Embarcada">Não Embarcada</option>            
		</select>
		</td>
		<td>
		<select name="Monitorada[]"style="float:left">
                    <option value="Monitorada" selected="selected">Monitorada</option>
                    <option value="Não Monitorada">Não Monitorada</option>            
		</select>
		</td>
		<td class="td-botao">
                    <a href="#" id="novaEntrevista" target="_blank">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-arrowreturnthick-1-e"></span></li>
                    </ul>
                    </a>
                </td>
		<td class="td-botao"> 
                    <a href="#rodape" class="removerCampo" title="Remover linha">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-circle-close"></span></li>
                    </ul>
                    </a>
		</td>
		</tr>
		</table>
		<br/>
                    <a href=""<?=$this->url(array("controller"=>"ficha-diaria","action"=>"#index"),null,true)?> class="adicionarCampo" title="Adicionar item">
                    <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-circle-plus"></span></li>
                    </ul>
                    </a>
                </fieldset>
					
        </form> 