<?php
$this->headScript()->appendFile('/js/jquery.maskedinput.min.js');
$this->headScript()->appendFile('/js/mascaras.js');
?>
<html dir="ltr">
    <head>
        <script type="text/javascript">
            var rowNumArte = 0;
            function addRowArte(frm) {
                rowNumArte++;

                var linhaArte = '<div class="noEditable"><p id="itemArteTipoRows' + rowNumArte + '">';
                linhaArte = linhaArte.concat('<input type="button" value="Remove" onclick="removeRowNumArte(' + rowNumArte + ');">');

                linhaArte = linhaArte.concat('<input type="text" readonly size="10" name="inputEmbarcacao[]" value="' + frm.SelectEmbarcacao[frm.SelectEmbarcacao.selectedIndex].text + '">');
                linhaArte = linhaArte.concat('<input type="text" readonly size="2" name="inputEmbarcacaoValue[]" value="' + frm.SelectEmbarcacao.value + '">');

                linhaArte = linhaArte.concat('<input type="text" readonly size="10" name="inputMonitorada[]" " value="' + frm.SelectMonitorada[frm.SelectMonitorada.selectedIndex].text + '">');
                linhaArte = linhaArte.concat('<input type="text" readonly size="2" name="inputMonitoradaValue[]" " value="' + frm.SelectMonitorada.value + '">');

                linhaArte = linhaArte.concat('<input type="text" readonly size="10" name="inputQuantidade[]" " value="'+ frm.QuantidadeEmbarcacoes.value+'">');
    
                linhaArte = linhaArte.concat('<input type="text" readonly size="10" name="inputArte[]" " value="' + frm.SelectArtePesca[frm.SelectArtePesca.selectedIndex].text + '">');
                linhaArte = linhaArte.concat('<input type="text" readonly size="2" name="inputArteID[]" " value="' + frm.SelectArtePesca.value + '">');
                
                //linhaArte = linhaArte.concat('<a 
                
                linhaArte = linhaArte.concat('<br></p></div>');

                jQuery('#itemArteTipoRows').append(linhaArte);
            }

            function removeRowNumArte(localRowNumArte) {
                jQuery('#itemArteTipoRows' + localRowNumArte).remove();
            }
            </script>
    </head>
<div id="titulos">
    <h2>Desembarque->Ficha Diária</h2>
    <h3>Novo</h3>
</div>


<form id="formulario" action="<?=$this->url(array("controller"=>"ficha-diaria","action"=>"criar"),null,true)?>" method="post">
   <fieldset id="Desembarque">
      <div id="esquerda">
       <div id="form-esq">
         <label for="id">ID:</label>
         <?php
                    foreach ($this->id as $key => $id):
               ?>
         <input type="text" name="id_fichaDiaria" placeholder="Id" id="id_ficha" value="<?=$id['fd_id']+1?>" /><br />
       <?php
                endforeach;
              ?>
       </div>
       
       <div id="form-esq">
         <label for="tipo">Estagiário:</label>
         <select name="select_nome_estagiario" >
              <?php
                    foreach ($this->users as $key => $estagiario):
               ?>
              
		<option nome="nome_estagiario" value="<?=$estagiario['tu_id']?>"><?= $estagiario['tu_nome']?></option>
              
              <?php
                endforeach;
              ?>
               
          </select></br>
        </div>
       
         <div id="form-esq">
            <label for="tipo">Monitor:</label>
            <select name="select_nome_monitor" >
                 <?php
                       foreach ($this->users as $key => $monitor):
                  ?>

                   <option nome="nome_monitor" value="<?=$monitor['tu_id']?>"><?= $monitor['tu_nome']?></option>

                 <?php
                   endforeach;
                 ?>
            </select></br>
         </div>
       
       <div id="form-esq">
         <label for="tipo">Data:</label>
         <input type="date"  placeholder="Data" name="data_ficha"/><br />
       </div>
       
       <div id="form-esq">
         <label for="tipo">Turno:</label>
         <select name="select_turno" >
		<option nome="turno" value="Matutino">Matutino</option>
                <option nome="turno" value="Vespertino">Vespertino</option>
         </select></br>
       </div>
       
       
       <div id="form-esq">  
         <label for="tipo">Porto:</label>
         <select name="select_nome_porto" >
              <?php
                    foreach ($this->dados_porto as $key => $porto):
               ?>
              
		<option nome="nome_porto" value="<?=$porto['pto_id']?>"><?=$porto['pto_nome']?></option>
              
              <?php
                endforeach;
              ?>
         </select></br>
       </div>   
      
      <div id="form-esq">        
          <label for="tipo">Tempo: </label>
         <select name="select_tempo">
             <?php
                  foreach ($this->dados_tempo as $key => $tempo):
               ?>
              
		<option nome="tempo" value="<?=$tempo['tmp_id']?>"><?=$tempo['tmp_estado']?></option>
              
              <?php
                endforeach;
              ?>
         </select><br/>
      </div>   
         
       <div id="form-esq"> 
         <label>Vento:</label> 
         <select name="select_vento" id="ficha_diaria_vento">
             <?php
                  foreach ($this->dados_vento as $key => $vento):
               ?>
              
		<option nome="tempo" value="<?=$vento['vnt_id']?>"><?= $vento['vnt_forca']?></option>
              
              <?php
                endforeach;
              ?>
             
         </select><br/><br/>  
       </div>
       
       <div id="form-esq">  
         <label for="tipo">Observação:</label>
         <input type="text" id="estado_tempo" name="observacao" /><br />
         <br/>
       </div>
       <div id="Submit">
            <input type="submit" value="SalvarFicha" />           
       </div>
   </div>
       <br/>
       <fieldset class="noEditable"><legend>Monitoramento:</legend>
            <fieldset class="noEditable"><legend>Artes de Pesca e quantidade de embarcacoes:</legend>

                <div id="base">
                    <input onclick="addRowArte(this.form);" type="button" value="Add row" />
                    <select id="tam_medio" name="SelectEmbarcacao"style="float:left">
                        <option   value="1" selected="selected">Embarcada</option>
                        <option   value="0">Não Embarcada</option>            
                    </select>
                    <select id="tam_medio" name="SelectMonitorada"style="float:left">
                        <option   value="1" selected="selected">Monitorada</option>
                        <option   value="0">Não Monitorada</option>            
                    </select>
                    <input type="text"name="QuantidadeEmbarcacoes" placeholder="Quantidade" size="10px">
                    
                    <select name="SelectArtePesca" id="artePesca">
                        <?php foreach ($this->artesPesca as $key => $artePesca): ?>
                            <option value="<?= $artePesca['tap_id']; ?>"><?= $artePesca['tap_artepesca']; ?></option>
                        <?php endforeach; ?>
                    </select>
                    
                </div>

            </fieldset>
            <br>
            <fieldset class="noEditable" id="itemArteTipoRows"><legend>Artes de Pesca e quantidade de embarcacoes listados:</legend>
                <!--Area para inserir os itens-->
            </fieldset>
        </fieldset>
         <br/>
       <div id="Submit">
            <a href="<?=$this->url(array("controller"=>"ficha-diaria","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>           
       </div>
         
   </fieldset>
</form> 