<div id="titulos">
    <h2>Desembarque->Entrevistas</h2>
    <h3>Novo</h3>
</div>
<div id="esquerda">
        <form>
              <fieldset id="Desembarque">
              <div id="form-esq">
                <label>ID da ficha diária:</label>
                <input type="text" name="id_fichaDiaria" placeholder="ID" id="id_fichaDiaria" /><br />
              </div>
              <div id="form-esq">
                <label for="tipo">ID Entrevista:</label>
                <input type="text" id="id_entrevista" placeholder = "ID" name="id_entrevista"/><br />
              </div>
              <div id="form-esq">
                <label for="tipo">Arte de Pesca:</label>
                <input type="text" id="arte_pesca" name="arte_pesca" placeholder="Arte de Pesca"/><br />	
              </div>
              
              <div id="direita">
		<legend><h4>Embarcação</h4></legend>
			<div id="form-esq">
                            <label>Barco:</label>
                            <input type="text" id="nome" name="barco" placeholder="Nome do Barco" /><br />
                        </div>
                        <div id="form-esq">
                            <label>Tipo de Barco:</label>
                            <input type="text" id="nome" name="tipo_barco" placeholder="Tipo de Barco"/><br />
                        </div>
                        <div id="form-esq">    
                            <label >Mestre:</label>
                            <input type="text" id="nome" name="mestre" placeholder="Nome do Mestre"/><br />
                        </div>
                        <div id="form-esq">
                            <label>Qtd de Pescadores:</label>
                            <input type="text" id="numeric" name="num_pescadores" placeholder="Num"/><br />
                        </div>
              </div>
              <div id="form-esq">
                    <label for="tipo">Subamostra?:</label>
                    <input type="checkbox" id="subamostra" name="subamostra" /><br />
              </div>
              <div id="form-esq">
                    <label for="tipo">Id Subamostra:</label>
                    <input type="text" id="nd_subamostra" name="id_subamostra" placeholder="Id da Subamostra"/><br />
              </div>
              
            </fieldset>
            <div id="Submit">
                <input type="submit" value="Cadastrar Ficha"/>
            </div>
            </form> 
        </div>
<div id="accordion">
  <!-- PESCA DE REDE --------------------------------------------------------------------------------------->
  <h3>Pesca de Rede</h3>
    <div>
       <div id="esquerda-entrevista">
        <form id="formulario_Entrevista" action="" method="post">
              <fieldset id="Desembarque">
                
                <div id="form-esq">
                    <label for="tipo">Pesqueiro:</label>
                    <input type="text" id="nome_pesqueiro" name="nome_pesqueiro_pescaLinha"/>
                </div>
                <div id="form-esq">
                    Tipo de Pesca:
                    <select name="Tipo_Pesca[]" >
                        <option value="" selected="selected">Tipo de Pesca</option>
                        <option value="Vara de Mão">Emalhe</option>
                        <option value="Tarrafa">Calão</option>
                        <option value="Rede de Emalhe">Tarrafa</option>        
                    </select>
                </div>
                <div id="form-esq">
                    <label for="tipo">Outra, Qual?:</label>
                    <input type="text" id="artePescaLinha" name="OutraartePescaLinha"/>
                    <br/>    
                </div>
                <div id="form-esq">
                    <label for="tipo">Destino</label>
                    <input type="text" id="nome_pesqueiro" name="nome_pesqueiro_pescaLinha"/> 
                </div>
                <div id="form-esq">
                    <label for="tipo">Diesel(L):</label>
                    <input type="text" id="nome_pesqueiro" name="nome_pesqueiro_pescaLinha"/>
                </div>
                <div id="form-esq">
                    <label for="tipo">Óleo(L):</label>
                    <input type="text" id="nome_pesqueiro" name="nome_pesqueiro_pescaLinha"/>
                </div>
                <div id="form-esq">
                    <label for="tipo">Alimento(R$):</label>
                    <input type="text" id="nome_pesqueiro" name="nome_pesqueiro_pescaLinha"/>
                </div>
                <div id="form-esq">
                    <label for="tipo">Gelo(R$):</label>
                    <input type="text" id="nome_pesqueiro" name="nome_pesqueiro_pescaLinha"/>
                </div>
                <div id="form-esq">
                    <label for="tipo">Avistamento:</label>
                    <input type="text" id="nome_pesqueiro" name="nome_pesqueiro_pescaLinha"/>
                </div>
       </div> 
                <fieldset id="EspecieCapturada">
                    <td><label for="tipo">Quantidade de Peixes Capturadas:</label></td>
                    <table style="border:none">
                        <tr class="linhas">
			<br/>
                        <td>
                            <select name="Especie[]" id="Especie">
                                <option value="" selected="selected">Espécie</option>
                            </select>
			</td>
                        <td>
                            <label>Quantidade</label>
                            <input type="text" name="qtd_peixes[]" id="numeric"/>
                        </td>
                        <td>
                            <label for="tipo">Peso (Kg):</label>
                            <input type="text" id="numeric" name="peso_pescaLinha"/>           
                        </td>
                        <td>
                            <label for="tipo">Preço por Kg:</label>
                            <input type="text" id="numeric" name="preco_pescaLinha"/>           
                        </td>
			<td>
                            <a  class="removerCampo" title="Remover linha">Remove Campo</a>
                        </td>
			</tr>
                    </table>
                    <br/>
                <a class="adicionarCampo" title="Adicionar item">Add Campo</a>
                </fieldset>
                     
            <div id="Submit">
                <input type="submit" value="Enviar"/>
            </div>
        </form>
       
    </div>
<!-- PESCA DE LINHA --------------------------------------------------------------------------------------->
  <h3>Pesca de Linha</h3>
    <div>
       <div id="esquerda-entrevista">
        <form id="formulario_Entrevista" action="" method="post">
              <fieldset id="Desembarque">
                <div id="form-esq">
                    <label for="tipo">Pesqueiro:</label>
                    <input type="text" id="nome_pesqueiro" name="nome_pesqueiro_pescaLinha"/>
                </div>
                <div id="form-esq">
                    Tipo de Pesca:
                    <select name="Tipo_Pesca[]" >
                        <option value="" selected="selected">Tipo de Pesca</option>
                        <option value="Vara de Mão">Linha de Mão</option>
                        <option value="Tarrafa">Espinhel/Grosseira</option>
                        <option value="Rede de Emalhe">Outra</option>        
                    </select>
                </div>
                <div id="form-esq">
                    <label for="tipo">Outra, Qual?:</label>
                    <input type="text" id="artePescaLinha" name="OutraartePescaLinha"/>
                    <br/>    
                </div>
                <div id="form-esq">
                    <label for="tipo">Destino</label>
                    <input type="text" id="nome_pesqueiro" name="nome_pesqueiro_pescaLinha"/> 
                </div>
                <div id="form-esq">
                    <label for="tipo">Diesel(L):</label>
                    <input type="text" id="nome_pesqueiro" name="nome_pesqueiro_pescaLinha"/>
                </div>
                <div id="form-esq">
                    <label for="tipo">Óleo(L):</label>
                    <input type="text" id="nome_pesqueiro" name="nome_pesqueiro_pescaLinha"/>
                </div>
                <div id="form-esq">
                    <label for="tipo">Alimento(R$):</label>
                    <input type="text" id="nome_pesqueiro" name="nome_pesqueiro_pescaLinha"/>
                </div>
                <div id="form-esq">
                    <label for="tipo">Gelo(R$):</label>
                    <input type="text" id="nome_pesqueiro" name="nome_pesqueiro_pescaLinha"/>
                </div>
                <div id="form-esq">
                    <label for="tipo">Avistamento:</label>
                    <input type="text" id="nome_pesqueiro" name="nome_pesqueiro_pescaLinha"/>
                </div>
                <div id="form-esq">
                    <label for="tipo">Qtd Linhas:</label>
                    <input type="text" id="nome_pesqueiro" name="nome_pesqueiro_pescaLinha"/>
                </div>
                <div id="form-esq">
                    <label for="tipo">Anzóis p/linha:</label>
                    <input type="text" id="nome_pesqueiro" name="nome_pesqueiro_pescaLinha"/>
                </div>
                  <div id="form-esq">
                    <label for="tipo">Isca:</label>
                    <input type="text" id="nome_pesqueiro" name="nome_pesqueiro_pescaLinha"/>
                </div>  
       </div> 
                <fieldset id="EspecieCapturada">
                    <td><label for="tipo">Quantidade de Peixes Capturadas:</label></td>
                    <table style="border:none">
                        <tr class="linhas">
			<br/>
                        <td>
                            <select name="Especie[]" id="Especie">
                                <option value="" selected="selected">Espécie</option>
                            </select>
			</td>
                        <td>
                            <label>Quantidade</label>
                            <input type="text" name="qtd_peixes[]" id="numeric"/>
                        </td>
                        <td>
                            <label for="tipo">Peso (Kg):</label>
                            <input type="text" id="numeric" name="peso_pescaLinha"/>           
                        </td>
                        <td>
                            <label for="tipo">Preço por Kg:</label>
                            <input type="text" id="numeric" name="preco_pescaLinha"/>           
                        </td>
			<td>
                            <a  class="removerCampo" title="Remover linha">Remove Campo</a>
                        </td>
			</tr>
                    </table>
                    <br/>
                <a class="adicionarCampo" title="Adicionar item">Add Campo</a>
                </fieldset>
                     
            <div id="Submit">
                <input type="submit" value="Enviar"/>
            </div>
        </form>
                
      
    </div>
<!-- ARRASTO DE FUNDO --------------------------------------------------------------------------------------->
  <h3>Arrasto de Fundo</h3>
    <div>
       
        <form id="formulario_Entrevista" action="" method="post">
           <div id="esquerda-entrevista">
              <fieldset id="Desembarque">
             
                <div id="form-esq">
                    <label for="tipo">Tempo ao Pesqueiro:</label>
                    <input type="text" id="nome_pesqueiro" name="nome_pesqueiro_pescaLinha"/>
                </div>
          </div>
        <fieldset id="Pesqueiros">
            <td>Quais Pesqueiros e Quanto tempo em cada:</td>
               <table style="border:none">
               <tr class="linhas">
               <br/>
               <td>
                   <select name="Pesqueiro[]" style="float:left">
                    <option value="" selected="selected">Pesqueiro</option>
                   </select>
               </td>
               <td>
                   <label>Tempo</label>
                   <input type="text" name="qtd_peixes[]" id="numeric"/>
               </td>
               <td>
                   <a  class="removerCampo" title="Remover linha">Remove Campo</a>
               </td>
                            
              </tr>
              </table>
                      
            <a href="#rodape" class="adicionarCampo" title="Adicionar item">Add Campo</a>
       </fieldset>
              

       <fieldset id="ArtePesca">
          <td><label for="tipo">Quantidade de Peixes Capturadas:</label></td>
              <table style="border:none">
              <tr class="linhas">
              <br/>
              <td>
                  <select name="Especie[]" id="Especie">
                      <option value="" selected="selected">Espécie</option>
                  </select>
	      </td>
              <td>
                  <label>Quantidade</label>
                  <input type="text" name="qtd_peixes[]" id="numeric"/>
              </td>
              <td>
                  <label for="tipo">Peso (Kg):</label>
                  <input type="text" id="numeric" name="peso_pescaLinha"/>           
              </td>
              <td>
                  <label for="tipo">Preço por Kg:</label>
                  <input type="text" id="numeric" name="preco_pescaLinha"/>           
              </td>
              <td>
                  <a class="removerCampo" title="Remover linha">Remove Campo</a>
              </td>
	      </tr>
              </table>
              <br/>
              <a  class="adicionarCampo" title="Adicionar item">Add Campo</a>
       </fieldset>
						
            <div id="Submit">
                <input type="submit" value="Enviar"/>
            </div>
        
    </form>
      
    </div>
<!-- MARISCAGEM --------------------------------------------------------------------------------------->
  <h3>Mariscagem</h3>
  <div>
        <form id="formulario_Entrevista" action="" method="post">
            <div id="esquerda-entrevista">
              <fieldset id="Desembarque">

                <div id="form-esq">
                    <label>Arte de Pesca:</label>
                    <select name="Tipo_Pesca[]" >
                        <option value="" selected="selected">Arte de Pesca</option>
                        <option value="Vara de Mão">Linha de Mão</option>
                        <option value="Tarrafa">Espinhel/Grosseira</option>
                        <option value="Rede de Emalhe">Outra</option>        
                    </select>
                </div>
                <div id="form-esq">
                    <label for="tipo">Outra, Qual?:</label>
                    <input type="text" id="artePescaLinha" name="OutraartePescaLinha"/>
                    <br/>    
                </div>
                <div id="form-esq">
                    <label>Maré:</label>
                    <select name="Tipo_Pesca[]" >
                        <option value="Vara de Mão"  selected="selected">Viva</option>
                        <option value="Tarrafa">Morta</option>     
                    </select>
                    <select name="Tipo_Pesca[]" >
                        <option value="Vara de Mão"  selected="selected">Enchente</option>
                        <option value="Tarrafa">Vazante</option>     
                    </select>
                </div>
                <br/>
                <div id="form-esq">
                    <label for="tipo">Tempo p/Pesq.:</label>
                    <input type="text" id="artePescaLinha" name="OutraartePescaLinha"/>
                    <br/>    
                </div>
                <div id="form-esq">
                    <label for="tipo">Dist p/Pesq.(Km):</label>
                    <input type="text" id="artePescaLinha" name="OutraartePescaLinha"/>
                    <br/>    
                </div>
                <div id="form-esq">
                    <label for="tipo">Qtd Combust.(L):</label>
                    <input type="text" id="artePescaLinha" name="OutraartePescaLinha"/>
                    <br/>    
                </div>
                <div id="form-esq">
                    <label for="tipo">Tempo Marisc.:</label>
                    <input type="text" id="artePescaLinha" name="OutraartePescaLinha"/>
                    <br/>    
                </div>
                <div id="form-esq">
                    <label for="tipo">Dist p/Pesq.(Km):</label>
                    <input type="text" id="artePescaLinha" name="OutraartePescaLinha"/>
                    <br/>    
                </div>
              </fieldset>  
           </div>
            
                <fieldset id="EspecieCapturada">
                    <td><label for="tipo">Quantidade de Peixes Capturadas:</label></td>
                    <table style="border:none">
                        <tr class="linhas">
			<br/>
                        <td>
                            <select name="Especie[]" id="Especie">
                                <option value="" selected="selected">Espécie</option>
                            </select>
			</td>
                        <td>
                            <label>Quantidade</label>
                            <input type="text" name="qtd_peixes[]" id="numeric"/>
                        </td>
                        <td>
                            <label for="tipo">Peso (Kg):</label>
                            <input type="text" id="numeric" name="peso_pescaLinha"/>           
                        </td>
                        <td>
                            <label for="tipo">Preço por Kg:</label>
                            <input type="text" id="numeric" name="preco_pescaLinha"/>           
                        </td>
			<td>
                            <a href="#rodape" class="removerCampo" title="Remover linha">Remove Campo</a>
                        </td>
			</tr>
                    </table>
                    <br/>
                <a href="#rodape" class="adicionarCampo" title="Adicionar item">Add Campo</a>
                </fieldset>
						
            <div id="Submit">
                <input type="submit" value="Enviar"/>
            </div>
        </form>
      
    </div>
</div>