<fieldset id="Entrevista"></fieldset>
    <form name="arrasto-fundo" method="post">

        <h2>Todas Entrevistas Cadastradas - Limite(50)</h2>

        <table id="tabelaSemEstilo" >
            <tr>

                <td>
                    <input type="button" size="50" value="Limpar" class="button-confirmText" onclick="jsClearBuscaEntrevista('<?= $this->url(array("controller" => "entrevista-pescador", "action" => "index"), null, true) ?>')">
                </td>
                <td>
                    <input type="button" size="50" value="Listar Todos" class="button-confirmText" onclick="jsBuscaTodasFichas('<?= $this->url(array("controller" => "entrevista-pescador", "action" => "index", "ent_all"=>"all"), null, true) ?>')">
                </td>
                <td>
                    <input type="button" size="30" value="Busca por Data" class="button-confirmText" onclick="jsBuscaData(this.form, '<?= $this->url(array("controller" => "entrevista-pescador", "action" => "index"), null, true) ?>')">
                    <input type="date" min="0" name="inputData" id="small" placeholder="Busca por Data" />
                </td>
            </tr>
            <tr>
                <td>
                    <input type="button" size="50" value="Busca por Pescador" class="button-confirmText" onclick="jsBuscaPescadorGeral(this.form, '<?= $this->url(array("controller" => "entrevista-pescador", "action" => "index"), null, true) ?>')">
                    <input type="text" min="0" name="inputPescador" id="small" placeholder="Busca por Pescador" />
                </td>

                <td>
                    <input type="button" size="40" value="Busca por Barco" class="button-confirmText" onclick="jsBuscaBarcoGeral(this.form, '<?= $this->url(array("controller" => "entrevista-pescador", "action" => "index"), null, true) ?>')">
                    <input type="text" min="0" name="inputBarco" id="small" placeholder="Busca por Barco" />
                </td>
                <td>
                    <input type="button" size="30" value="Busca por Apelido" class="button-confirmText" onclick="jsBuscaPescadorApelido(this.form, '<?= $this->url(array("controller" => "entrevista-pescador", "action" => "index"), null, true) ?>')">
                    <input type="text" min="0" name="inputApelido" id="small" placeholder="Busca por Apelido" />
                </td>
                <td>
                    <input type="button" size="30" value="Busca por Porto" class="button-confirmText" onclick="jsBuscaPescadorPorto(this.form, '<?= $this->url(array("controller" => "entrevista-pescador", "action" => "index"), null, true) ?>')">
                    <input type="text" min="0" name="inputPorto" id="small" placeholder="Busca por Porto" />
                </td>
            </tr>
        </table>
        <table>
            <tr>
                <th>Arte de Pesca</th>
                <th>Entrevista</th>
                <th>Pescador</th>
                <th>Apelido</th>
                <th>Barco</th>
                <th>Porto</th>
                <th>Data</th>
            </tr>

            <?php foreach ($this->dados as $key => $entrevista): ?>
                <tr>
                    <td><b><?= $entrevista['artepesca']?></b></td>
                    <td><?= $entrevista['id'] ?></td>
                    <td><?= $entrevista['tp_nome'] ?></td>
                    <td><?= $entrevista['tp_apelido'] ?></td>
                    <td><?= $entrevista['bar_nome'] ?></td>
                    <td><?= $entrevista['pto_nome'] ?></td>
                    <td><?= date("d-m-Y", strtotime($entrevista['data']))  ?></td>

                    <td>
                       <input type="button" width="10%" target="_blank" value ="Editar" onclick="jsEditarEntrevistas('<?= $entrevista['artepesca']?>',<?= $entrevista['id'] ?>)"/></td>

                    </td>

         

                    </a>

                </tr>
            <?php endforeach; ?>
        </table>
        <br/><br/>
    </form>
