<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-54122257-1', 'auto');
  ga('send', 'pageview');

</script>

<h2>Bem vindo ao <i>Rachycentron</i></h2>

<div class="imgefeito"> 
<a href="#"> 
    <img src="img/rachycentron_index.png" alt="Rachycentron" title="Figura Ilustrativa do Rachycentron Canadum"/> 
</a>
    <br/>
    <label id="titulo-img">Figura Ilustrativa do Rachycentron Canadum.</label>
</div>
<p>
Rachycentron é um software desenvolvido especificamente para o Projeto de Monitoramento da Atividade Pesqueira realizado pela UESC, ISUS e BAMIN. 
Integra todas as variáveis coletadas, permitindo cruzamento de dados que proporciona uma melhor compreensão da dinâmica pesqueira local.		 	          
</p>

<br/>
<p>
Rachycentron é o nome científico do peixe Beijupirá. Considerado o “Rei dos Peixes” em razão do seu tamanho e nobre sabor. 
A logomarca possui a cor azul que representa sabedoria e infinito que estão associados a robustez e a capacidade operacional do software. 
</p>
