<h2>Lista de Artes de Pesca</h2>

<a href="<?=$this->url(array("controller"=>"arte-pesca","action"=>"novo"),null,true)?>" id="botao-ancora">Novo</a>

<table>
    <tr>
        <th>Arte de Pesca</th>
    </tr>
    
    <?php
    foreach ($this->dados as $key => $artePesca):
    ?>
    <tr>
        <td><?= $artePesca['TAP_ArtePesca'] ?></td>
        <td class="td-botao">
            <a href="<?=$this->url(array("controller"=>"arte-pesca","action"=>"editar", "id" => $artePesca['TAP_ID']),null,true)?>">
                <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                </ul>
            </a>
        </td>
        <td class="td-botao">
            <a href="<?=$this->url(array("controller"=>"arte-pesca","action"=>"excluir", "id" => $artePesca['TAP_ID']),null,true)?>">
                <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-trash"></span></li>
                </ul>
            </a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>