<h2>Perfil Social->Arte de Pesca</h2>
<h3>Novo</h3>

<a href="<?=$this->url(array("controller"=>"arte-pesca","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>

<form action="<?=$this->url(array("controller"=>"arte-pesca","action"=>"criar"),null,true)?>" method="post">
    <fieldset id="Social">
    <div id="esquerda">
        <div id="form-esq">

            <label>Arte de Pesca:</label> 
            <input type="text" name="artePesca" placeholder="Arte de Pesca" accept=""value="<?=$this->artePesca['TAP_ArtePesca']?>"/> <br />
        </div>
        <div id="Submit">    
            <input type="submit" value="Enviar" />
        </div>

    </div>
    </fieldset>
</form>