<div id="titulos">
    <h2>Desembarque->Pesca de Emalhe</h2>
    <h3>Entrevista</h3>
</div>

<div id="esquerda-entrevista">
    <form action="<?= $this->url(array("controller" => "emalhe", "action" => "criar"), null, true) ?>">
        <fieldset id="Desembarque">
            <div id="esquerda">
                <div id="form-esq">
                    <label>ID da ficha diária:</label>
                    <input type="text" name="id_fichaDiaria" placeholder="ID" disabled="true" value="<?= $this->fichaDiaria['fd_id'] ?>" /><br />
                </div>
                <div id="form-esq">
                    <label>ID Monitoramento:</label>
                    <input type="text" name="id_monitoramento" placeholder="ID"  value="<?= $this->monitoramento['mnt_id'] ?>" /><br />
                </div>
                <div id="form-esq">
                    <label for="tipo">ID Entrevista:</label>
                    <input type="text" placeholder = "ID" name="id_entrevista" disabled="true"/><br />
                </div>
            </div>
            <br/>
            <div id="esquerda">
                <legend><h4>Embarcação:</h4></legend>
                <div id="form-esq">
                    <label>Utilizou Barco?</label>
                    <input type="checkbox"  name="embarcada" checked="true"/><br />
                </div>
                <div id="form-esq">
                    <label>Motor?</label>
                    <input type="checkbox"  name="motor"/><br />
                </div>
                <div id="form-esq">
                    <label>Barco:</label>
                    <select name="nomeBarco" placeholder="Nome do Barco" />
                    <?php
                    foreach ($this->barcos as $key => $barco):
                        ?>
                        <option value="<?= $barco['bar_id'] ?>"><?= $barco['bar_nome'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                    <br />
                </div>
                <div id="form-esq">
                    <label>Tipo de Barco:</label>
                    <select name="tipoBarco" />
                    <?php
                    foreach ($this->tipoEmbarcacoes as $key => $tipoEmbarcacao):
                        ?>
                        <option value="<?= $tipoEmbarcacao['tte_id'] ?>"><?= $tipoEmbarcacao['tte_tipoembarcacao'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                    <br />
                </div>
            </div>
            <div id="direita-entrevista">
                <div id="form-esq">    
                    <label>Pescador Entrevistado:</label>
                    <select name="pescadorEntrevistado" />
                    <?php
                    foreach ($this->pescadores as $key => $pescador):
                        ?>
                        <option value="<?= $pescador['tp_id'] ?>"><?= $pescador['tp_nome'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                    <br />
                </div>
                <div id="form-esq">
                    <label>Qtd de Pescadores:</label>
                    <input type="number" name="numPescadores" placeholder="QuantidadePescadores"/><br />
                </div>
            </div>
            <div id="esquerda">
                <legend><h4>Lançamento e Recolhimento:</h4></legend>
                <div id="form-esq">
                    <label>Data:</label>
                    <input type="date" name="dataLancamento" placeholder="Lançamento"/>
                </div>
                <div id="form-esq">
                    <label>Hora:</label>
                    <input type="time" name="horaLancamento" placeholder="Lançamento"/>
                </div>
            </div>
            <div id="direita-entrevista">
                <div id="form-esq">
                    <label>Data:</label>
                    <input type="date" name="dataRecolhimento" placeholder="Recolhimento"/>
                </div>
                <div id="form-esq">
                    <label>Hora:</label>
                    <input type="time" name="horaRecolhimento" placeholder="Recolhimento"/>
                </div>
            </div>
            <div id="esquerda">
                <div id="form-esq">
                    <legend><h4>Gastos:</h4></legend>
                    <label>Diesel(L):</label>
                    <input type="text"  name="diesel" placeholder="Diesel"/>
                </div>
                <div id="form-dir">    
                    <label>Óleo(L):</label>
                    <input type="text"  name="oleo" placeholder="Óleo"/><br />
                </div>
            </div>
            <div id="direita-entrevista">
                <div id="form-dir">    
                    <label>Alimento($):</label>
                    <input type="text"  name="alimento" placeholder="Alimento"/><br />
                </div>
                <div id="form-dir">    
                    <label>Gelo($):</label>
                    <input type="text"  name="gelo" placeholder="Gelo"/><br />
                </div>
            </div>
            <div id="esquerda">
                <div id="form-esq">
                    <legend><h4>Esforço:</h4></legend>
                    <label>Tamanho(m):</label>
                    <input type="text"  name="tamanho" placeholder="Tamanho"/>
                </div>
                <div id="form-dir">    
                    <label>Altura(m):</label>
                    <input type="text"  name="altura" placeholder="Altura"/><br />
                </div>
            </div>
            <div id="direita-entrevista">
                <div id="form-dir">    
                    <label>Número de Panos:</label>
                    <input type="text"  name="numPanos" placeholder="Panos"/><br />
                </div>
                <div id="form-dir">    
                    <label>Malha:</label>
                    <input type="text"  name="malha" placeholder="Malha"/><br />
                </div>
            </div><br/>
            <br/>
            <div id="esquerda">
                <legend><h4>Outros dados:</h4></legend>
                <div id="form-esq">    
                    <label>Avistou:</label>
                    <input type="text" name="avistamento" placeholder="Avistamento"/><br />
                </div>
                <div id="form-esq">
                    <label for="tipo">Subamostra?:</label>
                    <input type="checkbox" name="subamostra" /><br />
                </div>
                <div id="form-esq">
                    <label for="tipo">Observacao:</label>
                    <input type="text" name="observacao" placeholder="Observacao" /><br />
                </div>

                <div id="Submit">
                    <input type="submit" value="Salvar Entrevista"/>
                </div>
            </div>

        </fieldset>
    </form>        
</div>
<form id="formulario" action="<?= $this->url(array("controller" => "ficha-diaria", "action" => "atualizar"), null, true) ?>" method="post">
<fieldset class="noEditable"><legend>Pesqueiro:</legend>
    <fieldset class="noEditable"><legend>Pesqueiro e tempo no pesqueiro:</legend>
            <div id="base">
                <input onclick="jsInsertPesqueiroWithoutTime(this.form, '<?= $this->url(array("controller" => "emalhe", "action" => "insertpesqueiro"), null, true) ?>', '<?=$this->entrevista['em_id']?>')" type="button" value="Add row" />
                <select style="float:left;" name="nomePesqueiro">
                    <?php foreach ($this->pesqueiros as $key => $pesqueiro): ?>
                        <option value="<?= $pesqueiro['paf_id']; ?>"><?= $pesqueiro['paf_pesqueiro']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

        </fieldset>
        <br>
        <fieldset class="noEditable" id="itemArteTipoRows"><legend>Pesqueiros:</legend>
            <table id="pesqueiros">
                <tr>
                    <th width="5%">Id Entrevista</th>
                    <th width="50%">Pesqueiro</th>
                </tr>
                <?php
                foreach ($this->vEmalhe as $key => $vEmalhe):
                    ?>
                    <tr id="itemArrastoRows">
                        <td name="inputIdEntrevista"> <?= $vEmalhe['em_id'] ?> </td>
                        <td name="inputPesqueiro"> <?= $vEmalhe['paf_pesqueiro'] ?> </td>
                        <td><input type="button" class="button-del" width="5%" onclick="jsDeletePesqueiro(<?= $this->entrevista['em_id'] ?>, '<?= $this->url(array("controller" => "emalhe", "action" => "deletepesqueiro"), null, true) ?>', <?= $vEmalhe['em_paf_id'] ?>)"></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </fieldset>
    </fieldset>
<fieldset class="noEditable"><legend>Espécies Capturadas:</legend>
        <fieldset class="noEditable"><legend>Dados das Espécies Capturadas:</legend>

            <div id="base">
                <input onclick="jsInsertEspecieCapturada(this.form, '<?= $this->url(array("controller" => "emalhe", "action" => "insertespeciecapturada"), null, true) ?>','<?=$this->entrevista['em_id']?>')" type="button" value="Add row" />
                <select style="float:left;" name="SelectEspecie">
                    <?php foreach ($this->especies as $key => $especie): ?>
                        <option value="<?= $especie['esp_id']; ?>"><?= $especie['esp_nome_comum']; ?></option>
                    <?php endforeach; ?>
                </select>
                <input style="float:left;" type="text" name="quantidade" placeholder="Quantidade" size="10px">
                <input style="float:left;" type="text" name="peso" placeholder="Peso" size="10px">
                <input style="float:left;" type="text" name="precokg" placeholder="Preço" size="10px">

                <input type="hidden" name="id_entrevista"  value="<?= $this->entrevista['em_id'] ?>"/>

            </div>

        </fieldset>
        <br>
         <fieldset class="noEditable" id="itemArteTipoRows"><legend>Espécies Capturadas:</legend>
                <table id="especiesCapturadas">
                    <tr>
                        <th width="20%">Id Entrevista</th>
                        <th width="30%">Espécie Capturada</th>
                        <th width="20%">Quantidade</th>
                        <th width="20%">Peso (kg)</th>
                        <th width="20%">Preço por kg</th>
                    </tr>
                    <?php
                    foreach ($this->vEspecieCapturadas as $key => $vEspecieCapturada):
                        ?>
                        <tr id="itemEmbarcacoesRows">
                            <td name="inputEntrevista"> <?= $vEspecieCapturada['em_id'] ?> </td>
                            <td name="inputEspecie" > <?= $vEspecieCapturada['esp_nome_comum'] ?> </td>
                            <td name="inputQuantidade"> <?= $vEspecieCapturada['spc_quantidade'] ?> </td>
                            <td name="inputPeso"> <?= $vEspecieCapturada['spc_peso_kg'] ?> </td>
                            <td name="inputPreco"> <?= $vEspecieCapturada['spc_preco'] ?> </td>
                            <td><input type="button" class="button-del" width="5%" onclick="jsDeletePesqueiro(<?= $this->entrevista['em_id'] ?>, '<?= $this->url(array("controller" => "emalhe", "action" => "deletespecie"), null, true) ?>', <?= $vEspecieCapturada['spc_em_id'] ?>)"></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </fieldset>
    </fieldset>
    </form>
    <br/> <br/>
    <a href="<?= $this->url(array("controller" => "ficha-diaria", "action" => "editar","id" => $this->monitoramento['fd_id']), null, true) ?>" id="botao-ancora">Voltar à Ficha-Diária</a>
    
</div>     
