<div id="titulos">
    <h2>Desembarque->Pesca de Emalhe</h2>
    <h3>Entrevista</h3>
</div>

<div id="esquerda-entrevista">
    <form action="<?= $this->url(array("controller" => "emalhe", "action" => "criar"), null, true) ?>">
        <fieldset id="Desembarque">
            <div id="esquerda">
                <div id="form-esq">
                    <label>ID da ficha diária:</label>
                    <input type="text" name="id_fichaDiaria" placeholder="ID" disabled="true" value="<?= $this->fichaDiaria['fd_id'] ?>" /><br />
                </div>
                <div id="form-esq">
                    <label>ID Monitoramento:</label>
                    <input type="text" name="id_monitoramento" placeholder="ID"  value="<?= $this->monitoramento['mnt_id'] ?>" /><br />
                </div>
                <div id="form-esq">
                    <label for="tipo">ID Entrevista:</label>
                    <input type="text" placeholder = "ID" name="id_entrevista" disabled="true"/><br />
                </div>
            </div>
            <br/>
            <div id="esquerda">
                <legend><h4>Embarcação:</h4></legend>
                <div id="form-esq">
                    <label>Utilizou Barco?</label>
                    <input type="checkbox"  name="embarcada" checked="true"/><br />
                </div>
                <div id="form-esq">
                    <label>Barco:</label>
                    <select name="nomeBarco" placeholder="Nome do Barco" />
                    <?php
                    foreach ($this->barcos as $key => $barco):
                        ?>
                        <option value="<?= $barco['bar_id'] ?>"><?= $barco['bar_nome'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                    <br />
                </div>
                <div id="form-esq">
                    <label>Tipo de Barco:</label>
                    <select name="tipoBarco" />
                    <?php
                    foreach ($this->tipoEmbarcacoes as $key => $tipoEmbarcacao):
                        ?>
                        <option value="<?= $tipoEmbarcacao['tte_id'] ?>"><?= $tipoEmbarcacao['tte_tipoembarcacao'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                    <br />
                </div>

            </div>
            <div id="direita-entrevista">
                <div id="form-esq">    
                    <label>Pescador Entrevistado:</label>
                    <select name="pescadorEntrevistado" />
                    <?php
                    foreach ($this->pescadores as $key => $pescador):
                        ?>
                        <option value="<?= $pescador['tp_id'] ?>"><?= $pescador['tp_nome'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                    <br />
                </div>
                <div id="form-esq">
                    <label>Qtd de Pescadores:</label>
                    <input type="number" name="numPescadores" placeholder="QuantidadePescadores"/><br />
                </div>
            </div>
            <div id="esquerda">
                <legend><h4>Lançamento e Recolhimento:</h4></legend>
                <div id="form-esq">
                    <label>Data:</label>
                    <input type="date" name="dataLancamento" placeholder="Lançamento"/>
                </div>
                <div id="form-esq">
                    <label>Hora:</label>
                    <input type="time" name="horaLancamento" placeholder="Lançamento"/>
                </div>
            </div>
            <div id="direita-entrevista">
                <div id="form-esq">
                    <label>Data:</label>
                    <input type="date" name="dataRecolhimento" placeholder="Recolhimento"/>
                </div>
                <div id="form-esq">
                    <label>Hora:</label>
                    <input type="time" name="horaRecolhimento" placeholder="Recolhimento"/>
                </div>
            </div>
            <div id="esquerda">
                <div id="form-esq">
                    <legend><h4>Gastos:</h4></legend>
                    <label>Diesel(L):</label>
                    <input type="text"  name="diesel" placeholder="Diesel"/>
                </div>
                <div id="form-dir">    
                    <label>Óleo(L):</label>
                    <input type="text"  name="oleo" placeholder="Óleo"/><br />
                </div>
            </div>
            <div id="direita-entrevista">
                <div id="form-dir">    
                    <label>Alimento($):</label>
                    <input type="text"  name="alimento" placeholder="Alimento"/><br />
                </div>
                <div id="form-dir">    
                    <label>Gelo($):</label>
                    <input type="text"  name="gelo" placeholder="Gelo"/><br />
                </div>
            </div>
            <div id="esquerda">
                <div id="form-esq">
                    <legend><h4>Esforço:</h4></legend>
                    <label>Tamanho(m):</label>
                    <input type="text"  name="tamanho" placeholder="Tamanho"/>
                </div>
                <div id="form-dir">    
                    <label>Altura(m):</label>
                    <input type="text"  name="altura" placeholder="Altura"/><br />
                </div>
            </div>
            <div id="direita-entrevista">
                <div id="form-dir">    
                    <label>Número de Panos:</label>
                    <input type="text"  name="numPanos" placeholder="Panos"/><br />
                </div>
                <div id="form-dir">    
                    <label>Malha:</label>
                    <input type="text"  name="malha" placeholder="Malha"/><br />
                </div>
            </div><br/>
            <br/>
            <div id="esquerda">
                <legend><h4>Outros dados:</h4></legend>
                <div id="form-esq">    
                    <label>Avistou:</label>
                    <input type="text" name="avistamento" placeholder="Avistamento"/><br />
                </div>
                <div id="form-esq">
                    <label for="tipo">Subamostra?:</label>
                    <input type="checkbox" name="subamostra" /><br />
                </div>
                <div id="form-esq">
                    <label for="tipo">Observacao:</label>
                    <input type="text" name="observacao" placeholder="Observacao" /><br />
                </div>

                <div id="Submit">
                    <input type="submit" value="Salvar Entrevista"/>
                </div>
            </div>

        </fieldset>
    </form>        
</div>      
