<h2>Lista de Especies</h2>

<a href="<?=$this->url(array("controller"=>"especie","action"=>"novo"),null,true)?>" id="botao-ancora">Novo</a>

<table>
    <tr>
        <th>Especie</th>
    </tr>
    
    <?php
    foreach ($this->dados as $key => $especie):
    ?>
    <tr>
        <td><?= $especie['TEC_Especie'] ?></td>
        <td>
            <a href="<?=$this->url(array("controller"=>"especie","action"=>"editar", "id" => $especie['TEC_ID']),null,true)?>">
                <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                </ul>
            </a>
        </td>
        <td>
            <a href="<?=$this->url(array("controller"=>"especie","action"=>"excluir", "id" => $especie['TEC_ID']),null,true)?>">
                <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-trash"></span></li>
                </ul>
            </a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>