<h2>Filogenia->Espécie</h2>
<h3>Novo</h3>

<a href="<?=$this->url(array("controller"=>"especie","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>

<form id="cadastro-usuario" action="<?=$this->url(array("controller"=>"especie","action"=>"criar"),null,true)?>" method="post">
    <fieldset id="Filogenia">
         <div id="form-esq">     
            <label for="id" >ID:</label><br/>
            <input type="text" name="id_especie" id="id_especie" placeholder="Id"/><br />
         </div>
         <div id="form-esq">   
            <label for="tipo">Nome:</label><br/>
            <input type="text" id="nome_especie" name="nome_especie" placeholder="Nome"/><br />
         </div>  
         <div id="form-esq">   
            <label for="tipo">Descritor:</label><br/>
            <input type="text" id="descritor_especie" name="descritor_especie" placeholder="Descritor"/><br />
         </div>   
         <div id="form-esq">   
            <label for="tipo">Nome Comum:</label><br/>
            <input type="text" id="nome_comum" name="nome_comum" placeholder="Nome Comum"/><br />
         </div>
         <div id="form-esq">   
            <label for="tipo">Gênero:</label><br/>
              <select name="select_genero_especie" id="genero_especie">
              <?php
                    foreach ($this->dados as $key => $genero):
               ?>
              
		<option nome="genero_especie" value="<?=$genero['GEN_ID']?>"><?= $genero['GEN_Nome']?></option>
              
              <?php
                endforeach;
              ?>
              </select></br>
          </div>  
        <div id="Submit">
            <input type="submit" value="Cadastrar" />
        </div>
    </fieldset>
</form>