<div id="titulos">
    <h2>Relatórios->EXCEL</h2>
</div>
<form action="<?= $this->url(array("controller" => "relatorios", "action" => "gerar"), null, true) ?>">
 <div class="esquerda">
     <div class="form-esq">
         <label>Relatório:</label>
    <select name="artePesca" required>
            <option value="" selected></option>
            <option value="1">Arrasto de Fundo</option>
            <option value="2">Calão</option>
            <option value="3">Coleta Manual</option>
            <option value="4">Emalhe</option>
            <option value="5">Groseira</option>
            <option value="6">Jereré</option>
            <option value="7">Pesca Linha</option>
            <option value="8">Linha de Fundo</option>
            <option value="9">Manzuá</option>
            <option value="10">Mergulho</option>
            <option value="11">Ratoeira</option>
            <option value="12">Siripoia</option>
            <option value="13">Tarrafa</option>
            <option value="14">Vara de Pesca</option>
            <option value="15">Entrevistas (completo)</option>
            <option value="16">Monitoramentos</option>
            <option value="17">Espécies Capturadas</option>
            <option value="18">Espécies Capturadas(Mês)</option>
            <option value="19">Pescadores</option>       
            <option value="20">Pescadores Especialistas</option>
            <option value="21">Avistamentos</option>
    </select>
     </div>
     <div class="form-esq">
         <label>Tipo de Saída:</label>
            <select name="tipoRelatorio">
                    <option value="0" selected>Padrão</option>
                    <option value="1">Peso</option>
                    <option value="2">Quantidade</option>
                    <option value="3">Preço</option>
            </select>
     </div>
     <div class="form-esq">
         <label>Por Data até:</label>
         <input type="date" name="dataRelatorio"/>
     </div>

     
    <div class="form-esq">     
        <input type="submit" value="Relatório"/>
    </div>
 </div>