<!DOCTYPE html>
<head>
        
        <?php
        $this->headLink()->prependStylesheet('../css/basic.css');


        echo $this->headLink() . "\n";
        echo $this->headScript() . "\n";
        ?>
	<script type="text/javascript" src="http://filamentgroup.github.com/EnhanceJS/enhance.js"></script>
        <script type="text/javascript">
		// Run capabilities test
		enhance({
			loadScripts: [
				{src: 'js/excanvas.js', iecondition: 'all'},
				'js/jquery.js',
				'js/visualize.jQuery.js',
				'js/example.js'
			],
			loadStyles: [
				'css/visualize.css',
				'css/visualize-light.css'
			]	
		});   
        </script>
        
</head>
<div id="titulos">
    <h2>Relatórios->Monitoramentos</h2>
</div>


<table >

	<thead>
		<tr>
                    <td scope="col">Monitorado?</td>
                    <th scope="col">Pescadores</th>
		</tr>
	</thead>
	<tbody>
            <?php foreach ($this->monitoramentos as $key => $monitoramento): ?>
		<tr>
			<th scope="row"><?= $monitoramento['consulta']?></th>
			<td><?= $monitoramento['quantidade']?></td>
		</tr>
            <?php endforeach;?>
	</tbody>
</table>