<h2>Perfil Social->Comunidade</h2>
<h3>Editar</h3>

<a href="<?=$this->url(array("controller"=>"comunidade","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>

<form action="<?=$this->url(array("controller"=>"comunidade","action"=>"atualizar"),null,true)?>" method="post">
    <fieldset id="Social">
        <div id="esquerda">
            <input type="hidden" name="idComunidade" value="<?=$this->comunidade['TCOM_ID']?>" />
            <div id="form-esq">
                <label>Comunidade:</label>
                <input type="text" name="nome_comunidade" placeholder="Comunidade" value="<?=$this->comunidade['TCOM_NOME']?>"/> <br/>
            </div>
            <div id="Submit">
                <input type="submit" value="Atualizar" />
            </div>
        </div>
    </fieldset>
</form>