<h2>Perfil Social->Renda</h2>

<a href="<?=$this->url(array("controller"=>"Renda","action"=>"novo"),null,true)?>" id="botao-ancora">Novo</a>
<fieldset id="Social"></fieldset>
<table>
    <tr>
      <th>ID</th>
      <th>Renda</th>
    </tr>
    
    <?php foreach ($this->rendas as $key => $renda): ?>
    <tr>
        <td><?= $renda['ren_id'] ?></td>
        <td><?= $renda['ren_renda'] ?></td>
        
        <td class="td-botao">
            <a href="<?=$this->url(array("controller"=>"renda","action"=>"editar", "id" => $renda['ren_id']),null,true)?>">
                <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                </ul>
            </a>
        </td>
        
        <td class="td-botao">
            <a href="<?=$this->url(array("controller"=>"renda","action"=>"excluir", "id" => $renda['ren_id']),null,true)?>">
                <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-trash"></span></li>
                </ul>
            </a>
        </td>
        
    </tr>
    <?php endforeach; ?>
</table>
<br/><br/>
<a href="<?=$this->url(array("controller"=>"Renda","action"=>"relatorio"),null,true)?>" id="botao-ancora" target="_blank">Gerar Relatório</a>