<br /><br />
<div id="view-content">
	<p>View script for controller <b>Renda</b> and script/action name <b>novo</b></p>
</div>


<div id="Renda">
    <h2>Social->Renda</h2>
    <h3>Novo</h3>
</div>

<form action="<?=$this->url(array("controller"=>"Renda","action"=>"criar"),null,true)?>" method="post">
   <input type="hidden" name="idRenda" placeholder="ID" />
   <fieldset id="Renda">
      <div id="esquerda">
      
        <div id="form-esq"> 
            <label>Renda: </label>
            <input type="text" name="renRenda" placeholder="Renda"/> <br />
        </div>

          <div id="Submit">
            <a href="<?=$this->url(array("controller"=>"Renda","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>
            <input type="submit" value="Cadastrar" />
        </div>
      </div>   
    </fieldset>
</form>