<h1>Editar Usuário</h1>

<form action="<?=$this->url(array("controller"=>"usuarios","action"=>"atualizar"),null,true)?>" method="post">
    <input type="hidden" name="idUsuario" value="<?=$this->usuario['idUsuario']?>" />
    <input type="hidden" name="idEndereco" value="<?=$this->usuario['idEndereco']?>" />
    <label>Nome: <input type="text" name="nome" value="<?=$this->usuario['nome'];?>" /></label> <br />
    <label>Login: <input type="text" name="login" disabled="disabled" value="<?=$this->usuario['login'];?>" /></label> <br />
    <label>Perfil: 
        <select name="perfil">
            <?php foreach ($this->perfis as $key => $perfil): ?>
            <option value="<?= $perfil['idPerfil']; ?>" <?=($perfil['idPerfil'] == $this->usuario['idPerfil'] ) ? 'selected="selected"' : '';?>><?= $perfil['perfil']; ?></option>
            <?php endforeach; ?>
        </select>
    </label> <br />    
    <label>Sexo: 
        <select name="sexo">
            <option value="M" <?=($this->usuario['sexo'] == 'M') ? 'selected="selected"' : '';?>>Masculino</option>
            <option value="F" <?=($this->usuario['sexo'] == 'F') ? 'selected="selected"' : '';?>>Feminino</option>
        </select>
    </label> <br /> 
    <label>E-mail: <input type="text" name="email" value="<?=$this->usuario['email'];?>" /></label> <br />
    <label>RG: <input type="text" name="rg" value="<?=$this->usuario['rg'];?>" /></label> <br />
    <label>CPF: <input type="text" name="cpf" value="<?=$this->usuario['cpf'];?>" /></label> <br />
    <label>Telefone: <input type="text" name="telefone" value="<?=$this->usuario['telefone'];?>" /></label> <br />
    <label>Logradouro: <input type="text" name="logradouro" value="<?=$this->usuario['logradouro'];?>" /></label> <br />
    <label>Número: <input type="text" name="numero" value="<?=$this->usuario['numero'];?>" /></label> <br />
    <label>Bairro: <input type="text" name="bairro" value="<?=$this->usuario['bairro'];?>" /></label> <br />
    <label>Cidade: <input type="text" name="cidade" value="<?=$this->usuario['cidade'];?>" /></label> <br />
    <label>Estado: 
        <select name="estado">
            <?php foreach ($this->estados as $estado): ?>
            <option value="<?= $estado; ?>" <?=($estado == $this->usuario['estado']) ? 'selected="selected"' : '';?>><?= $estado; ?></option>
            <?php endforeach; ?>
        </select>
    </label> <br />
    <label>CEP: <input type="text" name="cep" value="<?=$this->usuario['cep'];?>" /></label> <br />
    <label>Complemento: <input type="text" name="complemento" value="<?=$this->usuario['complemento'];?>" /></label> <br />
    <input type="submit" value="Atualizar" />
</form>