<?php
$this->headLink()->appendStylesheet('/css/forms-nr-min.css');
$this->headScript()->appendFile('/js/jquery.maskedinput.min.js');
$this->headScript()->appendFile('/js/mascaras.js');
?>

<h2>Editar Usuário</h2>

<a href="<?=$this->url(array("controller"=>"usuarios","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>

<form class="pure-form pure-form-aligned" id="cadastro-usuario" action="<?=$this->url(array("controller"=>"usuarios","action"=>"atualizar"),null,true)?>" method="post">
    <input type="hidden" name="idUsuario" value="<?=$this->usuario['TU_ID']?>" />
    <input type="hidden" name="idEndereco" value="<?=$this->usuario['TE_ID']?>" />
    
    <fieldset>
        <div id="esquerda">
            <div class="pure-control-group">
            <label for="nome">Nome</label>
            <input type="text" name="nome" id="nome" placeholder="Nome" value="<?=$this->usuario['TU_Nome'];?>"/>
        </div>
        
        <div class="pure-control-group">
            <label for="login-form">Login</label>
            <input type="text" name="login" id="login-form" placeholder="Login" value="<?=$this->usuario['TL_Login'];?>"/>
        </div>
        
        <div class="pure-control-group">
            <label for="perfil">Perfil</label>
            <select name="perfil" id="perfil">
                <?php foreach ($this->perfis as $key => $perfil): ?>
                <option value="<?= $perfil['TP_ID']; ?>" <?=($perfil['TP_ID'] == $this->usuario['TP_ID'] ) ? 'selected="selected"' : '';?>><?= $perfil['TP_Perfil']; ?></option>
                <?php endforeach; ?>
            </select>            
        </div>
        
        <div class="pure-control-group">
            <label for="sexo">Sexo</label>
            <select name="sexo" id="sexo">
                <option value="M" <?=($this->usuario['TU_Sexo'] == 'M') ? 'selected="selected"' : '';?>>Masculino</option>
                <option value="F" <?=($this->usuario['TU_Sexo'] == 'F') ? 'selected="selected"' : '';?>>Feminino</option>
            </select>            
        </div>
        
        <div class="pure-control-group">
            <label for="email">E-mail</label>
            <input type="text" name="email" id="email" placeholder="E-mail" value="<?=$this->usuario['TU_Email'];?>"/>
        </div>
        
        <div class="pure-control-group">
            <label for="rg">RG</label>
            <input type="text" name="rg" id="rg" placeholder="RG" value="<?=$this->usuario['TU_RG'];?>"/>
        </div>
        
        <div class="pure-control-group">
            <label for="cpf">CPF</label>
            <input type="text" name="cpf" id="cpf" placeholder="CPF" value="<?=$this->usuario['TU_CPF'];?>"/>
        </div>
        
        <div class="pure-control-group">
            <label for="telefoneResidencial">Tel. Residencial</label>
            <input type="text" name="telefoneResidencial" id="telefoneResidencial" class="telefone" placeholder="Tel. Residencial"/>
        </div>
        
        <div class="pure-control-group">
            <label for="telefoneCelular">Tel. Celular</label>
            <input type="text" name="telefoneCelular" id="telefoneCelular" class="telefone" placeholder="Tel. Celular"/>
        </div>
            
            <div class="pure-controls">
            <input type="submit" value="Atualizar" />
        </div>
        </div>
        
        <div id="direita">
            <div class="pure-control-group">
            <label for="logradouro">Logradouro</label>
            <input type="text" name="logradouro" id="logradouro" placeholder="Logradouro" value="<?=$this->usuario['TE_Logradouro'];?>"/>
        </div>
        
        <div class="pure-control-group">
            <label for="numero">Número</label>
            <input type="text" name="numero" id="numero" placeholder="Número" value="<?=$this->usuario['TE_Numero'];?>"/>
        </div>
        
        <div class="pure-control-group">
            <label for="bairro">Bairro</label>
            <input type="text" name="bairro" id="bairro" placeholder="Bairro" value="<?=$this->usuario['TE_Bairro'];?>"/>
        </div>
        
        <div class="pure-control-group">
            <label for="municipio">Município</label>
            <select name="municipio" id="municipio">
                <?php foreach ($this->municipios as $key => $municipio): ?>
                <option value="<?= $municipio['TMun_ID']; ?>"><?= $municipio['TMun_Municipio']; ?></option>
                <?php endforeach; ?>
            </select>            
        </div>
        
        <div class="pure-control-group">
            <label for="estado">Estado</label>
            <select name="estado" id="estado">
                <?php foreach ($this->estados as $estado): ?>
                <option value="<?= $estado; ?>" <?=($estado == "BA") ? 'selected="selected"' : '';?>><?= $estado; ?></option>
                <?php endforeach; ?>
            </select>            
        </div>
        
        <div class="pure-control-group">
            <label for="cep">CEP</label>
            <input type="text" name="cep" id="cep" placeholder="CEP" value="<?=$this->usuario['TE_CEP'];?>"/>
        </div>
        
        <div class="pure-control-group">
            <label for="complemento">Complemento</label>
            <input type="text" name="complemento" id="complemento" placeholder="Complemento" value="<?=$this->usuario['TE_Comp'];?>"/>
        </div>
        </div>
        
    </fieldset>
</form>