<h2>Lista de Usuários</h2>

<a href="<?=$this->url(array("controller"=>"usuarios","action"=>"novo"),null,true)?>">Novo</a>

<table>
    <tr>
        <th>Nome</th>
        <th>E-mail</th>
    </tr>
    
    <?php
    foreach ($this->dados as $key => $usuario):
    ?>
    <tr>
        <td><?= $usuario['TU_Nome'] ?></td>
        <td><?= $usuario['TU_Email'] ?></td>
        <td><a href="<?=$this->url(array("controller"=>"usuarios","action"=>"visualizar", "id" => $usuario['TU_ID']),null,true)?>">Visualizar</a></td>
        <td><a href="<?=$this->url(array("controller"=>"usuarios","action"=>"editar", "id" => $usuario['TU_ID']),null,true)?>">Editar</a></td>
        <td><a href="<?=$this->url(array("controller"=>"usuarios","action"=>"excluir", "id" => $usuario['TU_ID']),null,true)?>">Excluir</a></td>
    </tr>
    <?php endforeach; ?>
</table>