<h1>Novo Usuário</h1>

<form action="<?=$this->url(array("controller"=>"usuarios","action"=>"criar"),null,true)?>" method="post">
    <label>Nome: <input type="text" name="nome" /></label> <br />
    <label>Login: <input type="text" name="login" /></label> <br />
    <label>Perfil: 
        <select name="perfil">
            <?php foreach ($this->perfis as $key => $perfil): ?>
            <option value="<?= $perfil['idPerfil']; ?>"><?= $perfil['perfil']; ?></option>
            <?php endforeach; ?>
        </select>
    </label> <br />    
    <label>Sexo: 
        <select name="sexo">
            <option value="M">Masculino</option>
            <option value="F">Feminino</option>
        </select>
    </label> <br /> 
    <label>E-mail: <input type="text" name="email" /></label> <br />
    <label>RG: <input type="text" name="rg" /></label> <br />
    <label>CPF: <input type="text" name="cpf" /></label> <br />
    <label>Telefone: <input type="text" name="telefone" /></label> <br />
    <label>Logradouro: <input type="text" name="logradouro" /></label> <br />
    <label>Número: <input type="text" name="numero" /></label> <br />
    <label>Bairro: <input type="text" name="bairro" /></label> <br />
    <label>Cidade: <input type="text" name="cidade" /></label> <br />
    <label>Estado: 
        <select name="estado">
            <?php foreach ($this->estados as $estado): ?>
            <option value="<?= $estado; ?>" <?=($estado == "BA") ? 'selected="selected"' : '';?>><?= $estado; ?></option>
            <?php endforeach; ?>
        </select>
    </label> <br />
    <label>CEP: <input type="text" name="cep" /></label> <br />
    <label>Complemento: <input type="text" name="complemento" /></label> <br />
    <input type="submit" value="Cadastrar" />
</form>