<?php
$this->headScript()->appendFile('/js/jquery.maskedinput.min.js');
$this->headScript()->appendFile('/js/mascaras.js');
?>

<h2>Novo Usuário</h2>

<a href="<?=$this->url(array("controller"=>"usuarios","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>

<form action="<?=$this->url(array("controller"=>"usuarios","action"=>"criar"),null,true)?>" method="post">
    <label>Nome: <input type="text" name="nome" /></label> <br />
    <label>Login: <input type="text" name="login" /></label> <br />
    <label>Perfil: 
        <select name="perfil">
            <?php foreach ($this->perfis as $key => $perfil): ?>
            <option value="<?= $perfil['TP_ID']; ?>"><?= $perfil['TP_Perfil']; ?></option>
            <?php endforeach; ?>
        </select>
    </label> <br />    
    <label>Sexo: 
        <select name="sexo">
            <option value="M">Masculino</option>
            <option value="F">Feminino</option>
        </select>
    </label> <br /> 
    <label>E-mail: <input type="text" name="email" /></label> <br />
    <label>RG: <input type="text" name="rg" /></label> <br />
    <label>CPF: <input type="text" name="cpf" id="cpf"/></label> <br />
    <label>Telefone Residencial: <input type="text" name="telefoneResidencial" class="telefone"/></label> <br />
    <label>Telefone Celular: <input type="text" name="telefoneCelular" class="telefone"/></label> <br />
    <label>Logradouro: <input type="text" name="logradouro" /></label> <br />
    <label>Número: <input type="text" name="numero" /></label> <br />
    <label>Bairro: <input type="text" name="bairro" /></label> <br />
    <label>Municipio: 
        <select name="municipio">
            <?php foreach ($this->municipios as $key => $municipio): ?>
            <option value="<?= $municipio['TMun_ID']; ?>"><?= $municipio['TMun_Municipio']; ?></option>
            <?php endforeach; ?>
        </select>
    </label> <br />  
    <label>Estado: 
        <select name="estado">
            <?php foreach ($this->estados as $estado): ?>
            <option value="<?= $estado; ?>" <?=($estado == "BA") ? 'selected="selected"' : '';?>><?= $estado; ?></option>
            <?php endforeach; ?>
        </select>
    </label> <br />
    <label>CEP: <input type="text" name="cep" id="cep"/></label> <br />
    <label>Complemento: <input type="text" name="complemento" /></label> <br />
    <input type="submit" value="Cadastrar" />
</form>