<h2>Visualizar Usuário</h2>

<a href="<?=$this->url(array("controller"=>"usuarios","action"=>"index"),null,true)?>">Voltar</a>

<table>
    <tr>
        <th>Nome</th>
        <th>Login</th>
        <th>Perfil</th>
        <th>E-mail</th>
        <th>Sexo</th>
        <th>RG</th>
        <th>CPF</th>
        <th>Telefone</th>
        <th>Logradouro</th>
        <th>Número</th>
        <th>Bairro</th>
        <th>Cidade</th>
        <th>Estado</th>
        <th>CEP</th>
        <th>Complemento</th>     
    </tr>
    <tr>
        <td><?= $this->usuario['TU_Nome'] ?></td>
        <td><?= $this->usuario['TL_Login'] ?></td>
        <td><?= $this->usuario['TP_Perfil'] ?></td>
        <td><?= $this->usuario['TU_Email'] ?></td>
        <td><?= $this->usuario['TU_Sexo'] ?></td>
        <td><?= $this->usuario['TU_RG'] ?></td>
        <td><?= $this->usuario['TU_CPF'] ?></td>
        <td><?= $this->usuario['TU_Telefone'] ?></td>
        <td><?= $this->usuario['TE_Logradouro'] ?></td>
        <td><?= $this->usuario['TE_Numero'] ?></td>
        <td><?= $this->usuario['TE_Bairro'] ?></td>
        <td><?= $this->usuario['TE_Cidade'] ?></td>
        <td><?= $this->usuario['TE_Estado'] ?></td>
        <td><?= $this->usuario['TE_CEP'] ?></td>
        <td><?= $this->usuario['TE_Complemento'] ?></td>
    </tr>
</table>