<div id="titulos">
    <h2>Desembarque->Arrasto de Fundo</h2>
    <h3>Entrevista</h3>
</div>

<div id="esquerda-entrevista">
    <form>
        <fieldset id="Desembarque">
            <div id="esquerda">
                <div id="form-esq">
                    <label>ID da ficha diária:</label>
                    <input type="text" name="id_fichaDiaria" placeholder="ID" id="id_fichaDiaria" /><br />
                </div>
                <div id="form-esq">
                    <label for="tipo">ID Entrevista:</label>
                    <input type="text" id="id_entrevista" placeholder = "ID" name="id_entrevista"/><br />
                </div>
            </div>
            <br/>
            <div id="esquerda">
                <legend><h4>Embarcação:</h4></legend>
                <div id="form-esq">
                    <label>Utilizou Barco?</label>
                    <input type="checkbox" id="nome" name="barco" checked="true"/><br />
                </div>
                <div id="form-esq">
                    <label>Barco:</label>
                    <select name="nomeBarco" placeholder="Nome do Barco" />
                    <?php
                    foreach ($this->barcos as $key => $barco):
                        ?>
                        <option value="<?= $barco['bar_id'] ?>"><?= $barco['bar_nome'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                    <br />
                </div>
                <div id="form-esq">
                    <label>Tipo de Barco:</label>
                    <select name="tipoBarco" />
                    <?php
                    foreach ($this->tipoEmbarcacoes as $key => $tipoEmbarcacao):
                        ?>
                        <option value="<?= $tipoEmbarcacao['tte_id'] ?>"><?= $tipoEmbarcacao['tte_tipoembarcacao'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                    <br />
                </div>

            </div>
            <div id="direita-entrevista">
                <div id="form-esq">    
                    <label>Pescador Entrevistado:</label>
                    <select name="PescadorEntrevistado" />
                    <?php
                    foreach ($this->pescadores as $key => $pescador):
                        ?>
                        <option value="<?= $pescador['tp_id'] ?>"><?= $pescador['tp_nome'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                    <br />
                </div>
                <div id="form-esq">
                    <label>Qtd de Pescadores:</label>
                    <input type="number" name="num_pescadores" placeholder="QuantidadePescadores"/><br />
                </div>
            </div>
            <div id="esquerda">
                <legend><h4>Saída e Volta:</h4></legend>
                <div id="form-esq">

                    <label>Data:</label>
                    <input type="date" name="num_pescadores" placeholder="Data da Saída"/>
                </div>
                <div id="form-esq">
                    <label>Horas:</label>
                    <input type="time" name="num_pescadores" placeholder="Hora da Saída"/>
                </div>
            </div>
            <div id="direita-entrevista">
                <div id="form-esq">
                    <label>Data:</label>
                    <input type="date" name="num_pescadores" placeholder="Data da Volta"/>
                </div>
                <div id="form-esq">
                    <label>Horas:</label>
                    <input type="time" name="num_pescadores" placeholder="Hora da Volta"/>
                </div>
            </div>
            <div id="esquerda">
                <div id="form-esq">
                    <legend><h4>Gastos:</h4></legend>
                    <label>Diesel(L):</label>
                    <input type="text"  name="num_pescadores" placeholder="Diesel"/>
                </div>
                <div id="form-dir">    
                    <label>Óleo(L):</label>
                    <input type="text"  name="num_pescadores" placeholder="Óleo"/><br />
                </div>
            </div>
            <div id="direita-entrevista">
                <div id="form-dir">    
                    <label>Alimento($):</label>
                    <input type="text"  name="num_pescadores" placeholder="Alimento"/><br />
                </div>
                <div id="form-dir">    
                    <label>Gelo($):</label>
                    <input type="text"  name="num_pescadores" placeholder="Gelo"/><br />
                </div>
            </div>
            <br/>
            <div id="esquerda">
                <legend><h4>Outros dados:</h4></legend>
                <div id="form-esq">    
                    <label>Avistou:</label>
                    <input type="text" name="num_pescadores" placeholder="Num"/><br />
                </div>
                <div id="form-esq">
                    <label for="tipo">Subamostra?:</label>
                    <input type="checkbox" id="subamostra" name="subamostra" /><br />
                </div>
                <div id="form-esq">
                    <label for="tipo">Observacao:</label>
                    <input type="text" id="obs" name="subamostra" placeholder="Observacao" /><br />
                </div>
                <div id="Submit">
                    <input type="submit" value="Salvar Entrevista"/>
                </div>
            </div>

        </fieldset>
        <fieldset class="noEditable"><legend>Pesqueiro:</legend>
            <fieldset class="noEditable"><legend>Pesqueiro e tempo no pesqueiro:</legend>

                <div id="base">

                    <input onclick="jsInsertMonitoramento(this.form, '<?= $this->url(array("controller" => "ficha-diaria", "action" => "insertmonitoramento"), null, true) ?>')" type="button" value="Add row" />
                    <select name="SelectArtePesca">
                        <?php foreach ($this->artesPesca as $key => $artePesca): ?>
                            <option value="<?= $artePesca['tap_id']; ?>"><?= $artePesca['tap_artepesca']; ?></option>
                        <?php endforeach; ?>
                    </select>
                    <input type="time" name="tempoPesqueiro" placeholder="Tempo no pesqueiro" size="10px">

                    <input type="hidden" name="id_entrevista"  value="<?= a//$this->fichadiaria['fd_id'] ?>"/>
                    
                </div>

            </fieldset>
            <br>
            <fieldset class="noEditable" id="itemArteTipoRows"><legend>Monitoramentos:</legend>
                <table id="especiesCapturadas">
                    <tr>
                        <th width="5%">Id Entrevista</th>
                        <th width="30%">Pesqueiro</th>
                        <th width="20%">Arte de Pesca</th>
                        <th width="30%">Quantidade</th>
                        <th width="5%">Id_Ficha</th>
                    </tr>
                    <?php
                    foreach ($this->vMonitoramento as $key => $vMonitoramento):
                        if ($vMonitoramento['mnt_monitorado'] == 1) {
                            $vMonitoramento['mnt_monitorado'] = "Sim";
                        } else {
                            $vMonitoramento['mnt_monitorado'] = "Não";
                        }
                        ?>
                        <tr id="itemEmbarcacoesRows<?= $key ?>">
                            <td name="inputIdMonitoramento"> <?= $vMonitoramento['mnt_id'] ?> </td>
                            <td name="inputMonitorada" > <?= $vMonitoramento['mnt_monitorado'] ?> </td>
                            <td name="inputArtedePesca"> <?= $vMonitoramento['tap_artepesca'] ?> </td>
                            <td name="inputQuantidade" > <?= $vMonitoramento['mnt_quantidade'] ?> </td>
                            <td name="inputIdFicha"> <?= $vMonitoramento['fd_id'] ?> </td>
                            <td><input type="button" class="button-del" width="5%" onclick="jsDeleteMonitoramento(<?= $vMonitoramento['mnt_id'] ?>, this.form, '<?= $this->url(array("controller" => "ficha-diaria", "action" => "deletmonitoramento"), null, true) ?>', <?= $vMonitoramento['fd_id'] ?>)"></td>
                            <td><input type="button" width="10%" target="_blank" value ="Nova Entrevista" onclick="jsEntrevista('<?= $vMonitoramento['tap_artepesca'] ?>', <?= $vMonitoramento['mnt_id'] ?>, <?= $vMonitoramento['fd_id'] ?>)"></td>

                        </tr>
                    <?php endforeach; ?>
                </table>
            </fieldset>
        </fieldset>

    </form>        
</div>      


