<div id="titulos">
    <h2>Desembarque->Arrasto de Fundo</h2>
    <h3>Entrevista</h3>
</div>

<div id="esquerda">
    <form>
        <fieldset id="Desembarque">
            <div id="form-esq">
                <label>ID da ficha diária:</label>
                <input type="text" name="id_fichaDiaria" placeholder="ID" id="id_fichaDiaria" /><br />
            </div>
            <div id="form-esq">
                <label for="tipo">ID Entrevista:</label>
                <input type="text" id="id_entrevista" placeholder = "ID" name="id_entrevista"/><br />
            </div>
            <div id="direita">
		<legend><h4>Embarcação</h4></legend>
			<div id="form-esq">
                            <label>Barco:</label>
                            <input type="text" id="nome" name="barco" placeholder="Nome do Barco" /><br />
                        </div>
                        <div id="form-esq">
                            <label>Tipo de Barco:</label>
                            <input type="text" id="nome" name="tipo_barco" placeholder="Tipo de Barco"/><br />
                        </div>
                        <div id="form-esq">    
                            <label >Mestre:</label>
                            <input type="text" id="nome" name="mestre" placeholder="Nome do Mestre"/><br />
                        </div>
                        <div id="form-esq">
                            <label>Qtd de Pescadores:</label>
                            <input type="text" id="numeric" name="num_pescadores" placeholder="Num"/><br />
                        </div>
              </div>
        </fieldset>
    </form>