<fieldset id="Entrevista"></fieldset>
    <form name="arrasto-fundo" method="post">

        <h2>Perfil Social->Arrasto de Fundo (lista limitada em 20)</h2>

        <table>
            <tr>
                
                <td>
                    <input type="button" size="50" value="Listar todos" class="button-confirmText" onclick="jsClearBuscaEntrevista('<?= $this->url(array("controller" => "arrasto-fundo", "action" => "visualizar"), null, true) ?>')">
                </td>
            </tr>
            <tr>
                <td>
                    <input type="button" size="50" value="Busca por ID" class="button-confirmText" onclick="jsBuscaEntrevistaId(this.form, '<?= $this->url(array("controller" => "arrasto-fundo", "action" => "visualizar"), null, true) ?>')">
                    <input type="number" min="0" name="inputId" placeholder="Busca por ID" />
                </td>
                <td>
                    <input type="button" size="50" value="Busca por Pescador" class="button-confirmText" onclick="jsBuscaEntrevistaPescador(this.form, '<?= $this->url(array("controller" => "arrasto-fundo", "action" => "visualizar"), null, true) ?>')">
                    <input type="number" min="0" name="inputPescador" placeholder="Busca por ID" />
                </td>
                <td>
                </td>
            </tr>
        </table>


        
        <table>
            <tr>
                <th>ID</th>
                <th>Pescador</th>
                <th>Barco</th>
            </tr>

            <?php foreach ($this->dados as $key => $entrevista): ?>
                <tr>
                    <td><?= $entrevista['af_id'] ?></td>
                    <td><?= $entrevista['tp_id_entrevistado'] ?></td>
                    <td><?= $entrevista['bar_id'] ?></td>

                    <td class="td-botao">
                        <a href="<?= $this->url(array("controller" => "pescador", "action" => "visualizar", "id" => $pescador['tp_id']), null, true) ?>">
                            <ul id="icons" class="ui-widget ui-helper-clearfix">
                                <li class="ui-state-default ui-corner-all" title="Visualizar"><span class="ui-icon ui-icon-search"></span></li>
                            </ul>
                        </a>
                    </td>

                    <td class="td-botao">
                        <a href="<?= $this->url(array("controller" => "pescador", "action" => "editar", "id" => $pescador['tp_id']), null, true) ?>">
                            <ul id="icons" class="ui-widget ui-helper-clearfix">
                                <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                            </ul>
                        </a>
                    </td>

                    <td class="td-botao">
                        <input type="button" name="Excluir" class="button-del" onclick="beforeDelete('<?= $this->url(array("controller" => "pescador", "action" => "excluir", "id" => $pescador['tp_id']), null, true) ?>')">
                    </td>

                    </a>

                </tr>
            <?php endforeach; ?>
        </table>
        <br/><br/>
        <a href="<?= $this->url(array("controller" => "pescador", "action" => "relatorio"), null, true) ?>" id="botao-ancora" target="_blank">Gerar Relatório</a>
    </form>
</html>
