<h2>Desembarque--Maré</h2>

<a href="<?=$this->url(array("controller"=>"mare","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>
<form id="mare">
    <fieldset id="Desembarque">
	  <legend ><h3>Mare:</h3></legend>
	  <label for="id">ID:</label>
          <input type="text" name="id_mare" id="id_mare"/><br />
          <label for="tipo">Estado da Maré:</label>
          <input type="text" id="estado_mare" name="estado_mare"/><br />
	  <input type="submit" value="enviar"/>
    </fieldset>
</form>