<h2>Filogenia->Gênero</h2>
<h3>Editar</h3>
<a href="<?=$this->url(array("controller"=>"genero","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>

<form id="genero" action="<?=$this->url(array("controller"=>"genero","action"=>"atualizar"),null,true)?>">
      <fieldset id="Filogenia">
          <div id="form-esq">
              <label for="id">ID:</label><br/>
              <input type="text" name="id_genero" id="id_genero" value="<?=$this->genero["GEN_ID"]?>"/><br />
          </div>
         <div id="form-esq">    
              <label for="tipo">Nome:</label><br/>
              <input type="text" id="nome_genero" name="nome_genero" value="<?=$this->genero["GEN_Nome"]?>"/><br />
         </div>
         <div id="form-esq">    
              <label for="tipo">Família:</label><br/>
              <select name="select_familia_genero" id="familia_genero">
              <?php
                    foreach ($this->dados as $key => $familia):
               ?>
              
		<option nome="ordem_familia" value="<?=$familia['FAM_ID']?>"><?= $familia['FAM_Nome']?></option>
              
              <?php
                endforeach;
              ?>
                </select><br/>
         </div>
        <div id="Submit">       
              <input type="submit" value="Enviar"/>
        </div>      
      </fieldset>
</form>