<h2>Filogenia->Gênero</h2>

<a href="<?=$this->url(array("controller"=>"genero","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>

<form id="genero" action="<?=$this->url(array("controller"=>"genero","action"=>"atualizar"),null,true)?>">
      <fieldset id="Filogenia">
          <legend><h3>Gênero:</h3></legend>
              <label for="id">ID:</label>
              <input type="text" name="id_genero" id="id_genero" value="<?=$this->genero["GEN_ID"]?>"/><br />
              <label for="tipo">Nome:</label>
              <input type="text" id="nome_genero" name="nome_genero" value="<?=$this->genero["GEN_Nome"]?>"/><br />
              <label for="tipo">Família:</label>
              <select name="select_familia_genero" id="familia_genero">
              <?php
                    foreach ($this->dados as $key => $familia):
               ?>
              
		<option nome="ordem_familia" value="<?=$familia['FAM_ID']?>"><?= $familia['FAM_Nome']?></option>
              
              <?php
                endforeach;
              ?>
                </select><br/>
              <input type="submit" value="Enviar"/>
      </fieldset>
</form>