<h2>Filogenia--Gênero</h2>

<a href="<?=$this->url(array("controller"=>"genero","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>

<form>
    <fieldset id="Filogenia">
              <legend><h3>Gênero:</h3></legend>
              <label for="id">ID:</label>
              <input type="text" name="id_genero" id="id_genero"/><br />
              <label for="tipo">Nome:</label>
              <input type="text" id="nome_genero" name="nome_genero"/><br />
              <label for="tipo">Família:</label>
              <input type="text" id="familia_genero" name="familia_genero"/><br />
              <input type="submit" value="Enviar"/>
    </fieldset>
              
</form>
