-- -- Data base
-- createdb movedb --template=template0 --encoding="UTF8" --lc-collate="pt_BR.UTF-8" --lc-ctype='pt_BR.UTF-8'
-- 
-- 
-- 
-- --SQL
-- psql -d movedb
-- 
-- CREATE USER pesca WITH PASSWORD 'pesca';
-- 
-- GRANT ALL PRIVILEGES ON DATABASE "movedb" to pesca;
-- 
-- alter user pesca superuser;

-- PSQL -D MOVEDB -A -F IMPORTACAO_ACCESS_PG.SQL

DROP TABLE IF EXISTS ATIVIDADES;
DROP TABLE IF EXISTS COMUNIDADE;
DROP TABLE IF EXISTS CONTROLE_DE_DESEMBARQUE;
DROP TABLE IF EXISTS EMBARCACAO;
DROP TABLE IF EXISTS ENTREV_PESCA;
DROP TABLE IF EXISTS EQUIPE;
DROP TABLE IF EXISTS ESPECIES;
DROP TABLE IF EXISTS FAMILIAS;
DROP TABLE IF EXISTS FICHA_DIARIA;
DROP TABLE IF EXISTS FICHAS;
DROP TABLE IF EXISTS GENERO;
DROP TABLE IF EXISTS GRUPOS;
DROP TABLE IF EXISTS ISCA;
DROP TABLE IF EXISTS MUNICIPIO;
DROP TABLE IF EXISTS ORDEM;
DROP TABLE IF EXISTS PERMISSOES;
DROP TABLE IF EXISTS PESCADOR;
DROP TABLE IF EXISTS PESQUEIRO;
DROP TABLE IF EXISTS PORTODESEMB;
DROP TABLE IF EXISTS SP_CAP;
DROP TABLE IF EXISTS SUBPROJETO;
DROP TABLE IF EXISTS SWITCHBOARD_ITEMS;
DROP TABLE IF EXISTS TAREFAS;
DROP TABLE IF EXISTS USUARIOS;

-- ATIVIDADES
CREATE TABLE  ATIVIDADES  (
   CODIGO  INTEGER NOT NULL, 
   COD_TRF  INTEGER, 
   ATIVIDADES  VARCHAR(255), 
  PRIMARY KEY ( CODIGO )
);

-- COMUNIDADE
CREATE TABLE COMUNIDADE (
  CODIGO INTEGER NOT NULL, 
  COMUNIDADE VARCHAR(255), 
  UNIQUE (COMUNIDADE), 
  PRIMARY KEY (CODIGO)
);

CREATE TABLE CONTROLE_DE_DESEMBARQUE (
  CODIGO INTEGER NOT NULL, 
  DATA TIMESTAMP, 
  HORA TIMESTAMP, 
  PORTO INTEGER, 
  PERIODOI TIMESTAMP, 
  PERIODOF TIMESTAMP, 
  FAD INTEGER, 
  FE INTEGER, 
  FAP INTEGER, 
  FAC INTEGER, 
  MONITOR VARCHAR(255), 
  COORD_ESTAG VARCHAR(255), 
  PRESENCAMONITOR NUMERIC(1) DEFAULT 0, 
  MATERIAIS_OK NUMERIC(1) DEFAULT 0, 
  PROVIDENCIAR VARCHAR(255), 
  FICHASENTREGUES INTEGER, 
  OBS VARCHAR(255), 
  ANEXO BYTEA, 
  PRIMARY KEY (CODIGO)
);

CREATE TABLE EMBARCACAO (
  CODIGO INTEGER NOT NULL, 
  EMBARCACAO VARCHAR(255) NOT NULL, 
  UNIQUE (EMBARCACAO), 
  PRIMARY KEY (CODIGO)
);

CREATE TABLE ENTREV_PESCA (
  CODIGO INTEGER NOT NULL, 
  COD_FICHADIARIA INTEGER NOT NULL, 
  ARTE VARCHAR(255) NOT NULL, 
  COD_PDESEMB INTEGER, 
  DATA TIMESTAMP, 
  BARCO VARCHAR(255), 
  TP_BARCO VARCHAR(255), 
  MESTRE INTEGER, 
  N_PESC INTEGER, 
  DATASAIDA VARCHAR(255), 
  HORASAIDA TIMESTAMP, 
  DATACHEGADA VARCHAR(255), 
  HORACHEGADA TIMESTAMP, 
  SUBAMOSTRA NUMERIC(1) DEFAULT 0, 
  ID_SUBAMOSTRA VARCHAR(255), 
  DESTINO VARCHAR(255), 
  PESQUEIRO1 VARCHAR(255), 
  PESQUEIRO2 VARCHAR(255), 
  PESQUEIRO3 VARCHAR(255), 
  PESQUEIRO4 VARCHAR(255), 
  PESQUEIRO5 VARCHAR(255), 
  DUR_ARRASTO1 INTEGER, 
  DUR_ARRASTO2 INTEGER, 
  DUR_ARRASTO3 INTEGER, 
  DUR_ARRASTO4 INTEGER, 
  DUR_ARRASTO5 INTEGER, 
  TEMPOATEPESQ INTEGER, 
  COMBUSTIVEL DECIMAL(18,2), 
  TIPO_COMB VARCHAR(255), 
  ÓLEO DECIMAL(18,2), 
  ALIMENTOS DECIMAL(18,2), 
  GELO DECIMAL(18,2), 
  TP_PESCA VARCHAR(255), 
  N_LINHAS INTEGER, 
  N_ANZOIS INTEGER, 
  ISCA VARCHAR(255), 
  TP_REDE VARCHAR(255), 
  N_LANCES INTEGER, 
  N_PANOS INTEGER, 
  COMP_PANO DECIMAL(18,2), 
  ALT_PANO DECIMAL(18,1), 
  TAM_MALHA DECIMAL(18,1), 
  MARE VARCHAR(255), 
  TIPOMARISCAGEM VARCHAR(255), 
  N_ARMADILHAS INTEGER, 
  TEMPOMARISCANDO INTEGER, 
  DISTMARISCO DECIMAL(18,1), 
  AVIST VARCHAR(255), 
  OBS VARCHAR(255), 
  --INDEX (ID_SUBAMOSTRA), 
  PRIMARY KEY (CODIGO)
);

CREATE TABLE EQUIPE (
  CODIGO INTEGER NOT NULL, 
  COD_ATIV INTEGER, 
  NOME VARCHAR(255), 
  FUNCAO VARCHAR(255), 
  DTNASC TIMESTAMP, 
  CPF VARCHAR(255), 
  RG VARCHAR(255), 
  NOME_PAI VARCHAR(255), 
  NOME_MAE VARCHAR(255), 
  TEL VARCHAR(255), 
  CEL VARCHAR(255), 
  EMAIL VARCHAR(255), 
  OBS VARCHAR(255), 
  INATIVO NUMERIC(1) DEFAULT 0, 
  UNIQUE (NOME), 
  PRIMARY KEY (CODIGO)
);

CREATE TABLE ESPECIES (
  CODIGO INTEGER NOT NULL, 
  COD_GEN INTEGER, 
  ESPECIE VARCHAR(255) NOT NULL, 
  DESCRITOR VARCHAR(255), 
  NOME_VULGAR VARCHAR(255) NOT NULL, 
  --INDEX (CODIGO), 
  UNIQUE (ESPECIE), 
  PRIMARY KEY (CODIGO)
);

CREATE TABLE FAMILIAS (
  CODIGO INTEGER NOT NULL, 
  COD_ORDEM INTEGER, 
  FAMILIA VARCHAR(255) NOT NULL, 
  ORDEM_FILOG INTEGER, 
  TIPO VARCHAR(255), 
  CARACTERISTICAS VARCHAR(255), 
  UNIQUE (FAMILIA), 
  PRIMARY KEY (CODIGO), 
  UNIQUE (ORDEM_FILOG)
);

CREATE TABLE FICHA_DIARIA (
  COD_FICHA INTEGER NOT NULL, 
  PORTO_DE_DESEMBARQUE INTEGER NOT NULL, 
  DATA TIMESTAMP NOT NULL, 
  ESTAGIARIO VARCHAR(255) NOT NULL, 
  MONITOR VARCHAR(255) NOT NULL, 
  TURNO VARCHAR(255), 
  HORACH TIMESTAMP, 
  HORAS TIMESTAMP, 
  TEMPO VARCHAR(255), 
  VENTO VARCHAR(255), 
  N_BARCO INTEGER NOT NULL, 
  LINHAMAO INTEGER DEFAULT 0, 
  GROS INTEGER DEFAULT 0, 
  ARRFUNDO INTEGER DEFAULT 0, 
  RDEMA INTEGER DEFAULT 0, 
  LINHAMAONM INTEGER DEFAULT 0, 
  GROSNM INTEGER DEFAULT 0, 
  ARRFUNDONM INTEGER DEFAULT 0, 
  RDEMANM INTEGER DEFAULT 0, 
  VARA_DE_PESCA INTEGER DEFAULT 0, 
  MERGULHO INTEGER DEFAULT 0, 
  MANZUA INTEGER DEFAULT 0, 
  JERERE INTEGER DEFAULT 0, 
  Tres_MALHOS INTEGER DEFAULT 0, 
  CIRIPOIA INTEGER DEFAULT 0, 
  TARRAFA INTEGER DEFAULT 0, 
  RATOEIRA INTEGER DEFAULT 0, 
  OBS VARCHAR(255), 
  PRIMARY KEY (COD_FICHA)
);

CREATE TABLE FICHAS (
  CODIGO INTEGER NOT NULL, 
  DIARIA INTEGER, 
  REDE INTEGER, 
  LINHA INTEGER, 
  ARRASTO INTEGER, 
  MARISCAGEM INTEGER, 
  BIO_CAMARAO INTEGER, 
  BIO_PEIXES INTEGER, 
  PRIMARY KEY (CODIGO)
);

CREATE TABLE GENERO (
  CODIGO INTEGER NOT NULL, 
  COD_FAM INTEGER, 
  GENERO VARCHAR(255), 
  UNIQUE (GENERO), 
  PRIMARY KEY (CODIGO)
);

CREATE TABLE GRUPOS (
  COD INTEGER NOT NULL, 
  GRUPO VARCHAR(255), 
  UNIQUE (GRUPO), 
  PRIMARY KEY (COD)
);

CREATE TABLE ISCA (
  CODIGO INTEGER NOT NULL, 
  ISCA VARCHAR(255), 
  PRIMARY KEY (CODIGO)
);

CREATE TABLE MUNICIPIO (
  CODIGO INTEGER NOT NULL, 
  MUNICIPIO VARCHAR(255), 
  PRIMARY KEY (CODIGO)
);

CREATE TABLE ORDEM (
  CODIGO INTEGER NOT NULL, 
  COD_GRUPO INTEGER NOT NULL, 
  ORDEM VARCHAR(255) NOT NULL, 
  CARACTERISTICA VARCHAR(255), 
  UNIQUE (ORDEM), 
  PRIMARY KEY (CODIGO)
);

CREATE TABLE PERMISSOES (
  CODIGO INTEGER NOT NULL, 
  COD_USUARIO INTEGER, 
  FUNCAO VARCHAR(255), 
  NIVEL VARCHAR(1), 
  PRIMARY KEY (CODIGO)
);

CREATE TABLE PESCADOR (
  CODIGO INTEGER NOT NULL, 
  COD_PDESEMB INTEGER, 
  RESPONSAVEL_LANCAMENTO VARCHAR(255), 
  NOME VARCHAR(255) NOT NULL, 
  APELIDO VARCHAR(255), 
  SEXO VARCHAR(255), 
  RUA VARCHAR(255), 
  BAIRRO VARCHAR(255), 
  MUNICIPIO VARCHAR(255), 
  DT_NASC VARCHAR(255), 
  NATURALIDADE VARCHAR(255), 
  PAI VARCHAR(255), 
  MAE VARCHAR(255), 
  N_DEPENDENTES VARCHAR(255), 
  DEPENDENTE TEXT, 
  COLONIA VARCHAR(255), 
  COMUNIDADE VARCHAR(255), 
  MATRICULA VARCHAR(255), 
  ESPECIFICIDADE VARCHAR(255), 
  DATA_INSC VARCHAR(255), 
  RG VARCHAR(255), 
  CPF VARCHAR(255), 
  CTPS VARCHAR(255), 
  PIS VARCHAR(255), 
  INSS VARCHAR(255), 
  CEI VARCHAR(255), 
  RGP VARCHAR(255), 
  CIR VARCHAR(255), 
  ARTE_PESCA TEXT, 
  TIPO_EMBARC TEXT, 
  PROP_EMBARC NUMERIC(1) DEFAULT 0, 
  TAM_AMBARC VARCHAR(255), 
  MOTOR_EMBARC NUMERIC(1) DEFAULT 0, 
  AREA_PESCA TEXT, 
  SP_CAPT TEXT, 
  ESCOLARIDADE VARCHAR(255), 
  PROG_SOC VARCHAR(255), 
  RENDA VARCHAR(255), 
  OUTRA_RENDA NUMERIC(1) DEFAULT 0, 
  QUAL VARCHAR(255), 
  SITUACAO_ATUAL VARCHAR(255), 
  SITUACAO_ATUAL_INTERROGACAO VARCHAR(255), 
  TEL VARCHAR(255), 
  CEL VARCHAR(255), 
  RESPONSAVEL_TEL VARCHAR(255), 
  RESPONSAVEL_CADASTRAMENTO VARCHAR(255), 
  DATA_CADASTRO VARCHAR(255), 
  OBS VARCHAR(255), 
  --INDEX (COD_PDESEMB), 
  UNIQUE (NOME), 
  PRIMARY KEY (CODIGO)
);

CREATE TABLE PESQUEIRO (
  CODIGO INTEGER NOT NULL, 
  PESQUEIRO VARCHAR(255), 
  PRIMARY KEY (CODIGO)
);

CREATE TABLE PORTODESEMB (
  CODIGO INTEGER NOT NULL, 
  COD_MUNIC INTEGER, 
  PDESMB VARCHAR(255), 
  MONITOR VARCHAR(255), 
  PRIMARY KEY (CODIGO)
);

CREATE TABLE SP_CAP (
  CODIGO INTEGER NOT NULL, 
  COD_ENTREV INTEGER, 
  COD_SP INTEGER NOT NULL, 
  QUANTIDADE INTEGER, 
  PESO_KG DECIMAL(18,2), 
  VALOR_KG DECIMAL(18,2), 
  PRIMARY KEY (CODIGO) 
  --INDEX (COD_SP)
);

CREATE TABLE SUBPROJETO (
  CODIGO INTEGER NOT NULL, 
  COD_PROJ INTEGER NOT NULL, 
  SUBPROJETO VARCHAR(255) NOT NULL, 
  DESCRICAO TEXT, 
  OBS VARCHAR(255), 
  PRIMARY KEY (CODIGO), 
  UNIQUE (SUBPROJETO)
);

CREATE TABLE SWITCHBOARD_ITEMS (
  SWITCHBOARDID INTEGER NOT NULL, 
  ITEMNUMBER INTEGER NOT NULL DEFAULT 0, 
  ITEMTEXT VARCHAR(255), 
  COMMAND INTEGER, 
  ARGUMENT VARCHAR(255), 
  PRIMARY KEY (SWITCHBOARDID, ITEMNUMBER)
);

CREATE TABLE TAREFAS (
  CODIGO INTEGER NOT NULL, 
  COD_SUBP INTEGER NOT NULL, 
  TIPO VARCHAR(255), 
  TAREFAS VARCHAR(255), 
  UNIQUE (TAREFAS), 
  PRIMARY KEY (CODIGO)
);

CREATE TABLE USUARIOS (
  CODIGO INTEGER NOT NULL, 
  USUARIO VARCHAR(255), 
  NOME VARCHAR(255), 
  SENHA VARCHAR(255) NOT NULL, 
  PRIMARY KEY (CODIGO), 
  UNIQUE (SENHA)
);