<?php
$this->headScript()->appendFile('/js/jquery.maskedinput.min.js');
$this->headScript()->appendFile('/js/mascaras.js');
?>

<html dir="ltr">
    <head>
        <script src="/js/funcoesJquery.js"></script>

    </head>

    <div id="titulos">
        <h2>Perfil Social->Pescador</h2>
        <h3>Editar</h3>
    </div>

    <body>

        <form action="<?= $this->url(array("controller" => "pescador", "action" => "atualizar"), null, true) ?>" method="post">
            <a name="top"></a>

            <fieldset id="Social">
                <input type="hidden" name="idEndereco" value="<?= $this->pescador['te_id'] ?>" />
                <div id="esquerda">
                    <div id="form-dir">
                        <label for="idPescador">Código</label>
                        <input readonly="" type="text" name="idPescador" value="<?= $this->pescador['tp_id'] ?>" />
                    </div>

                    <div id="form-dir">
                        <label for="nome">Nome</label>
                        <input type="text" name="nome" id="nome" placeholder="Nome" value="<?= $this->pescador['tp_nome'] ?>"/><br/>
                    </div>

                    <div id="form-esq">
                        <label for="sexo">Sexo</label>
                        <select name="sexo" id="sexo">
                            <option value="M" <?= ( "M" == $this->pescador['tp_sexo']) ? 'selected="selected"' : ''; ?>><?= "Masculino"; ?></option>
                            <option value="F" <?= ( "F" == $this->pescador['tp_sexo']) ? 'selected="selected"' : ''; ?>><?= "Feminino"; ?></option>
                        </select>
                    </div>

                    <div id="form-dir">
                        <label for="matricula">Matricula</label>
                        <input type="text" name="matricula" id="matricula" placeholder="Matricula" value="<?= $this->pescador['tp_matricula'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="apelido">Apelido</label>
                        <input type="text" name="apelido" id="apelido" placeholder="Apelido" value="<?= $this->pescador['tp_apelido'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="filiacaoPai">Nome de Pai</label>
                        <input type="text" name="filiacaoPai" id="filiacaoPai" placeholder="Nome de Pai" value="<?= $this->pescador['tp_filiacaopai'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="filiacaoMae">Nome da Mãe</label>
                        <input type="text" name="filiacaoMae" id="filiacaoMae" placeholder="Nome da Mãe" value="<?= $this->pescador['tp_filiacaomae'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="rg">RG</label>
                        <input type="text" name="rg" id="rg" placeholder="RG" value="<?= $this->pescador['tp_rg'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="cpf">CPF</label>
                        <input type="text" name="cpf" id="cpf" placeholder="CPF" value="<?= $this->pescador['tp_cpf'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="dataNasc">Data Nascimento</label>
                        <input type="date" name="dataNasc" placeholder="Data Nascimento" min="1910-01-01" value="<?= $this->pescador['tp_datanasc'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="$municipioNat">Naturalidade</label>
                        <select name="municipioNat" id="municipioNat">
                            <?php foreach ($this->municipios as $key => $municipioNat): ?>
                                <option value="<?= $municipioNat['tmun_id']; ?>" <?= ($municipioNat['tmun_id'] == $this->pescador['tmun_id_natural']) ? 'selected="selected"' : ''; ?>>
                                    <?= $municipioNat['tmun_municipio'], ' ', $municipioNat['tuf_sigla']; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>

                    <div id="form-dir">
                        <label for="ctps">CTPS</label>
                        <input type="text" name="ctps" id="ctps" placeholder="CTPS" value="<?= $this->pescador['tp_ctps'] ?>"/>
                    </div>

                </div>

                <div id="direita">
                    <div id="form-dir">
                        <label for="logradouro">Logradouro</label>
                        <input type="text" name="logradouro" id="logradouro" placeholder="Logradouro" value="<?= $this->pescador['te_logradouro'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="numero">Número</label>
                        <input type="text" name="numero" id="numero" placeholder="Número" value="<?= $this->pescador['te_numero'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="bairro">Bairro</label>
                        <input type="text" name="bairro" id="bairro" placeholder="Bairro" value="<?= $this->pescador['te_bairro'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="$municipio">Municipio</label>
                        <select name="municipio" id="municipio">
                            <?php foreach ($this->municipios as $key => $municipio): ?>
                                <option value="<?= $municipio['tmun_id']; ?>" <?=
                                ($municipio['tmun_id'] == $this->pescador['tmun_id']) ? 'selected="selected"' :
                                        '';
                                ?>><?= $municipio['tmun_municipio'], ' ', $municipio['tuf_sigla']; ?></option>
                                    <?php endforeach; ?>
                        </select>
                    </div>

                    <div id="form-dir">
                        <label for="cep">CEP</label>
                        <input type="text" name="cep" id="cep" placeholder="CEP" value="<?= $this->pescador['te_cep'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="complemento">Complemento</label>
                        <input type="text" name="complemento" id="complemento" placeholder="Complemento" value="<?= $this->pescador['te_comp'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="pis">PIS</label>
                        <input type="text" name="pis" id="pis" placeholder="PIS" value="<?= $this->pescador['tp_pis'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="inss">INSS</label>
                        <input type="text" name="inss" id="inss" placeholder="INSS" value="<?= $this->pescador['tp_inss'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="nit_cei">NIT CEI</label>
                        <input type="text" name="nit_cei" id="nit_cei" placeholder="NIT CEI" value="<?= $this->pescador['tp_nit_cei'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="cma">CMA</label>
                        <input type="text" name="cma" id="cma" placeholder="CMA" value="<?= $this->pescador['tp_cma'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="rgb_maa_ibama">RGB MAA IBAMA</label>
                        <input type="text" name="rgb_maa_ibama" id="rgb_maa_ibama" placeholder="RGB MAA IBAMA" value="<?= $this->pescador['tp_rgb_maa_ibama'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="cir_cap_porto">CIR Cap. Porto</label>
                        <input type="text" name="cir_cap_porto" id="cir_cap_porto" placeholder="CIR Cap. Portos" value="<?= $this->pescador['tp_cir_cap_porto'] ?>"/>
                    </div>

                    <!--/_/_/_/_/_/_/_/_/_/_/_/_/_/ Escolaridade /_/_/_/_/_/_/_/_/_/_/_/_/_/-->
                    <div id="form-dir">
                        <label for="escolaridade" id="pure-checkbox">Escolaridade</label>
                        <select name="selectEscolaridade" id="selectEscolaridadeId">
                            <?php foreach ($this->assignEscolaridades as $key => $localEscolaridade): ?>
                                <option value="<?= $localEscolaridade['esc_id']; ?>"<?= ( $localEscolaridade['esc_id'] == $this->pescador['esc_id']) ? 'selected="selected"' : ''; ?>><?= $localEscolaridade['esc_nivel']; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>

                </div>
            </fieldset>

            <!--/_/_/_/_/_/_/_/_/_/_/_/_/_/ BOTÕES /_/_/_/_/_/_/_/_/_/_/_/_/_/-->
            <fieldset class="noBorder">
                <div id="Submit">
                    <table>
                        <td><a href="<?= $this->url(array("controller" => "pescador", "action" => "index"), null, true) ?>" id="botao-ancora">Voltar</a></td>
                        <td><input type="submit" value="Atualizar" /></td>
                        <td><input type="button" size="50" value="Salvar e Continuar" class="button-confirmText" onclick="jsAtualizarPescadorEndereco(this.form, '<?= $this->url(array("controller" => "pescador", "action" => "atualizarpescadorendereco"), null, true) ?>')"></td>
                    </table>
                </div>
            </fieldset>

            <!--//            /_/_/_/_/_/_/_/_/_/_/_/_/_/ Dependentes /_/_/_/_/_/_/_/_/_/_/_/_/_/-->
            <a id="ancora_dependentes"></a>
            <fieldset class="noEditable"><legend>Dependentes:</legend>
                <fieldset class="noEditable"><legend>Adicionar Dependentes:</legend>
                    <div id="base">
                        <input type="button" name="Add" class="button-confirm" onclick="jsInsertPescadorHasDependente(this.form, '<?= $this->url(array("controller" => "pescador", "action" => "insertpescadorhasdependente"), null, true) ?>')">

                        <input type="number" min="1" name="inputQuantidadeDependente" placeholder="Número de dependentes" size="20"  />

                        <select name="SelectDependente" id="Dependente">
                            <?php foreach ($this->assignTipoDependentes as $key => $localTipoDependente): ?>
                                <option value="<?= $localTipoDependente['ttd_id']; ?>">
                                    <?= $localTipoDependente['ttd_tipodependente']; ?></option><?php endforeach; ?>
                        </select>
                    </div>
                </fieldset>
                <br>

                <table id="tblDependentes">
                    <tr>
                        <th width="15%">ID </th>
                        <th width="65%">Dependente</th>
                        <th>Familiares</th>
                        <th width="5%"></th>
                    </tr>
                    <?php foreach ($this->assign_vPescadorDependente as $key => $vPescadorHasDependente): ?>
                        <tr id="rowNumDependente<?= $key ?>">
                            <td name="inputTipoDependenteID[]"> <?= $vPescadorHasDependente['ttd_id'] ?> </td>
                            <td name="inputTipoDependente[]" > <?= $vPescadorHasDependente['ttd_tipodependente'] ?> </td>
                            <td name="inputQuantidadeDependente[]" > <?= $vPescadorHasDependente['tptd_quantidade'] ?> </td>
                            <td><input type="button" class="button-del" width="5%" onclick="jsDeletePescadorHasDependente(<?= $vPescadorHasDependente['ttd_id'] ?>, this.form, '<?= $this->url(array("controller" => "pescador", "action" => "deletepescadorhasdependente"), null, true) ?>')"></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </fieldset>
            <fieldset class="noBorder">
                <br><input type="button" class="button-up" width="5%" onclick="scrollTo('top')">
            </fieldset>
            <!--//            /_/_/_/_/_/_/_/_/_/_/_/_/_/ Renda /_/_/_/_/_/_/_/_/_/_/_/_/_/-->
            <a id="ancora_rendas"></a><fieldset class="noEditable"><legend>Renda:</legend>
                <fieldset class="noEditable"><legend>Adicionar Renda:</legend>
                    <div id="base">
                        <input type="button" name="Add" class="button-confirm" onclick="jsInsertPescadorHasRenda(this.form, '<?= $this->url(array("controller" => "pescador", "action" => "insertpescadorhasrenda"), null, true) ?>')">

                        <select name="SelectRenda" id="Renda">
                            <?php foreach ($this->assignRendas as $key => $localRenda): ?>
                                <option value="<?= $localRenda['ren_id']; ?>">
                                    <?= $localRenda['ren_renda']; ?></option><?php endforeach; ?>
                        </select>

                        <select name="SelectTipoRenda" id="TipoRenda">
                            <?php foreach ($this->assignTipoRendas as $key => $localTipoRenda): ?>
                                <option value="<?= $localTipoRenda['ttr_id']; ?>">
                                    <?= $localTipoRenda['ttr_descricao']; ?></option><?php endforeach; ?>
                        </select>

                    </div>

                </fieldset>
                <br>
                <table id="tblRenda">
                    <tr>
                        <th width="10%">ID </th>
                        <th width="40%">Renda</th>
                        <th width="10%">ID </th>
                        <th width="35%">Descrição</th>
                        <th width="5%"></th>
                    </tr>
                    <?php foreach ($this->assign_vPescadorRenda as $key => $vPescadorHasRenda): ?>
                        <tr id="rowRenda<?= $key ?>">
                            <td name="inputRendaID[]"> <?= $vPescadorHasRenda['ttr_id'] ?> </td>
                            <td name="inputRenda[]" > <?= $vPescadorHasRenda['ttr_descricao'] ?> </td>
                            <td name="inputTipoRendaID[]" > <?= $vPescadorHasRenda['ren_id'] ?> </td>
                            <td name="inputTipoRenda[]" > <?= $vPescadorHasRenda['ren_renda'] ?> </td>
                            <td><input type="button" class="button-del" width="5%" onclick="jsDeletePescadorHasRenda(<?= $vPescadorHasRenda['ttr_id'] ?>,<?= $vPescadorHasRenda['ren_id'] ?>, this.form, '<?= $this->url(array("controller" => "pescador", "action" => "deletepescadorhasrenda"), null, true) ?>')"></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </fieldset>
            <fieldset class="noBorder">
                <br><input type="button" class="button-up" width="5%" onclick="scrollTo('top')">
            </fieldset>
<!--//            /_/_/_/_/_/_/_/_/_/_/_/_/_/ Programa Social /_/_/_/_/_/_/_/_/_/_/_/_/_/-->
            <a id="ancora_programasocial"></a><fieldset class="noEditable"><legend>Programa Social:</legend>
                <fieldset class="noEditable"><legend>Adicionar Programa Social:</legend>

                    <div id="base">
                        <input type="button" name="Add" class="button-confirm" onclick="jsInsertPescadorHasProgramaSocial(this.form, '<?= $this->url(array("controller" => "pescador", "action" => "insertpescadorhasprogramasocial"), null, true) ?>')">
                        <select name="selectProgramaSocial" id="programaSocial">
                            <?php foreach ($this->assignProgramaSocial as $key => $programaSocial): ?>
                                <option value="<?= $programaSocial['prs_id']; ?>"><?= $programaSocial['prs_programa']; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </fieldset>
                <br>

                <table id="tblProgramaSocial">
                    <tr>
                        <th width="15%">ID </th>
                        <th width="65%">Programa Social</th>
                        <th width="5%"></th>
                    </tr>
                    <?php foreach ($this->assign_vPescadorProgramaSocial as $key => $vPescadorHasProgramaSocial): ?>
                        <tr id="linhaAreaPescaRows<?= $key ?>">
                            <td name="inputPS_ID[]"> <?= $vPescadorHasProgramaSocial['prs_id'] ?> </td>
                            <td name="inputPS[]" > <?= $vPescadorHasProgramaSocial['prs_programa'] ?> </td>
                            <td><input type="button" class="button-del" width="5%" onclick="jsDeletePescadorHasProgramaSocial(<?= $vPescadorHasProgramaSocial['prs_id'] ?>, this.form, '<?= $this->url(array("controller" => "pescador", "action" => "deletepescadorhasprogramasocial"), null, true) ?>')"></td> </td>
                        </tr>
                    <?php endforeach; ?>
                </table>

            </fieldset>


            <fieldset class="noBorder">
                <br><input type="button" class="button-up" width="5%" onclick="scrollTo('top')">
            </fieldset>
<!--//            /_/_/_/_/_/_/_/_/_/_/_/_/_/ Comunidade /_/_/_/_/_/_/_/_/_/_/_/_/_/-->
            <a id="ancora_comunidade"></a><fieldset class="noEditable"><legend>Comunidade:</legend>
                <fieldset class="noEditable"><legend>Adicionar Comunidade:</legend>

                    <div id="base">
                        <input type="button" name="Add" class="button-confirm" onclick="jsInsertPescadorHasComunidade(this.form, '<?= $this->url(array("controller" => "pescador", "action" => "insertpescadorhascomunidade"), null, true) ?>')">
                        <select name="selectComunidade" id="selectComunidadeID">
                            <?php foreach ($this->assignComunidade as $key => $pescadorHasComunidade): ?>
                                <option value="<?= $pescadorHasComunidade['tcom_id']; ?>"><?= $pescadorHasComunidade['tcom_nome']; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </fieldset>
                <br>

                <table id="tblComunidade">
                    <tr>
                        <th width="15%">ID </th>
                        <th width="65%">Comunidade</th>
                        <th width="5%"></th>
                    </tr>
                    <?php foreach ($this->assign_vPescadorComunidade as $key => $vPescadorHasComunidade): ?>
                        <tr id="linhaAreaPescaRows<?= $key ?>">
                            <td name="inputComunidadeID[]"> <?= $vPescadorHasComunidade['tcom_id'] ?> </td>
                            <td name="inputComunidade[]" > <?= $vPescadorHasComunidade['tcom_nome'] ?> </td>
                            <td><input type="button" class="button-del" width="5%" onclick="jsDeletePescadorHasComunidade(<?= $vPescadorHasComunidade['tcom_id'] ?>, this.form, '<?= $this->url(array("controller" => "pescador", "action" => "deletepescadorhascomunidade"), null, true) ?>')"></td> </td>
                        </tr>
                    <?php endforeach; ?>
                </table>

            </fieldset>

            <fieldset class="noBorder">
                <br><input type="button" class="button-up" width="5%" onclick="scrollTo('top')">
            </fieldset>
                        
<!--//            /_/_/_/_/_/_/_/_/_/_/_/_/_/ PORTO /_/_/_/_/_/_/_/_/_/_/_/_/_/-->
            <a id="ancora_porto"></a><fieldset class="noEditable"><legend>Porto de Desembarque:</legend>
                <fieldset class="noEditable"><legend>Adicionar Porto de Desembarque:</legend>

                    <div id="base">
                        <input type="button" name="Add" class="button-confirm" onclick="jsInsertPescadorHasPorto(this.form, '<?= $this->url(array("controller" => "pescador", "action" => "insertpescadorhasporto"), null, true) ?>')">
                        <select name="selectPorto" id="selectPortoID">
                            <?php foreach ($this->assignPorto as $key => $pescadorHasPorto): ?>
                                <option value="<?= $pescadorHasPorto['pto_id']; ?>"><?= $pescadorHasPorto['pto_nome']; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </fieldset>
                <br>

                <table id="tblPorto">
                    <tr>
                        <th width="15%">ID </th>
                        <th width="65%">Porto de Desembarque</th>
                        <th width="5%"></th>
                    </tr>
                    <?php foreach ($this->assign_vPescadorPorto as $key => $vPescadorHasPorto): ?>
                        <tr id="linhaAreaPescaRows<?= $key ?>">
                            <td name="inputPortoID[]"> <?= $vPescadorHasPorto['pto_id'] ?> </td>
                            <td name="inputPorto[]" > <?= $vPescadorHasPorto['pto_nome'] ?> </td>
                            <td><input type="button" class="button-del" width="5%" onclick="jsDeletePescadorHasPorto(<?= $vPescadorHasPorto['pto_id'] ?>, this.form, '<?= $this->url(array("controller" => "pescador", "action" => "deletepescadorhasporto"), null, true) ?>')"></td> </td>
                        </tr>
                    <?php endforeach; ?>
                </table>

            </fieldset>

            <fieldset class="noBorder">
                <br><input type="button" class="button-up" width="5%" onclick="scrollTo('top')">
            </fieldset>

            <!--//            /_/_/_/_/_/_/_/_/_/_/_/_/_/ Telefone /_/_/_/_/_/_/_/_/_/_/_/_/_/-->
            <a id="ancora_telefones"></a><fieldset class="noEditable"><legend>Telefones:</legend>
                <fieldset class="noEditable"><legend>Adicionar Telefone:</legend>

                    <div id="base">
                        <input type="button" name="Add" class="button-confirm" onclick="jsInsertPescadorHasTelefone(this.form, '<?= $this->url(array("controller" => "pescador", "action" => "insertpescadorhastelefone"), null, true) ?>')">
                        <input type="text" name="inputTelefone" size="20" class="telefone" />
                        <select name="selectTipoTelefone" id="selectTipoTelefone" >
                            <?php foreach ($this->assignTipoTelefones as $key => $tipoTelefones): ?><option value="<?= $tipoTelefones['ttel_id']; ?>"><?= $tipoTelefones['ttel_desc']; ?></option><?php endforeach; ?>
                        </select>
                    </div>
                </fieldset>
                <br>
                <table id="tblTelefones">
                    <tr>
                        <th width="15%">ID </th>
                        <th width="40%">Telefones</th>
                        <th width="40%">Nº Telefone</th>
                        <th width="5%"></th>
                    </tr>
                    <?php foreach ($this->assign_vPescadorHasTelefone as $key => $vPescadorHasTelefone): ?>
                        <tr id="rowNumTelefone<?= $key ?>">
                            <td name="inputTipoID[]"> <?= $vPescadorHasTelefone['tpt_ttel_id'] ?> </td>
                            <td name="inputTipo[]" > <?= $vPescadorHasTelefone['ttel_desc'] ?> </td>
                            <td name="inputTelefone[]" chass="telefone" > <?= $vPescadorHasTelefone['tpt_telefone'] ?> </td>
                            <td><input type="button" class="button-del" width="5%" onclick="jsDeletePescadorHasTelefone(<?= $vPescadorHasTelefone['tpt_ttel_id'] ?>, this.form, '<?= $this->url(array("controller" => "pescador", "action" => "deletepescadorhastelefone"), null, true) ?>')"></td>
                        </tr>
                    <?php endforeach; ?>
                </table>

            </fieldset>
            <fieldset class="noBorder">
                <br><input type="button" class="button-up" width="5%" onclick="scrollTo('top')">
            </fieldset>
            <!--//            /_/_/_/_/_/_/_/_/_/_/_/_/_/ Colonias /_/_/_/_/_/_/_/_/_/_/_/_/_/-->
            <a id="ancora_colonias"></a><fieldset class="noEditable"><legend>Colonias:</legend>
                <fieldset class="noEditable"><legend>Adicionar Colonias:</legend>
                    <div id="base">
                        <input type="button" name="Add" class="button-confirm" onclick="jsInsertPescadorHasColonia(this.form, '<?= $this->url(array("controller" => "pescador", "action" => "insertpescadorhascolonia"), null, true) ?>')">
                        <input type="date" name="inputDataInscricaoColonia" placeholder="Data Inscrição na Colonia" size="20"  />

                        <select name="SelectColonia" id="colonia">
                            <?php foreach ($this->colonias as $key => $colonia): ?>
                                <option value="<?= $colonia['tc_id']; ?>">
                                    <?= $colonia['tc_nome']; ?></option><?php endforeach; ?>
                        </select>

                    </div>
                </fieldset>
                <br>
                <table id="tblColonias">
                    <tr>
                        <th width="15%">ID </th>
                        <th width="65%">Colonia</th>
                        <th>Data inscrição</th>
                        <th width="5%"></th>
                    </tr>
                    <?php foreach ($this->assign_vPescadorColonia as $key => $vPescadorHasColonia): ?>
                        <tr id="rowNumColonias<?= $key ?>">
                            <td name="inputColoniaID[]"> <?= $vPescadorHasColonia['tc_id'] ?> </td>
                            <td name="inputColonia[]" > <?= $vPescadorHasColonia['tc_nome'] ?> </td>
                            <td name="inputDataInscricaoColonia[]" > <?= $vPescadorHasColonia['tptc_datainsccolonia'] ?> </td>
                            <td><input type="button" class="button-del" width="5%" onclick="jsDeletePescadorHasColonia(<?= $vPescadorHasColonia['tc_id'] ?>, this.form, '<?= $this->url(array("controller" => "pescador", "action" => "deletepescadorhascolonia"), null, true) ?>')"></td> </td>
                        </tr>
                    <?php endforeach; ?>
                </table>

            </fieldset>
            <fieldset class="noBorder">
                <br><input type="button" class="button-up" width="5%" onclick="scrollTo('top')">
            </fieldset>
            <!--//            /_/_/_/_/_/_/_/_/_/_/_/_/_/ Area de Pesca /_/_/_/_/_/_/_/_/_/_/_/_/_/-->
            <a id="ancora_areas"></a><fieldset class="noEditable"><legend>Area de Pesca:</legend>
                <fieldset class="noEditable"><legend>Adicionar Area de Pesca:</legend>

                    <div id="base">
                        <input type="button" name="Add" class="button-confirm" onclick="jsInsertPescadorHasArea(this.form, '<?= $this->url(array("controller" => "pescador", "action" => "insertpescadorhasarea"), null, true) ?>')">
                        <select name="selectAreaPesca" id="areaPesca">
                            <?php foreach ($this->areasPesca as $key => $areaPesca): ?>
                                <option value="<?= $areaPesca['tareap_id']; ?>"><?= $areaPesca['tareap_areapesca']; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </fieldset>
                <br>

                <table id="tblAreaPesca">
                    <tr>
                        <th width="15%">ID </th>
                        <th width="65%">Área de Pesca</th>
                        <th width="5%"></th>
                    </tr>
                    <?php foreach ($this->assign_vPescadorAreaPesca as $key => $vPescadorHasAreaPesca): ?>
                        <tr id="linhaAreaPescaRows<?= $key ?>">
                            <td name="inputAreaID[]"> <?= $vPescadorHasAreaPesca['tareap_id'] ?> </td>
                            <td name="inputArea[]" > <?= $vPescadorHasAreaPesca['tareap_areapesca'] ?> </td>
                            <td><input type="button" class="button-del" width="5%" onclick="jsDeletePescadorHasArea(<?= $vPescadorHasAreaPesca['tareap_id'] ?>, this.form, '<?= $this->url(array("controller" => "pescador", "action" => "deletepescadorhasarea"), null, true) ?>')"></td> </td>
                        </tr>
                    <?php endforeach; ?>
                </table>

            </fieldset>


            <fieldset class="noBorder">
                <br><input type="button" class="button-up" width="5%" onclick="scrollTo('top')">
            </fieldset>
            <!--//            /_/_/_/_/_/_/_/_/_/_/_/_/_/ Arte de Pesca /_/_/_/_/_/_/_/_/_/_/_/_/_/-->
            <a id="ancora_arte"></a><fieldset class="noEditable"><legend>Artes de Pesca:</legend>
                <fieldset class="noEditable"><legend>Adicionar Artes de Pesca:</legend>

                    <div id="base">
                        <input type="button" name="Add" class="button-confirm" onclick="jsInsertPescadorHasArteTipo(this.form, '<?= $this->url(array("controller" => "pescador", "action" => "insertpescadorhasartetipo"), null, true) ?>')">

                        <select name="SelectArtePesca" id="artePesca">
                            <?php foreach ($this->artesPesca as $key => $artePesca): ?>
                                <option value="<?= $artePesca['tap_id']; ?>"><?= $artePesca['tap_artepesca']; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>

                </fieldset>
                <br>
                <table id="tblArteTipoPescas">
                    <tr>
                        <th width="10%">ID </th>
                        <th width="40%">Arte de Pesca</th>
                        <th width="5%"></th>
                    </tr>
                    <?php foreach ($this->assign_vPescadorArteTipoArea as $key => $vPescadorHasArteTipoArea): ?>
                        <tr id="linhaArteTipoRows<?= $key ?>">
                            <td name="inputArteID[]"> <?= $vPescadorHasArteTipoArea['tap_id'] ?> </td>
                            <td name="inputArte[]" > <?= $vPescadorHasArteTipoArea['tap_artepesca'] ?> </td>
                            <td><input type="button" class="button-del" width="5%" onclick="jsDeletePescadorHasArteTipo(<?= $vPescadorHasArteTipoArea['tap_id'] ?>, this.form, '<?= $this->url(array("controller" => "pescador", "action" => "deletepescadorhasartetipo"), null, true) ?>')"></td> </td>
                        </tr>
                    <?php endforeach; ?>
                </table>

            </fieldset>
            <fieldset class="noBorder">
                <br><input type="button" class="button-up" width="5%" onclick="scrollTo('top')">
            </fieldset>
             <!--//            /_/_/_/_/_/_/_/_/_/_/_/_/_/ Tipo de Pesca /_/_/_/_/_/_/_/_/_/_/_/_/_/-->
            <a id="ancora_tipos"></a><fieldset class="noEditable"><legend>Tipos de Capturas:</legend>
                <fieldset class="noEditable"><legend>Adicionar Tipos de Capturas:</legend>

                    <div id="base">
                        <input type="button" name="Add" class="button-confirm" onclick="jsInsertPescadorHasTipoCapturada(this.form, '<?= $this->url(array("controller" => "pescador", "action" => "insertpescadorhastipo"), null, true) ?>')">

                        <select name="selectTipoCapturada" id="tipocapturada">
                            <?php foreach ($this->tipoCapturadas as $key => $tipoCapturadas): ?>
                                <option value="<?= $tipoCapturadas['itc_id']; ?>"><?= $tipoCapturadas['itc_tipo']; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>

                </fieldset>
                <br>
                <table id="tblArteTipoPescas">
                    <tr>
                        <th width="10%">ID</th>
                        <th width="35%">Tipo de Pesca</th>
                        <th width="5%"></th>
                    </tr>
                    <?php foreach ($this->assign_vPescadorTipoCapturada as $key => $vPescadorHasTipoCapturada): ?>
                        <tr id="linhaTipoCapturadaRows<?= $key ?>">
                            <td name="inputTipoID[]"> <?= $vPescadorHasTipoCapturada['itc_id'] ?> </td>
                            <td name="inputTipo[]" > <?= $vPescadorHasTipoCapturada['itc_tipo'] ?> </td>
                            <td><input type="button" class="button-del" width="5%" onclick="jsDeletePescadorHasTipoCapturada(<?= $vPescadorHasTipoCapturada['itc_id'] ?>, this.form, '<?= $this->url(array("controller" => "pescador", "action" => "deletepescadorhastipo"), null, true) ?>')"></td> </td>
                        </tr>
                    <?php endforeach; ?>
                </table>

            </fieldset>
            <fieldset class="noBorder">
                <br><input type="button" class="button-up" width="5%" onclick="scrollTo('top')">
            </fieldset>
            <!--//            /_/_/_/_/_/_/_/_/_/_/_/_/_/ Embarcações /_/_/_/_/_/_/_/_/_/_/_/_/_/-->
            <a id="ancora_embarcacoes"></a><fieldset class="noEditable"><legend>Embarcações e Porte das Embarcações:</legend>
                <fieldset class="noEditable"><legend>Adicionar Embarcações:</legend>

                    <div id="base">
                        <input type="button" class="button-confirm" onclick="jsInsertPescadorHasEmbarcacoes(this.form, '<?= $this->url(array("controller" => "pescador", "action" => "insertpescadorhasembarcacoes"), null, true) ?>')">

                        <select name="selectMotorEmbarcacao" id="motorEmbarcacao">
                            <option value="0" >Sem motor</option>
                            <option value="1" >Com motor</option>
                        </select>

                        <select name="selectPorteEmbarcacao" id="porteEmbarcacao">
                            <?php foreach ($this->portesEmbarcacao as $key => $porteEmbarcacao): ?>
                                <option value="<?= $porteEmbarcacao['tpe_id']; ?>"><?= $porteEmbarcacao['tpe_porte']; ?></option>
                            <?php endforeach; ?>
                        </select>

                        <select name="selectTipoEmbarcacao" id="tipoEmbarcacao">
                            <?php foreach ($this->tiposEmbarcacao as $key => $tipoEmbarcacao): ?>
                                <option value="<?= $tipoEmbarcacao['tte_id']; ?>"><?= $tipoEmbarcacao['tte_tipoembarcacao']; ?></option>
                            <?php endforeach; ?>
                        </select>
                        <select name="selectDonoEmbarcacao" id="donoEmbarcacao">
                            <option value="0" >Usuário</option>
                            <option value="1" >Proprietário</option>
                        </select>
                    </div>

                </fieldset>
                <br>
                <table id="tblEmbarcacoes">
                    <tr>
                        <th width="30%">Proprietário</th>
                        <th width="5%">ID </th>
                        <th width="30%">Embarcação</th>
                        <th width="5%">ID</th>
                        <th width="30%">Porte da Embarcação</th>
                        <th width="5%">ID</th>
                        <th width="20%">Motor</th>
                        <th width="5%"></th>
                    </tr>
                    <?php foreach ($this->assign_vPescadorEmbarcacao as $key => $vPescadorHasEmbarcacao): ?>
                        <tr id="itemEmbarcacoesRows<?= $key ?>">
                            <td name="inputMotor[]" > <?= ( $vPescadorHasEmbarcacao['tpte_dono'] == 0 ) ? 'Usuário' : 'Proprietário' ?> </td>
                            <td name="inputBarcoID[]"> <?= $vPescadorHasEmbarcacao['tte_id'] ?> </td>
                            <td name="inputBarco[]" > <?= $vPescadorHasEmbarcacao['tte_tipoembarcacao'] ?> </td>
                            <td name="inputPorteID[]"> <?= $vPescadorHasEmbarcacao['tpe_id'] ?> </td>
                            <td name="inputPorte[]" > <?= $vPescadorHasEmbarcacao['tpe_porte'] ?> </td>
                            <td name="inputMotorID[]"> <?= $vPescadorHasEmbarcacao['tpte_motor'] ?> </td>
                            <td name="inputMotor[]" > <?= ( $vPescadorHasEmbarcacao['tpte_motor'] == 0 ) ? 'Sem motor' : 'Com motor' ?> </td>
                            <td><input type="button" class="button-del" width="5%" onclick="jsDeletePescadorHasEmbarcacoes(<?= $vPescadorHasEmbarcacao['tte_id'] ?>, <?= $vPescadorHasEmbarcacao['tpe_id'] ?>, this.form, '<?= $this->url(array("controller" => "pescador", "action" => "deletepescadorhasembarcacoes"), null, true) ?>')"></td> </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </fieldset>
            <fieldset class="noBorder">
                <br><input type="button" class="button-up" width="5%" onclick="scrollTo('top')">
            </fieldset>

            <!--//            /_/_/_/_/_/_/_/_/_/_/_/_/_//_/_/_/_/_/_/_/_/_/_/_/_/_/-->
        </form>
    </body>
</html>