<?php
$this->headScript()->appendFile('/js/jquery.maskedinput.min.js');
$this->headScript()->appendFile('/js/mascaras.js');
?>

<html dir="ltr">
    <head>
        <script type="text/javascript">
            function msg()
            {
                alert("Hello world!");
            }

            var rowNum = 1000; //Não sobrepor numeração existente
            function addRowPhone(frm) {
                rowNum++;

                var tmpTelefone = frm.inputTelefone.value;
                var tmpSelectText = frm.selectTipoTelefone.text;
                var tmpSelectID = frm.selectTipoTelefone.value;

                for (var i = 0; i < frm.selectTipoTelefone.length; i++) {
                    if (frm.selectTipoTelefone[i].value == tmpSelectID) {
                        tmpSelectText = frm.selectTipoTelefone[i].text;
                    }
                }

                if (tmpSelectText && tmpTelefone) {

                    var linhaTelefones = '<div class="noEditable"><p id="rowNum' + rowNum + '">';
                    linhaTelefones = linhaTelefones.concat('<input type="button" value="Remove" onclick="removeRowPhone(' + rowNum + ');">');
                    linhaTelefones = linhaTelefones.concat('<input type="text" readonly size="15" name="inputTelefone[]" class="telefone" value="' + tmpTelefone + '">');
                    linhaTelefones = linhaTelefones.concat('<input type="text" readonly size="15" name="inputTipo[]" value="' + tmpSelectText + '">');
                    linhaTelefones = linhaTelefones.concat('<input type="text" readonly size="8" name="inputTipoID[]" value="' + tmpSelectID + '">');
                    linhaTelefones = linhaTelefones.concat('<br></p></div>');

                    jQuery('#itemRows').append(linhaTelefones);
                    frm.inputTelefone.value = '';
                    frm.selectTipoTelefone.value = '';
                }
            }

            function removeRowPhone(rnum) {
                jQuery('#rowNum' + rnum).remove();
            }

        </script>
    </head>

    <div id="titulos">
        <h2>Perfil Social->Pescador</h2>
        <h3>Editar</h3>
    </div>

    <body onload="onloadAddRowPhone()">
        <form action="<?= $this->url(array("controller" => "pescador", "action" => "atualizar"), null, true) ?>" method="post">

            <fieldset id="Social">
                <input type="hidden" name="idPescador" value="<?= $this->pescador['tp_id'] ?>" />
                <input type="hidden" name="idEndereco" value="<?= $this->pescador['te_id'] ?>" />
                <div id="esquerda">
                    <div id="form-dir">
                        <label for="idPescador">Código</label>
                        <input readonly="" type="text" name="idPescador" value="<?= $this->pescador['tp_id'] ?>" />
                    </div>

                    <div id="form-dir">
                        <label for="nome">Nome</label>
                        <input type="text" name="nome" id="nome" placeholder="Nome" value="<?= $this->pescador['tp_nome'] ?>"/><br/>
                    </div>

                    <div id="form-esq">
                        <label for="sexo">Sexo</label>
                        <select name="sexo" id="sexo">
                            <option value="M" <?= ( "M" == $this->pescador['tp_sexo']) ? 'selected="selected"' : ''; ?>><?= "Masculino"; ?></option>
                            <option value="F" <?= ( "F" == $this->pescador['tp_sexo']) ? 'selected="selected"' : ''; ?>><?= "Feminino"; ?></option>
                        </select>
                    </div>

                    <div id="form-dir">
                        <label for="matricula">Matricula</label>
                        <input type="text" name="matricula" id="matricula" placeholder="Matricula" value="<?= $this->pescador['tp_matricula'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="apelido">Apelido</label>
                        <input type="text" name="apelido" id="apelido" placeholder="Apelido" value="<?= $this->pescador['tp_apelido'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="filiacaoPai">Nome de Pai</label>
                        <input type="text" name="filiacaoPai" id="filiacaoPai" placeholder="Nome de Pai" value="<?= $this->pescador['tp_filiacaopai'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="filiacaoMae">Nome da Mãe</label>
                        <input type="text" name="filiacaoMae" id="filiacaoMae" placeholder="Nome da Mãe" value="<?= $this->pescador['tp_filiacaomae'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="rg">RG</label>
                        <input type="text" name="rg" id="rg" placeholder="RG" value="<?= $this->pescador['tp_rg'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="cpf">CPF</label>
                        <input type="text" name="cpf" id="cpf" placeholder="CPF" value="<?= $this->pescador['tp_cpf'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="dataNasc">Data Nascimento</label>
                        <input type="text" name="dataNasc" id="data_Nasc" placeholder="Data Nascimento" value="<?= $this->pescador['tp_datanasc'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="$municipioNat">Naturalidade</label>
                        <select name="municipioNat" id="municipioNat">
                            <?php foreach ($this->municipios as $key => $municipioNat): ?>
                                <option value="<?= $municipioNat['tmun_id']; ?>" <?= ($municipioNat['tmun_id'] == $this->pescador['tmun_id_natural']) ? 'selected="selected"' : ''; ?>>
                                    <?= $municipioNat['tuf_sigla'], ' ', $municipioNat['tmun_municipio']; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>

                    <div id="form-dir">
                        <label for="ctps">CTPS</label>
                        <input type="text" name="ctps" id="ctps" placeholder="CTPS" value="<?= $this->pescador['tp_ctps'] ?>"/>
                    </div>

                </div>

                <div id="direita">
                    <div id="form-dir">
                        <label for="logradouro">Logradouro</label>
                        <input type="text" name="logradouro" id="logradouro" placeholder="Logradouro" value="<?= $this->pescador['te_logradouro'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="numero">Número</label>
                        <input type="text" name="numero" id="numero" placeholder="Número" value="<?= $this->pescador['te_numero'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="bairro">Bairro</label>
                        <input type="text" name="bairro" id="bairro" placeholder="Bairro" value="<?= $this->pescador['te_bairro'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="$municipio">Municipio</label>
                        <select name="municipio" id="municipio">
                            <?php foreach ($this->municipios as $key => $municipio): ?>
                                <option value="<?= $municipio['tmun_id']; ?>" <?=
                                ($municipio['tmun_id'] == $this->pescador['tmun_id']) ? 'selected="selected"' :
                                        '';
                                ?>><?= $municipio['tuf_sigla'], ' ', $municipio['tmun_municipio']; ?></option>
                                    <?php endforeach; ?>
                        </select>
                    </div>

                    <div id="form-dir">
                        <label for="cep">CEP</label>
                        <input type="text" name="cep" id="cep" placeholder="CEP" value="<?= $this->pescador['te_cep'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="complemento">Complemento</label>
                        <input type="text" name="complemento" id="complemento" placeholder="Complemento" value="<?= $this->pescador['te_comp'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="pis">PIS</label>
                        <input type="text" name="pis" id="pis" placeholder="PIS" value="<?= $this->pescador['tp_pis'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="inss">INSS</label>
                        <input type="text" name="inss" id="inss" placeholder="INSS" value="<?= $this->pescador['tp_inss'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="nit_cei">NIT CEI</label>
                        <input type="text" name="nit_cei" id="nit_cei" placeholder="NIT CEI" value="<?= $this->pescador['tp_nit_cei'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="cma">CMA</label>
                        <input type="text" name="cma" id="cma" placeholder="CMA" value="<?= $this->pescador['tp_cma'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="rgb_maa_ibama">RGB MAA IBAMA</label>
                        <input type="text" name="rgb_maa_ibama" id="rgb_maa_ibama" placeholder="RGB MAA IBAMA" value="<?= $this->pescador['tp_rgb_maa_ibama'] ?>"/>
                    </div>

                    <div id="form-dir">
                        <label for="cir_cap_porto">CIR Cap. Porto</label>
                        <input type="text" name="cir_cap_porto" id="cir_cap_porto" placeholder="CIR Cap. Portos" value="<?= $this->pescador['tp_cir_cap_porto'] ?>"/>
                    </div>
                </div>
            </fieldset>

            <fieldset class="noEditable"><legend>Telefones:</legend>
                <fieldset class="noEditable"><legend>Adicionar Telefone:</legend>

                    <div id="base">
                        <input onclick="addRowPhone(this.form);" type="button" value="Add row" />
                        <input type="text" name="inputTelefone" size="20" class="telefone" />
                        <select name="selectTipoTelefone" id="selectTipoTelefone" >
                            <?php foreach ($this->assignTipoTelefones as $key => $tipoTelefones): ?>
                                <option value="<?= $tipoTelefones['ttel_id']; ?>"><?= $tipoTelefones['ttel_desc']; ?></option><?php endforeach; ?>
                        </select>
                    </div>
                </fieldset>
                <br>
                <fieldset class="noEditable" id="itemRows"><legend>Telefone listados:</legend>

                    <?php foreach ($this->assign_vPescadorHasTelefone as $key => $vPescadorHasTelefone): ?>
                        <div class="noEditable"><p id="rowNum<?=$key?>">
                                <input type="button" value="Remove" onclick="removeRowPhone( <?=$key?> );">
                                <input type="text" readonly size="15" name="inputTelefone[]" class="telefone" value="<?= $vPescadorHasTelefone['tpt_telefone'] ?>">
                                <input type="text" readonly size="15" name="inputTipo[]" value="<?= $vPescadorHasTelefone['ttel_desc'] ?>">
                                <input type="text" readonly size="8" name="inputTipoID[]" value="<?= $vPescadorHasTelefone['tpt_ttel_id'] ?><?=$key?>">
                                <br>
                            </p></div>
                    <?php endforeach; ?>

                </fieldset>
            </fieldset>
            <br>
            <fieldset class="noEditable"><legend>Colonias:</legend>
                <fieldset class="noEditable"><legend>Adicionar Colonias:</legend>

                    <div id="base">
                        <input onclick="addRowColonia(this.form);" type="button" value="Add row" />
                        <input type="date" name="inputDataInscricaoColonia" placeholder="Data Inscrição na Colonia" size="20"  />
                        
                        <select name="colonia" id="colonia">
                            <?php foreach ($this->colonias as $key => $colonia): ?>
                            <option value="<?= $colonia['tc_id']; ?>">
                            <?= $colonia['tc_nome']; ?></option><?php endforeach; ?>
                        </select>
                        
                    </div>

                </fieldset>
                <br>
                <fieldset class="noEditable" id="itemColoniaRows"><legend>Artes de Pesca e Tipos de Capturas listados:</legend>
                    <!--Area para inserir os itens-->
                </fieldset>
            </fieldset>
            <br>
            <fieldset class="noEditable"><legend>Artes de Pesca e Tipos de Capturas:</legend>
                <fieldset class="noEditable"><legend>Adicionar Artes de Pesca e Tipos de Capturas:</legend>

                    <div id="base">
                        <input onclick="addRowArte(this.form);" type="button" value="Add row" />
                        
                        <select name="areaPesca" id="areaPesca">
                            <?php foreach ($this->areasPesca as $key => $areaPesca): ?>
                                <option value="<?= $areaPesca['tareap_id']; ?>"><?= $areaPesca['tareap_areapesca']; ?></option>
                            <?php endforeach; ?>
                        </select>

                        <select name="tipocapturada" id="tipocapturada">
                            <?php foreach ($this->tipoCapturadas as $key => $tipoCapturadas): ?>
                                <option value="<?= $tipoCapturadas['itc_id']; ?>"><?= $tipoCapturadas['itc_tipo']; ?></option>
                            <?php endforeach; ?>
                        </select>
                        <select name="artePesca" id="artePesca">
                            <?php foreach ($this->artesPesca as $key => $artePesca): ?>
                                <option value="<?= $artePesca['tap_id']; ?>"><?= $artePesca['tap_artepesca']; ?></option>
                                    <?php endforeach; ?>
                        </select>
                    </div>

                </fieldset>
                <br>
                <fieldset class="noEditable" id="itemArteTipoRows"><legend>Artes de Pesca e Tipos de Capturas listados:</legend>
                    <!--Area para inserir os itens-->
                </fieldset>
            </fieldset>
            <br>
            <fieldset class="noEditable"><legend>Embarcações e Porte das Embarcações:</legend>
                <fieldset class="noEditable"><legend>Adicionar Embarcações:</legend>

                    <div id="base">
                        <input onclick="addRowEmbarcacao(this.form);" type="button" value="Adicionar" />
                        
                        <select name="motorEmbarcacao" id="motorEmbarcacao">
                            <option value="0" >Sem motor</option>
                            <option value="1" >Com motor</option>
                        </select>

                        <select name="porteEmbarcacao" id="porteEmbarcacao">
                            <?php foreach ($this->portesEmbarcacao as $key => $porteEmbarcacao): ?>
                                <option value="<?= $porteEmbarcacao['tpe_id']; ?>"><?= $porteEmbarcacao['tpe_porte']; ?></option>
                                    <?php endforeach; ?>
                        </select>

                        <select name="tipoEmbarcacao" id="tipoEmbarcacao">
                            <?php foreach ($this->tiposEmbarcacao as $key => $tipoEmbarcacao): ?>
                                <option value="<?= $tipoEmbarcacao['tte_id']; ?>"><?= $tipoEmbarcacao['tte_tipoembarcacao']; ?></option>
                                    <?php endforeach; ?>
                        </select>
                    </div>

                </fieldset>
                <br>
                <fieldset class="noEditable" id="itemEmbarcacoesRows"><legend>Embarcações listadas:</legend>
                    <!--Area para inserir os itens-->
                </fieldset>
            </fieldset>            
            <br>

            <div id="Submit">
                <a href="<?= $this->url(array("controller" => "pescador", "action" => "index"), null, true) ?>" id="botao-ancora">Voltar</a>
                <input type="submit" value="Atualizar" />
            </div>



        </form>
    </body>
</html>