
<h2>Perfil Social->Pescador</h2>
<h3>Novo</h3>
<a href="<?=$this->url(array("controller"=>"pescador","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>

<form  id="cadastro-usuario" action="<?=$this->url(array("controller"=>"pescador","action"=>"criar"),null,true)?>" method="post">
     <fieldset id="Social">
        <input type="hidden" name="idPescador" value="<?=$this->pescador['TP_ID']?>" />
        <input type="hidden" name="idEndereco" value="<?=$this->pescador['TE_ID']?>" />
        <div id="esquerda">
            <div id="form-dir">
                <label for="nome">Nome</label><br/>
                <input type="text" name="nome" id="nome" placeholder="Nome" value="<?=$this->pescador['TP_Nome']?>"/><br/>
            </div>
            <div id="form-dir">
                <label for="sexo">Sexo</label><br/>
                <select name="sexo" id="selec-form" >
                    <option value="M">Masculino</option>
                    <option value="F">Feminino</option>
                </select>            
            </div> 
            
            <div id="form-dir">
                <label for="matricula">Matricula</label><br/>
                <input type="text" name="matricula" id="matricula" placeholder="Matricula" value="<?=$this->pescador['TP_Matricula']?>"/>
            </div>
               
            <div id="form-dir">
                <label for="apelido">Apelido</label><br/>
                <input type="text" name="apelido" id="apelido" placeholder="Apelido" value="<?=$this->pescador['TP_Apelido']?>"/>
            </div>
     
            <div id="form-dir">
                <label for="filiacaoPai">Nome de Pai</label><br/>
                <input type="text" name="filiacaoPai" id="filiacaoPai" placeholder="Nome de Pai" value="<?=$this->pescador['TP_FiliacaoPai']?>"/>
            </div>
            
            <div id="form-dir">
                <label for="filiacaoMae">Nome da Mãe</label><br/>
                <input type="text" name="filiacaoMae" id="filiacaoMae" placeholder="Nome da Mãe" value="<?=$this->pescador['TP_FiliacaoMae']?>"/>
            </div>

            <div id="form-dir">
                <label for="rg">RG</label><br/>
                <input type="text" name="rg" id="rg" placeholder="RG" value="<?=$this->pescador['TP_RG']?>"/>
            </div>

            <div id="form-dir">
                <label for="cpf">CPF</label><br/>
                <input type="text" name="cpf" id="cpf" placeholder="CPF" value="<?=$this->pescador['TP_CPF']?>"/>
            </div>

            <div id="form-dir">
                <label for="telefoneResidencial">Tel. Residencial</label><br/>
                <input type="text" name="telefoneResidencial" id="telefoneResidencial" id="telefone" placeholder="Tel. Residencial"/>
            </div>

            <div id="form-dir">
                <label for="telefoneCelular">Tel. Celular</label><br/>
                <input type="text" name="telefoneCelular" id="telefoneCelular" id="telefone" placeholder="Tel. Celular"/>
            </div>
            
            <div id="form-dir">
                <label for="dataNasc">Data Nascimento</label><br/>
                <input type="text" name="dataNasc" id="data_Nasc" placeholder="Data Nascimento" value="<?=$this->pescador['TP_DataNasc']?>"/>
            </div>
            
            <div id="form-dir">
                <label for="municipioNat">Município (Naturalidade)</label><br/>
                <select name="municipioNat" id="municipioNat">
                    <?php foreach ($this->municipios as $key => $municipio): ?>
                    <option value="<?= $municipio['TMun_ID']; ?>"><?= $municipio['TMun_Municipio']; ?></option>
                    <?php endforeach; ?>
                </select>            
            </div>
            
            <div id="form-dir">
                <label for="ctps">CTPS</label><br/>
                <input type="text" name="ctps" id="ctps" placeholder="CTPS" value="<?=$this->pescador['TP_CTPS']?>"/>
            </div>

            <div id="form-dir">
                <label for="artePesca" id="pure-checkbox">Arte de Pesca</label><br/>                
                <select name="artePesca" id="artePesca">
                    <?php foreach ($this->artesPesca as $key => $artePesca): ?>
                    <option value="<?= $artePesca['TAP_ID']; ?>"><?= $artePesca['TAP_ArtePesca']; ?></option>
                    <?php endforeach; ?>
                </select>           
            </div>
            
            <div id="form-dir">
                <label for="tipoEmbarcacao" id="pure-checkbox">Tipo de Embarcação</label><br/>
                <select name="tipoEmbarcacao" id="tipoEmbarcacao">
                    <?php foreach ($this->tiposEmbarcacao as $key => $tipoEmbarcacao): ?>
                    <option value="<?= $tipoEmbarcacao['TTE_ID']; ?>"><?= $tipoEmbarcacao['TTE_TipoEmbarcacao']; ?></option>
                    <?php endforeach; ?>
                </select>           
            </div>
            
            <div id="form-dir">
                <label for="porteEmbarcacao" id="pure-checkbox">Porte da Embarcação</label><br/>             
                <select name="porteEmbarcacao" id="porteEmbarcacao">
                    <?php foreach ($this->portesEmbarcacao as $key => $porteEmbarcacao): ?>
                    <option value="<?= $porteEmbarcacao['TPE_ID']; ?>"><?= $porteEmbarcacao['TPE_Porte']; ?></option>
                    <?php endforeach; ?>
                </select>           
            </div>
            
            
        </div>

        <div id="direita">
                <div id="form-dir">
                <label for="logradouro">Logradouro</label><br/>
                <input type="text" name="logradouro" id="logradouro" placeholder="Logradouro" value="<?=$this->pescador['TE_Logradouro']?>"/>
            </div>

            <div id="form-dir">
                <label for="numero">Número</label><br/>
                <input type="text" name="numero" id="numero" placeholder="Número" value="<?=$this->pescador['TE_Numero']?>"/>
            </div>

            <div id="form-dir">
                <label for="bairro">Bairro</label><br/>
                <input type="text" name="bairro" id="bairro" placeholder="Bairro" />
            </div>

            <div id="form-dir">
                <label for="municipio">Município</label><br/>
                <select name="municipio" id="municipio">
                    <?php foreach ($this->municipios as $key => $municipio): ?>
                    <option value="<?= $municipio['TMun_ID']; ?>"><?= $municipio['TMun_Municipio']; ?></option>
                    <?php endforeach; ?>
                </select>            
            </div>

            <div id="form-dir">
                <label for="estado">Estado</label><br/>
                <select name="estado" id="estado">
                    <?php foreach ($this->estados as $estado): ?>
                    <option value="<?= $estado; ?>" <?=($estado == "BA") ? 'selected="selected"' : '';?>><?= $estado; ?></option>
                    <?php endforeach; ?>
                </select>            
            </div>

            <div id="form-dir">
                <label for="cep">CEP</label><br/>
                <input type="text" name="cep" id="cep" placeholder="CEP" />
            </div>

            <div id="form-dir">
                <label for="complemento">Complemento</label><br/>
                <input type="text" name="complemento" id="complemento" placeholder="Complemento" />
            </div>
            
            <div id="form-dir">
                <label for="colonia" id="pure-checkbox">Colônia</label><br/>                
                <select name="colonia" id="colonia">
                    <?php foreach ($this->colonias as $key => $colonia): ?>
                    <option value="<?= $colonia['TC_ID']; ?>"><?= $colonia['TC_Nome']; ?></option>
                    <?php endforeach; ?>
                </select>           
            </div>
            
            <div id="form-dir">
                <label for="pis">PIS</label><br/>
                <input type="text" name="pis" id="pis" placeholder="PIS" />
            </div>
            
            <div id="form-dir">
                <label for="inss">INSS</label><br/>
                <input type="text" name="inss" id="inss" placeholder="INSS" />
            </div>
            
            <div id="form-dir">
                <label for="nit_cei">NIT CEI</label><br/>
                <input type="text" name="nit_cei" id="nit_cei" placeholder="NIT CEI" />
            </div>
            
            <div id="form-dir">
                <label for="cma">CMA</label><br/>
                <input type="text" name="cma" id="cma" placeholder="CMA" />
            </div>
            
            <div id="form-dir">
                <label for="rgb_maa_ibama">RGB MAA IBAMA</label><br/>
                <input type="text" name="rgb_maa_ibama" id="rgb_maa_ibama" placeholder="RGB MAA IBAMA" />
            </div>
            
            <div id="form-dir">
                <label for="cir_cap_porto">CIR Cap. Porto</label><br/>
                <input type="text" name="cir_cap_porto" id="cir_cap_porto" placeholder="CIR Cap. Portos"/>
            </div>
            
            <div id="form-dir">
                <label for="areaPesca" id="pure-checkbox">Area de Pesca</label><br/>                
                <select name="areaPesca" id="areaPesca">
                    <?php foreach ($this->areasPesca as $key => $areaPesca): ?>
                    <option value="<?= $areaPesca['TAreaP_ID']; ?>"><?= $areaPesca['TAreaP_AreaPesca']; ?></option>
                    <?php endforeach; ?>
                </select>           
            </div>
            
            <div id="form-dir">
                <label for="especie" id="pure-checkbox">Especie Capturada</label><br/>                
                <select name="especie" id="especie">
                    <?php foreach ($this->especies as $key => $especie): ?>
                    <option value="<?= $especie['TEC_ID']; ?>"><?= $especie['ESP_Nome']; ?></option>
                    <?php endforeach; ?>
                </select>           
            </div>
            
        </div>
        
    </fieldset>
    <div id="Submit">
           <input type="submit" value="Enviar" />
    </div>
</form>