<h2>Visualizar Pescador</h2>

<a href="<?=$this->url(array("controller"=>"pescador","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>

<table>
    <tr>
        <th>Nome</th>
        <th>Sexo</th>
        <th>Matricula</th>
        <th>Apelido</th>
        <th>Nome do Pai</th>
        <th>Nome da Mãe</th>
        <th>Data de Nascimento</th>
        <th>RG</th>
        <th>CPF</th>  
        <th>Logradouro</th>
        <th>Número</th>
        <th>Bairro</th>
        <th>Cidade</th>
        <th>Estado</th>
        <th>CEP</th>
        <th>Complemento</th> 
    </tr>
    <tr>
        <td><?= $this->pescador['TP_Nome'] ?></td>
        <td><?= $this->pescador['TP_Sexo'] ?></td>
        <td><?= $this->pescador['TP_Matricula'] ?></td>
        <td><?= $this->pescador['TP_Apelido'] ?></td>
        <td><?= $this->pescador['TP_FiliacaoPai'] ?></td>
        <td><?= $this->pescador['TP_FiliacaoMae'] ?></td>
        <td><?= $this->pescador['TP_DataNasc'] ?></td>
        <td><?= $this->pescador['TP_RG'] ?></td>
        <td><?= $this->pescador['TP_CPF'] ?></td>
        <td><?= $this->pescador['TE_Logradouro'] ?></td>
        <td><?= $this->pescador['TE_Numero'] ?></td>
        <td><?= $this->pescador['TE_Bairro'] ?></td>
        <td><?= $this->pescador['TMun_Municipio'] ?></td>
        <td><?= $this->pescador['TUF_Sigla'] ?></td>
        <td><?= $this->pescador['TE_CEP'] ?></td>
        <td><?= $this->pescador['TE_Comp'] ?></td>
    </tr>
</table>