<h2>Desembarque--Vento</h2>

<form>
    <fieldset id="Desembarque">
        <legend ><h3>Vento:</h3></legend>
        <label for="id">ID:</label>
        <input type="text" name="id_vento" id="id_vento"/><br />
        <label for="tipo">Potencia do Vento:</label>
        <input type="text" id="potencia_vento" name="potencia_vento"/><br />
        <input type="submit" value="enviar"/>
    </fieldset>
</form>