<?php
$this->headScript()->appendFile('/js/jquery.maskedinput.min.js');
$this->headScript()->appendFile('/js/mascaras.js');
?>

<h2>Perfil Social->Colônia</h2>
<h3>Editar</h3>

<a href="<?=$this->url(array("controller"=>"colonia","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>
<form action="<?=$this->url(array("controller"=>"colonia","action"=>"atualizar"),null,true)?>" method="post">
    <fieldset id="Social">

        <input type="hidden" name="idColonia" value="<?=$this->colonia['TC_ID']?>" />
        <input type="hidden" name="idEndereco" value="<?=$this->colonia['TE_ID']?>" />
        <div id="form-esq">
            <label>Colônia: </label> <br/>
            <input type="text" name="nome" placeholder="Colônia" value="<?=$this->colonia['TC_Nome']?>"/><br/>
        </div>
        <div id="form-esq">
            <label>Comunidade: </label><br/>
            <select name="comunidade">
                <?php foreach ($this->comunidades as $key => $comunidade): ?>
                <option value="<?= $comunidade['TCOM_ID']; ?>" <?=($comunidade['TCOM_ID'] == $this->colonia['TCOM_ID']) ? 'selected="selected"' : '';?>><?= $comunidade['TCOM_Nome']; ?></option>
                <?php endforeach; ?>
            </select>
        </div>

        <div id="form-esq">
            <label>Especificidade: </label> <br/>
            <input type="text" name="especificidade" placeholder="Especificidade" value="<?=$this->colonia['TC_Especificidade']?>"/> <br/>
        </div>
        <div id="form-esq">
            <label>Logradouro: </label> <br/> 
            <input type="text" name="logradouro" placeholder="Logradouro" value="<?=$this->colonia['TE_Logradouro'];?>" /><br />
        </div>

        <div id="form-esq">
            <label>Número: </label> <br/>
            <input type="text" name="numero" placeholder="Número" value="<?=$this->colonia['TE_Numero'];?>" /><br />
        </div>

        <div id="form-esq">
            <label>Bairro: </label></br> 
            <input type="text" name="bairro" placeholder="Bairro" value="<?=$this->colonia['TE_Bairro'];?>" /><br/>
        </div>
        
        <div id="form-esq">    
            <label>Municipio:</label><br/>
                <select name="municipio">
                    <?php foreach ($this->municipios as $key => $municipio): ?>
                    <option value="<?= $municipio['TMun_ID']; ?>"><?= $municipio['TMun_Municipio']; ?></option>
                    <?php endforeach; ?>
                </select> 
        </div>

        <div id="form-esq">
            <label>Estado: </label><br/>
            <select name="estado">
                <?php foreach ($this->estados as $estado): ?>
                <option value="<?= $estado; ?>" <?=($estado == $this->colonia['TUF_Sigla']) ? 'selected="selected"' : '';?>><?= $estado; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        

        <div id="form-esq">
            <label>CEP: </label> <br/>
            <input type="text" name="cep" placeholder="CEP" id="cep" value="<?=$this->colonia['TE_CEP'];?>" /> <br />
        </div>
        
        <div id="form-esq">           
            <label>Complemento: </label> <br/>
            <input type="text" name="complemento" placeholder="Complemento" value="<?=$this->colonia['TE_Comp'];?>" /> <br />
        </div>    
        <div id="Submit">
            <input type="submit" value="Atualizar" />
        </div>
        
    </fieldset>

    </form>