

<h2>Perfil Social-> Colônias</h2>

<a href="<?=$this->url(array("controller"=>"colonia","action"=>"novo"),null,true)?>" id="botao-ancora">Novo</a>
<fieldset id="Social"></fieldset>
<table>
    <tr>
        <th>Colonia</th>
        <th>CEP</th>
        <th>Complemento</th> 
    </tr>
    
    <?php
    foreach ($this->dados as $key => $colonia):
    ?>
    <tr>
        <td><?= $colonia['TC_Nome'] ?></td>
        <td><?= $colonia['TE_CEP'] ?></td>
        <td><?= $colonia['TE_Comp'] ?></td>
        <td class="td-botao">
            <a href="<?=$this->url(array("controller"=>"colonia","action"=>"visualizar", "id" => $colonia['TC_ID']),null,true)?>">
                <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Visualizar"><span class="ui-icon ui-icon-search"></span></li>
                </ul>
            </a>
        </td>
        <td class="td-botao">
            <a href="<?=$this->url(array("controller"=>"colonia","action"=>"editar", "id" => $colonia['TC_ID']),null,true)?>">
                <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                </ul>
            </a>
        </td>
        <td class="td-botao">
            <a href="<?=$this->url(array("controller"=>"colonia","action"=>"excluir", "id" => $colonia['TC_ID']),null,true)?>">
                <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-trash"></span></li>
                </ul>
            </a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>