<h2>Filogenia->Família</h2>
<h3>Editar</h3>
<a href="<?=$this->url(array("controller"=>"familia","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>

<form id="familia" action="<?=$this->url(array("controller"=>"familia","action"=>"atualizar"),null,true)?>" method="post">
      <fieldset id="Filogenia">
         <div id="esquerda"> 
          <div id="form-esq">
              <label for="id">ID:</label>
              <input type="text" name="id_familia" id="id_familia" value="<?=$this->familia["FAM_ID"]?>"/><br />
          </div>
          <div id="form-esq">
              <label for="tipo">Nome:</label>
              <input type="text" id="nome_familia" name="nome_familia"value="<?=$this->familia["FAM_Nome"]?>"/><br/>
          </div>
          <div id="form-esq">
              <label for="tipo">Tipo:</label>
              <input type="text" id="tipo_familia" name="tipo_familia"value="<?=$this->familia["FAM_Tipo"]?>"/><br />
          </div>
          <div id="form-esq">
              <label for="tipo">Característica:</label>
              <input type="text" id="caracteristica_familia" name="caracteristica_familia"value="<?=$this->familia["FAM_Caracteristica"]?>"/><br />
          </div>
          <div id="form-esq">
              <label for="tipo">Ordem:</label>
              <select name="select_ordem_familia" id="familia_ordem">
              <?php
                    foreach ($this->dados as $key => $ordem):
               ?>
              
		<option nome="ordem_familia" value="<?=$ordem['ORD_ID']?>"><?= $ordem['ORD_Nome']?></option>
              
              <?php
                endforeach;
              ?>
                </select><br/>
            </div>    
            <div id="Submit">  
               <input type="submit" value="enviar"/>
            </div>
         </div>    
      </fieldset>              
</form>