<h2>Filogenia--Família</h2>

<a href="<?=$this->url(array("controller"=>"familia","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>

<form id="familia">
      <fieldset id="Filogenia">
              <legend><h3>Família:</h3></legend>
              <label for="id">ID:</label>
              <input type="text" name="id_familia" id="id_familia"/><br />
              <label for="tipo">Nome:</label>
              <input type="text" id="nome_familia" name="nome_familia"/><br />
              <label for="tipo">Ordem Filogenética:</label>
              <input type="text" id="ordem_filogenetica" name="ordem_filogenetica"/><br />
              <label for="tipo">Tipo:</label>
              <input type="text" id="tipo_familia" name="tipo_familia"/><br />
              <label for="tipo">Característica:</label>
              <input type="text" id="caracteristica_familia" name="caracteristica_familia"/><br />
              <label for="tipo">Ordem:</label>
              <input type="text" id="ordem_familia" name="ordem_familia"/><br />
              <input type="submit" value="enviar"/>
      </fieldset>              
</form>