<h2>Filogenia->Família</h2>
<h3>Novo</h3>
<a href="<?=$this->url(array("controller"=>"familia","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>

<form id="familia" action="<?=$this->url(array("controller"=>"familia","action"=>"criar"),null,true)?>">
      <fieldset id="Filogenia">
          <div id="esquerda">
          <div id="form-esq">
              <label for="id">ID:</label>
              <input type="text" name="id_familia" placeholder="ID" id="id_familia" /><br />
          </div>
          <div id="form-esq">
              <label for="tipo">Nome:</label>
              <input type="text" id="nome_familia" placeholder="Nome" name="nome_familia"/><br/>
          </div>
          <div id="form-esq">
              <label for="tipo">Tipo:</label>
              <input type="text" id="tipo_familia" placeholder="Tipo" name="tipo_familia"/><br />
          </div>
          <div id="form-esq">
              <label for="tipo">Característica:</label>
              <input type="text" id="caracteristica_familia" placeholder="Característica" name="caracteristica_familia"/><br />
          </div>
          <div id="form-esq">
              <label for="tipo">Ordem:</label>
              <select name="select_ordem_familia" id="familia_ordem">
              <?php
                    foreach ($this->dados as $key => $ordem):
               ?>
              
		<option nome="ordem_familia" value="<?=$ordem['ORD_ID']?>"><?= $ordem['ORD_Nome']?></option>
              
              <?php
                endforeach;
              ?>
                </select><br/>
            </div>    
            <div id="Submit">  
               <input type="submit" value="enviar"/>
            </div>
          </div>
      </fieldset>              
</form>