<?=$this->doctype('XHTML1_TRANSITIONAL')?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-br">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <base href="http://<?=$_SERVER['HTTP_HOST'] . $this->baseUrl()?>/" />
        <?php
            $this->headLink()->prependStylesheet('/css/estilo-admin.css');
            $this->headLink()->appendStylesheet('/css/smoothness/jquery-ui-1.10.3.custom.min.css');
            $this->headScript()->prependFile('/js/jquery-1.10.2.min.js'); 
            $this->headScript()->appendFile('/js/jquery-ui-1.10.3.custom.min.js');
            $this->headScript()->appendFile('/js/jquery-ui-functions.js');
            $this->headScript()->appendFile('/js/funcoesJquery.js');
            
            echo $this->headLink() . "\n";
            echo $this->headScript() . "\n";
        ?>
    </head>
    <body>
        <div id="geral">
            <div id="topo">
            </div>
            <div id="menu">
                <ul>
                    <li><a href="<?=$this->url(array("controller"=>"index","action"=>"index"),null,true)?>">Página Inicial</a></li>
                    <li><a href="<?=$this->url(array("controller"=>"noticias","action"=>"index"),null,true)?>">Últimas Notícias</a></li>
                    <li><a href="<?=$this->url(array("controller"=>"equipe","action"=>"index"),null,true)?>">Equipe</a></li>
                    <li><a href="<?=$this->url(array("controller"=>"contato","action"=>"index"),null,true)?>">Contato</a></li>
                </ul>
                <div id="login">
                    <p>
                        Olá, Elenildo João |
                        <a href="<?=$this->url(array("controller"=>"autenticacao","action"=>"logout"),null,true)?>">Sair</a>
                    </p>
                </div>
            </div>
            <div id="conteudo-geral">
                <div id="menu-lateral">
                    <ul>
                        <li><a id="for-Social" href="#">Perfil Social</a></li>
                        <ul id="Social">
                            <li><a href="<?=$this->url(array("controller"=>"pescador","action"=>"index"),null,true)?>">Pescadores</a></li>
                            <li><a href="<?=$this->url(array("controller"=>"arte-pesca","action"=>"index"),null,true)?>">Artes de pesca</a></li>
                            <li><a href="<?=$this->url(array("controller"=>"area-pesca","action"=>"index"),null,true)?>">Áreas de pesca</a></li>
                            <li><a href="<?=$this->url(array("controller"=>"especie","action"=>"index"),null,true)?>">Especies</a></li>     
                            <li><a href="<?=$this->url(array("controller"=>"tipo-embarcacao","action"=>"index"),null,true)?>">Tipos de embarcações</a></li>
                            <li><a href="<?=$this->url(array("controller"=>"comunidade","action"=>"index"),null,true)?>">Comunidades</a></li>
                            <li><a href="<?=$this->url(array("controller"=>"colonia","action"=>"index"),null,true)?>">Colônias</a></li>
                            <li><a href="<?=$this->url(array("controller"=>"municipio","action"=>"index"),null,true)?>">Municipios</a></li>
                        </ul>
                        <li><a id="for-Dsbq" href="#">Controle de Desembarque</a></li>
                        <ul id="Dsbq"> 
                            <li><a href="">Ficha Diária</a></li>
                            <li><a id="for-Filo" href="#">Filogenia</a></li>
                            <ul id="Filo">
                            <li><a href="<?=$this->url(array("controller"=>"grupo","action"=>"index"),null,true)?>">Grupo</a></li>
                            <li><a href="<?=$this->url(array("controller"=>"ordem","action"=>"index"),null,true)?>">Ordem</a></li>
                            <li><a href="<?=$this->url(array("controller"=>"familia","action"=>"index"),null,true)?>">Família</a></li>
                            <li><a href="<?=$this->url(array("controller"=>"genero","action"=>"index"),null,true)?>">Genero</a></li>
                            <li><a href="<?=$this->url(array("controller"=>"","action"=>"index"),null,true)?>">Espécie</a></li>
                            </ul>
                            <li><a href="<?=$this->url(array("controller"=>"mare","action"=>"index"),null,true)?>">Maré</a></li>
                            <li><a href="<?=$this->url(array("controller"=>"tempo","action"=>"index"),null,true)?>">Tempo</a></li>
                            <li><a href="<?=$this->url(array("controller"=>"vento","action"=>"index"),null,true)?>">Vento</a></li>
                            <li><a href="<?=$this->url(array("controller"=>"porto","action"=>"index"),null,true)?>">Porto</a></li>
                            <li><a href="<?=$this->url(array("controller"=>"pesqueiro","action"=>"index"),null,true)?>">Pesqueiro</a></li>
                        </ul>
                        <li><a href="#">Tráfego de Embarcações</a></li>
                        <li><a href="#">Notícias</a></li>
                    </ul>
                    <div id="admin">
                        <ul>
                            <li><a  href="#">Administrador</a></li>
                            <li><a href="<?=$this->url(array("controller"=>"usuarios","action"=>"index"),null,true)?>">Usuários</a></li>
                        </ul>
                        
                    </div>
                </div>
                
                <div id="menu-lateral">
                    <ul>
                        
                        
                    </ul>
                </div>
                <div id="conteudo">
                    <?php echo $this->layout()->content; ?>
                </div>

                <div id="rodape">
                    <div id="parceiros">
                        <ul>
                            <li><a href="http://nbcgib.uesc.br/nbcgib" target="_blank"><img class="imgparc" src="img/nbcgib.png" alt="NBCGIB" title="NBCGIB" /></a></li>
                            <li><a href="#" target="_blank"><img class="imgparc" src="img/iSus.png" alt="iSUS" title="iSUS" /></a></li>
                            <li><a href="http://www.bamin.com.br/" target="_blank"><img class="imgparc" src="img/bamin.jpg" alt="Bamin" title="Bamin" /></a></li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </body>
</html>