<h2>Filogenia--Grupo</h2>

<a href="<?=$this->url(array("controller"=>"grupo","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>

<form action="<?=$this->url(array("controller"=>"grupo","action"=>"atualizar"),null,true)?>" method="post"> 
    <fieldset id="Filogenia">
              <legend><h3>Grupo:</h3></legend>
              <label for="id">ID:</label>
              <input type="text" name="id_grupo" id="id_grupo" value="<?=$this->grupo["GRP_ID"]?>"/><br />
              <label for="tipo">Nome:</label>
              <input type="text" id="nome_grupo" name="nome_grupo" value="<?=$this->grupo["GRP_Nome"]?>"/><br />
              <input type="submit" value="enviar"/>
    </fieldset>
</form>