<div id="titulos">
    <h2>Filogenia->Ordem</h2>
    <h3>Editar</h3>
</div>

 <form action="<?=$this->url(array("controller"=>"ordem","action"=>"atualizar"),null,true)?>" method="post">
    <fieldset id="Filogenia">
      <div id="esquerda">  
        <div id="form-esq">
              <label for="id">ID:</label>
              <input type="text" name="id_ordem" value="<?=$this->ordem['ord_id']?>"/><br />
        </div>
        <div id="form-esq"> 
              <label for="tipo">Nome:</label>
              <input type="text" name="nome_ordem" value="<?=$this->ordem['ord_nome']?>"/><br />
        </div>
        <div id="form-esq">   
              <label for="tipo">Característica:</label>
              <input type="text" name="caracteristica_ordem" value="<?=$this->ordem['ord_caracteristica']?>"/><br />
        </div>
        <div id="form-esq">    
              <label for="tipo">Grupo:</label>
              <select name="select_grupo_ordem" id="grupo_ordem">
              <?php
                    foreach ($this->dados as $key => $grupo):
               ?>
              
                  <option nome="grupo_ordem" value="<?=$grupo['grp_id']?>"><?=$grupo['grp_nome']?></option>
              
              <?php
                endforeach;
              ?>
                </select><br/>
        </div>
        <div id="Submit">
            <a href="<?=$this->url(array("controller"=>"usuarios","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a> 
            <input type="submit" value="Atualizar" />
        </div>
      </div>        
    </fieldset>
              
</form>