<h2>Filogenia--Ordem</h2

<a href="<?=$this->url(array("controller"=>"ordem","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>

<form>
    <fieldset id="Filogenia">
              <legend><h3>Ordem:</h3></legend>
              <label for="id">ID:</label>
              <input type="text" name="id_ordem" id="id_ordem"/><br />
              <label for="tipo">Nome:</label>
              <input type="text" id="nome_ordem" name="nome_ordem"/><br />
              <label for="tipo">Característica:</label>
              <input type="text" id="caracteristica_ordem" name="caracteristica_ordem"/><br />
              <label for="tipo">Grupo:</label>
              <input type="text" id="grupo_ordem" name="grupo_ordem"/><br />
              <input type="submit" value="Enviar"/>
    </fieldset>
              
</form>