<h2>Novo Municipio</h2>

<a href="<?=$this->url(array("controller"=>"municipio","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>

<form action="<?=$this->url(array("controller"=>"municipio","action"=>"criar"),null,true)?>" method="post">
    <label>Municipio: <input type="text" name="municipio" /></label> <br />
    <label>Estado: 
        <select name="estado">
            <?php foreach ($this->estados as $estado): ?>
            <option value="<?= $estado; ?>" <?=($estado == "BA") ? 'selected="selected"' : '';?>><?= $estado; ?></option>
            <?php endforeach; ?>
        </select>
    </label> <br />
    <input type="submit" value="Cadastrar" />
</form>