<div id="titulos">
    <h2>Desembarque->Pesca com Vara</h2>
    <h3>Entrevista</h3>
</div>

<div id="esquerda-entrevista">
    <form action="<?=$this->url(array("controller"=>"vara-pesca","action"=>"criar"),null,true)?>">
        <fieldset id="Entrevista">
            <div id="esquerda">
                <div id="form-esq">
                    <label>ID da ficha diária:</label>
                    <input type="text" name="id_fichaDiaria" placeholder="ID" disabled="true" value="<?= $this->fichaDiaria['fd_id'] ?>" /><br />
                </div>
                <div id="form-esq">
                    <label>ID monitoramento:</label>
                    <input type="text" name="id_monitoramento" placeholder="ID"  value="<?= $this->monitoramento['mnt_id'] ?>" /><br />
                </div>
                <div id="form-esq">
                    <label for="tipo">ID Entrevista:</label>
                    <input type="text" placeholder = "ID" name="id_entrevista" disabled="true"/><br />
                </div>
            </div>
            <br/>
            <div id="esquerda">
                <legend><h4>Embarcação:</h4></legend>
                <div id="form-esq">
                    <label>Utilizou Barco?</label>
                    <input type="checkbox"  name="embarcada"/><br />
                </div>
                <div id="form-esq">
                    <label>Motor?</label>
                    <input type="checkbox"  name="motor"/><br />
                </div>
                <div id="form-esq">
                    <label>Barco:</label>
                    <select name="nomeBarco" required/>
                    <option value="" selected></option>
                    <?php
                    foreach ($this->barcos as $key => $barco):
                        ?>
                        <option value="<?= $barco['bar_id'] ?>"><?= $barco['bar_nome'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>

                </div>
                <div id="form-esq">
                    <label>Tipo de Barco:</label>
                    <select name="tipoBarco" required>
                    <option value="" selected></option>
                    <?php
                    foreach ($this->tipoEmbarcacoes as $key => $tipoEmbarcacao):
                        ?>
                        <option value="<?= $tipoEmbarcacao['tte_id'] ?>"><?= $tipoEmbarcacao['tte_tipoembarcacao'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>

                </div>

            </div>
            <div id="direita-entrevista">
                <div id="form-esq">    
                    <label>Pescador Entrevistado:</label>
                    <select name="pescadorEntrevistado" required>
                    <option value="" selected></option>
                    <?php
                    foreach ($this->pescadores as $key => $pescador):
                        ?>
                        <option value="<?= $pescador['tp_id'] ?>"><?= $pescador['tp_nome'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select><br />
                </div>
                <div id="form-esq">
                    <label>Quant. de Pescadores:</label>
                    <input type="text"  name="numPescadores" min="1" placeholder="Quantidade de Pescadores " required/><br />
                </div>
            </div>
            <div id="esquerda">
                <legend><h4>Saída e Volta:</h4></legend>
                <div id="form-esq">

                    <label>Data:</label>
                    <input type="date" name="dataSaida" min="2013-11-01" required/>
                </div>
                <div id="form-esq">
                    <label>Horas:</label>
                    <input type="time" name="horaSaida" required/>
                </div>
            </div>
            <div id="direita-entrevista">
                <div id="form-esq">
                    <label>Data:</label>
                    <input type="date" name="dataVolta" min="2013-11-01" required/>
                </div>
                <div id="form-esq">
                    <label>Horas:</label>
                    <input type="time" name="horaVolta" required/>
                </div>
            </div>
            <br/>
            <div id="esquerda">
                <div id="form-esq">
                    <label>Tempo Gasto:</label>
                    <input type="time" name="tempoGasto" required/>
                </div>
            </div>
            <br/>
            <div id="esquerda">
                <div id="form-esq">
                    <legend><h4>Gastos:</h4></legend>
                    <label>Diesel(L):</label>
                    <input type="text"  name="diesel" placeholder="Diesel"/>
                </div>
                <div id="form-dir">    
                    <label>Óleo(L):</label>
                    <input type="text"  name="oleo" placeholder="Óleo"/><br />
                </div>
            </div>
            <div id="direita-entrevista">
                <div id="form-dir">    
                    <label>Alimento($):</label>
                    <input type="text"  name="alimento" placeholder="Alimento"/><br />
                </div>
                <div id="form-dir">    
                    <label>Gelo($):</label>
                    <input type="text"  name="gelo" placeholder="Gelo"/><br />
                </div>
            </div>
            <br/>
            <div id="esquerda">
                <div id="form-esq">
                    <legend><h4>Maré:</h4></legend>
                    <label>Tipo:</label>
                    <select name="mare" required>
                        <option value="" selected></option>
                        <?php
                        foreach ($this->mare as $key => $mare):
                            ?>
                            <option value="<?= $mare['mre_id'] ?>"><?= $mare['mre_tipo'] ?></option>
                            <?php
                        endforeach;
                        ?>
                    </select>
                </div>
                <div id="form-dir">    
                    <label>Maré Viva?</label>
                    <input type="checkbox" name="mareviva"> 
                </div>
            </div><br/>
            <div id="esquerda">
                <div id="form-esq">
                    <legend><h4>Esforço:</h4></legend>
                    <label>Número de Linhas:</label>
                    <input type="text" name="numLinhas" placeholder="Linhas"/>
                </div>
                <div id="form-dir">    
                    <label> Anzóis p/ Linha:</label>
                    <input type="text" name="numAnzois" placeholder="Anzóis P/ Linha"/><br />
                </div>
            </div>
            <div id="direita-entrevista">
                <div id="form-esq">    
                    <label>Isca:</label>
                    <select name="isca" required>
                    <option value="" selected></option>
                    <?php
                    foreach ($this->iscas as $key => $isca):
                        ?>
                        <option value="<?= $isca['isc_id'] ?>"><?= $isca['isc_tipo'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                    <br />
                </div>
            </div><br/>
            <div id="esquerda">
                <legend><h4>Outros dados:</h4></legend>
                <div id="form-esq">    
                    <label>Destino do Pescado:</label>
                    <select name="destinoPescado" required>
                        <option value="" selected></option>
                    <?php
                    foreach ($this->destinos as $key => $destino):
                        ?>
                        <option value="<?= $destino['dp_id'] ?>"><?= $destino['dp_destino'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>
                </div>
                <div id="form-esq">
                    <label for="tipo">Subamostra?:</label>
                    <input type="checkbox" name="subamostra" /><br />
                </div>
                <div id="form-esq">
                    <label for="tipo">Observacao:</label>
                    <input type="text" name="observacao" placeholder="Observação" /><br />
                </div>
                
                <div id="Submit">
                    <input type="submit" value="Salvar Entrevista"/>
                </div>
            </div>
        </fieldset>
    </form>
</div>