<h2>Desembarque->Pesqueiro</h2>
<h3>Editar</h3>

<a href="<?=$this->url(array("controller"=>"pesqueiro","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>

<form action="<?=$this->url(array("controller"=>"especie","action"=>"atualizar"),null,true)?>" method="post">
    <fieldset id="Desembarque">
         <div id="form-esq">
              <label for="id">ID do Pesqueiro:</label><br/>
              <input type="text" name="id_Pesqueiro" id="id_pesqueiro"/><br />
         </div>
         <div id="form-esq">     
              <label for="tipo">Nome:</label><br/>
              <input type="text" id="nome_pesqueiro" name="nome_pesqueiro"/><br />
         </div>     
         <div id="form-esq">     
              <label for="tipo">Local:</label><br/>
              <input type="text" id="nome_local" name="local_pesqueiro" /><br />
         </div>     
         <div id="form-esq">     
              <label>Municipio: </label><br/>
              <select name="municipio">
                <?php foreach ($this->municipios as $key => $municipio): ?>
                <option value="<?= $municipio['TMun_ID']; ?>"><?= $municipio['TMun_Municipio']; ?></option>
                <?php endforeach; ?>
              </select><br/>
         </div> 
         <div id="Submit">
              <input type="submit" value="enviar"/>
         </div>
    </fieldset>
                
</form>