<h2>Desembarque->Pesqueiro</h2>

<a href="<?=$this->url(array("controller"=>"pesqueiro","action"=>"novo"),null,true)?>" id="botao-ancora">Novo</a>
<fieldset id="Desembarque"></fieldset>
<table>
    <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Municipio</th>
    </tr>
    
    <?php foreach ($this->dados as $key => $pesqueiro): ?>
    <tr>
        <td><?= $pesqueiro['psq_id'] ?></td>
        <td><?= $pesqueiro['psq_nome'] ?></td>
        <td><?= $pesqueiro['tmun_id'] ?></td>
        <td class="td-botao">
            <a href="<?=$this->url(array("controller"=>"pesqueiro","action"=>"visualizar", "id" => $pesqueiro['tp_id']),null,true)?>">
                <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Visualizar"><span class="ui-icon ui-icon-search"></span></li>
                </ul>
            </a>
        </td>
        <td class="td-botao">
            <a href="<?=$this->url(array("controller"=>"pesqueiro","action"=>"editar", "id" => $pesqueiro['tp_id']),null,true)?>">
                <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                </ul>
            </a>
        </td>
        <td class="td-botao">
            <a href="<?=$this->url(array("controller"=>"pesqueiro","action"=>"excluir", "id" => $pesqueiro['tp_id']),null,true)?>">
                <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-trash"></span></li>
                </ul>
            </a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<br/><br/>
<a href="<?=$this->url(array("controller"=>"pesqueiro","action"=>"relatorio"),null,true)?>" id="botao-ancora" target="_blank">Gerar Relatório</a>