<div id="titulos">
    <h2>Desembarque->Pesqueiro</h2>
    <h3>Novo</h3>
</div>



<form action="<?=$this->url(array("controller"=>"especie","action"=>"criar"),null,true)?>" method="post">
    <fieldset id="Desembarque">
        <div id="esquerda">
         <div id="form-esq">
              <label for="id">ID do Pesqueiro:</label>
              <input type="text" name="id_Pesqueiro" id="id_pesqueiro"/><br />
         </div>
         <div id="form-esq">     
              <label for="tipo">Nome:</label>
              <input type="text" id="nome_pesqueiro" name="nome_pesqueiro"/><br />
         </div>     
         <div id="form-esq">     
              <label for="tipo">Local:</label>
              <input type="text" id="nome_local" name="local_pesqueiro" /><br />
         </div>     
         <div id="form-esq">     
              <label>Municipio: </label>
              <select name="municipio">
                <?php foreach ($this->municipios as $key => $municipio): ?>
                <option value="<?= $municipio['TMun_ID']; ?>"><?= $municipio['TMun_Municipio']; ?></option>
                <?php endforeach; ?>
              </select><br/>
         </div>
        
        <div id="Submit">
            <a href="<?=$this->url(array("controller"=>"pesqueiro","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>
            <input type="submit" value="Cadastrar" />
        </div>
            </div>
    </fieldset>
                
</form>