<h2>Desembarque--Pesqueiro</h2>

<form>
    <fieldset id="Desembarque">
              <legend ><h3>Pesqueiro:</h3></legend>
              <label for="id">ID do Pesqueiro:</label>
              <input type="text" name="id_Pesqueiro" id="id_pesqueiro"/><br />
              <label for="tipo">Nome:</label>
              <input type="text" id="nome_pesqueiro" name="nome_pesqueiro"/><br />
              <label for="tipo">Local:</label>
              <input type="text" id="nome_local" name="local_pesqueiro" /><br />
              <label for="tipo">Cidade:</label>
              <input type="text" id="cidade_pesqueiro" name="cidade_pesqueiro" /><br />
              <input type="submit" value="enviar"/>
    </fieldset>
                
</form>