UPDATE t_arrastofundo
   SET tp_id_entrevistado=?
 WHERE tp_id_entrevistado=!;
 UPDATE t_calao
   SET tp_id_entrevistado=?
 WHERE tp_id_entrevistado=!;
 UPDATE t_coletamanual
   SET tp_id_entrevistado=?
 WHERE tp_id_entrevistado=!;
 UPDATE t_emalhe
   SET tp_id_entrevistado=?
 WHERE tp_id_entrevistado=!;
 UPDATE t_grosseira
   SET tp_id_entrevistado=?
 WHERE tp_id_entrevistado=!;
 UPDATE t_jerere
   SET tp_id_entrevistado=?
 WHERE tp_id_entrevistado=!;
 UPDATE t_linha
   SET tp_id_entrevistado=?
 WHERE tp_id_entrevistado=!;
 UPDATE t_linhafundo
   SET tp_id_entrevistado=?
 WHERE tp_id_entrevistado=!;
 UPDATE t_manzua
   SET tp_id_entrevistado=?
 WHERE tp_id_entrevistado=!;
 UPDATE t_mergulho
   SET tp_id_entrevistado=?
 WHERE tp_id_entrevistado=!;
UPDATE t_ratoeira
   SET tp_id_entrevistado=?
 WHERE tp_id_entrevistado=!;
 UPDATE t_siripoia
   SET tp_id_entrevistado=?
 WHERE tp_id_entrevistado=!;
 UPDATE t_tarrafa
   SET tp_id_entrevistado=?
 WHERE tp_id_entrevistado=!;
 UPDATE t_varapesca
   SET tp_id_entrevistado=?
 WHERE tp_id_entrevistado=!;

 Delete From t_pescador WHERE tp_id = !;