UPDATE t_arrastofundo
   SET tp_id_entrevistado=651
 WHERE tp_id_entrevistado=1538;
 UPDATE t_calao
   SET tp_id_entrevistado=651
 WHERE tp_id_entrevistado=1538;
 UPDATE t_coletamanual
   SET tp_id_entrevistado=651
 WHERE tp_id_entrevistado=1538;
 UPDATE t_emalhe
   SET tp_id_entrevistado=651
 WHERE tp_id_entrevistado=1538;
 UPDATE t_grosseira
   SET tp_id_entrevistado=651
 WHERE tp_id_entrevistado=1538;
 UPDATE t_jerere
   SET tp_id_entrevistado=651
 WHERE tp_id_entrevistado=1538;
 UPDATE t_linha
   SET tp_id_entrevistado=651
 WHERE tp_id_entrevistado=1538;
 UPDATE t_linhafundo
   SET tp_id_entrevistado=651
 WHERE tp_id_entrevistado=1538;
 UPDATE t_manzua
   SET tp_id_entrevistado=651
 WHERE tp_id_entrevistado=1538;
 UPDATE t_mergulho
   SET tp_id_entrevistado=651
 WHERE tp_id_entrevistado=1538;
UPDATE t_ratoeira
   SET tp_id_entrevistado=651
 WHERE tp_id_entrevistado=1538;
 UPDATE t_siripoia
   SET tp_id_entrevistado=651
 WHERE tp_id_entrevistado=1538;
 UPDATE t_tarrafa
   SET tp_id_entrevistado=651
 WHERE tp_id_entrevistado=1538;
 UPDATE t_varapesca
   SET tp_id_entrevistado=651
 WHERE tp_id_entrevistado=1538;

 Delete From t_pescador WHERE tp_id = 1538;