<h2>Perfil Social->Tipo de Embarcação</h2>
<h3>Editar</h3>

<a href="<?=$this->url(array("controller"=>"tipo-embarcacao","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>

<form id="tipo-embarcacao" action="<?=$this->url(array("controller"=>"tipo-embarcacao","action"=>"atualizar"),null,true)?>" method="post">
    <fieldset id="Social">
    <input type="hidden" name="idTipoEmbarcacao" value="<?=$this->tipoEmbarcacao['TTE_ID']?>" />
    
        <div id="form-esq">
            <label for="tipoEmbarcacao">Tipo de Embarcação</label><br/>
            <input type="text" name="tipoEmbarcacao" id="tipoEmbarcacao" placeholder="Tipo de Embarcação" value="<?=$this->tipoEmbarcacao['TTE_TipoEmbarcacao']?>"/>
        </div>
        <div id="Submit">
            <input type="submit" value="Atualizar" />
        </div>
    </fieldset>
</form>