<h2>Lista de Tipos de Embarcações</h2>

<a href="<?=$this->url(array("controller"=>"tipo-embarcacao","action"=>"novo"),null,true)?>" id="botao-ancora">Novo</a>

<table>
    <tr>
        <th>Tipo de Embarcação</th>
    </tr>
    
    <?php
    foreach ($this->dados as $key => $tipoEmbarcacao):
    ?>
    <tr>
        <td><?= $tipoEmbarcacao['TTE_TipoEmbarcacao'] ?></td>
        <td class="td-botao">
            <a href="<?=$this->url(array("controller"=>"tipo-embarcacao","action"=>"editar", "id" => $tipoEmbarcacao['TTE_ID']),null,true)?>">
                <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                </ul>
            </a>
        </td>
        <td class="td-botao">
            <a href="<?=$this->url(array("controller"=>"tipo-embarcacao","action"=>"excluir", "id" => $tipoEmbarcacao['TTE_ID']),null,true)?>">
                <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-trash"></span></li>
                </ul>
            </a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>