<h2>Perfil Social->Tipo de Embarcação</h2>
<h3>Novo</h3>

<a href="<?=$this->url(array("controller"=>"tipo-embarcacao","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>

<form class="pure-form pure-form-aligned" id="cadastro-usuario" action="<?=$this->url(array("controller"=>"tipo-embarcacao","action"=>"criar"),null,true)?>" method="post">
    <fieldset id="Social">
        <div id="form-esq">
            <label for="tipoEmbarcacao">Tipo de Embarcação</label><br/>
            <input type="text" name="tipoEmbarcacao" id="tipoEmbarcacao" placeholder="Tipo de Embarcação"/>
        </div>
        <div class="Submit">
            <input type="submit" value="Enviar" />
        </div>
    </fieldset>
</form>