<h2>Novo Tipo de Embarcação</h2>

<a href="<?=$this->url(array("controller"=>"tipo-embarcacao","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>

<form action="<?=$this->url(array("controller"=>"tipo-embarcacao","action"=>"criar"),null,true)?>" method="post">
    <label>Tipo de Embarcação: <input type="text" name="tipoEmbarcacao" /></label> <br />
    <input type="submit" value="Cadastrar" />
</form>