
<div id="titulos">
    <h2>Desembarque->Amostragem de Camarão</h2>
    <h3>Editar</h3>
</div>


<form id="formulario" action="<?= $this->url(array("controller" => "amostra-camarao", "action" => "criar"), null, true) ?>" method="post">
    <fieldset id="Desembarque">
        <div id="esquerda">
            <div id="form-esq">
                <label for="id">ID:</label>
                <input type="text" name="id_amostra" placeholder="Id" id="id_ficha" /><br />
            </div>

            <div id="form-esq">
                <label for="tipo">Estagiário:</label>
                <select name="select_nome_estagiario" >

                    <option nome="nome_estagiario" value="<?= $this->usuario['tu_id'] ?>"><?= $this->usuario['tu_nome'] ?></option>


                </select></br>
            </div>

            <div id="form-esq">
                <label for="tipo">Monitor:</label>
                <select name="select_nome_monitor" >
                    <?php
                    foreach ($this->users as $key => $monitor):
                        ?>

                        <option nome="nome_monitor" value="<?= $monitor['tu_id'] ?>"><?= $monitor['tu_nome'] ?></option>

                        <?php
                    endforeach;
                    ?>
                </select></br>
            </div>

            <div id="form-esq">
                <label for="tipo">Data:</label>
                <input type="date"  placeholder="Data" name="data_amostra"/><br />
            </div>


            <div id="form-esq">  
                <label for="tipo">Porto:</label>
                <select name="select_nome_porto" >
                    <?php
                    foreach ($this->dados_porto as $key => $porto):
                        ?>

                        <option nome="nome_porto" value="<?= $porto['pto_id'] ?>"><?= $porto['pto_nome'] ?></option>

                        <?php
                    endforeach;
                    ?>
                </select></br>
            </div>   
            <div id="form-esq">
                <label>Barco:</label>
                <select name="nomeBarco" placeholder="Nome do Barco" />
                <?php
                foreach ($this->barcos as $key => $barco):
                    ?>
                    <option value="<?= $barco['bar_id'] ?>"><?= $barco['bar_nome'] ?></option>
                    <?php
                endforeach;
                ?>
                </select>
                <br />
            </div>
            <div id="form-esq">
                <label>Pesqueiro:</label>
                <select name="nomePesqueiro">
                    <?php foreach ($this->pesqueiros as $key => $pesqueiro): ?>
                        <option value="<?= $pesqueiro['paf_id']; ?>"><?= $pesqueiro['paf_pesqueiro']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div id="form-esq">
                <label>Espécie Capturada:</label>
                <select name="especie_camarao">
                    <?php foreach ($this->especies as $key => $especie): ?>
                        <option value="<?= $especie['esp_id']; ?>"><?= $especie['esp_nome_comum']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div id="form-esq">
                <label for="tipo">Captura total:</label>
                <input type="text"  placeholder="Captura Total" name="captura_total"/><br />
            </div>
            <div id="form-esq">
                <label for="tipo">Id Subamostra:</label>
                <select name="subamostra_id"/>
                </select>
            </div>
            <div id="Submit">
                <input type="submit" value="Salvar Alterações" /> 
            </div>
          
                    
            
        </div>
        <br/>
    </fieldset>
</form>
  <fieldset class="noEditable"><legend>Amostras de Camarão:</legend>
        <fieldset class="noEditable"><legend>Dados das Amostras:</legend>

            <div id="base">
                <input onclick="jsInsertAmostraCamarao(this.form, '<?= $this->url(array("controller" => "arrasto-fundo", "action" => "insertespeciecapturada"), null, true) ?>','<?=$this->entrevista['af_id']?>')" type="button" value="Adicionar" />
                
                <select style="float:left;" class="amostragem" name="SelectSexo" style="width:5px">
                    
                </select>
                <select style="float:left;" class="amostragem" name="SelectMaturidade">
                    
                </select>
                
                <input style="float:left;" type="text" name="comprimentoCabeca" placeholder="Comp. Carapaça" size="10px">

                <input style="float:left;" type="text" name="peso" placeholder="Peso" size="10px">

                <input type="hidden" name="id_amostragem"  value="<?= $this->entrevista['af_id'] ?>"/>

            </div>

        </fieldset>
        <br>
         <fieldset class="noEditable" id="itemArteTipoRows"><legend>Dados Cadastrados:</legend>
                <table id="especiesCapturadas">
                    <tr>
                        <th width="20%">Id Amostra</th>
                        <th width="20%">Sexo</th>
                        <th width="20%">Maturidade</th>
                        <th width="20%">Comp.Carapaça</th>
                        <th width="20%">Peso</th>
                    </tr>
                    <?php
                    foreach ($this->vAmostragem as $key => $vAmostragem):
                        ?>
                        <tr id="itemEmbarcacoesRows">
                            <td name="inputEntrevista"> <?= $vAmostragem['tamc_id'] ?> </td>
                            <td name="inputSexo"> <?= $vAmostragem['tamc_sexo'] ?> </td>
                            <td name="inputMaturidade"> <?= $vAmostragem['mat_id'] ?> </td>
                            <td name="inputPreco"> <?= $vAmostragem['spc_preco'] ?> </td>
                            <td><input type="button" class="button-del" width="5%" onclick="jsDeleteAmostragem(<?= $this->entrevista['af_id'] ?>, '<?= $this->url(array("controller" => "arrasto-fundo", "action" => "deletespecie"), null, true) ?>', <?= $vAmostragem['spc_af_id'] ?>)"></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </fieldset>
</fieldset>
<div id="Submit">
    <a href="<?= $this->url(array("controller" => "amostra-camarao", "action" => "index"), null, true) ?>" id="botao-ancora">Voltar</a>           
</div>  