<h2>Desembarque->Amostragem de Camarão</h2>

    <a href="<?= $this->url(array("controller" => "amostra-camarao", "action" => "novo"), null, true) ?>" id="botao-ancora">Novo</a>
    <fieldset id="Desembarque"></fieldset>
    <table>
        <tr>
            <th>Id</th>
            <th></th>
        </tr>

        <?php
        foreach ($this->barcos as $key => $barco):
            ?>
            <tr>
                <td><?= $barco['bar_id'] ?></td>
                <td><?= $barco['bar_nome'] ?></td>

                <td class="td-botao">
                    <a href="<?= $this->url(array("controller" => "barcos", "action" => "editar", "id" => $barco['bar_id']), null, true) ?>">
                        <ul id="icons" class="ui-widget ui-helper-clearfix">
                            <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                        </ul>
                    </a>
                </td>

                <td class="td-botao">
                    <input type="button" value="Excluir" onclick="beforeDelete('<?= $this->url(array("controller" => "barcos", "action" => "excluir", "id" => $barco['bar_id']), null, true) ?>')">
                </td>

            </tr>
        <?php endforeach; ?>
    </table>
    <br/><br/>
    <a href="<?= $this->url(array("controller" => "barcos", "action" => "relatorio"), null, true) ?>" id="botao-ancora" target="_blank">Gerar Relatório</a>
