<div id="titulos">
    <h2>Perfil Social->Escolaridade</h2>
    <h3>Editar</h3>
</div>

<form action="<?=$this->url(array("controller"=>"escolaridade","action"=>"atualizar"),null,true)?>" method="post">
   <input type="hidden" name="idEscolaridade" value="<?= $this->escolaridades['esc_id'] ?>" />
   <fieldset id="Escolaridade">
     <div id="esquerda">   

     <div id="form-esq"> 
            <label>Programa Social: </label>
            <input type="text" name="nivelEscolaridade" value="<?= $this->escolaridades['esc_nivel'] ?>"/> <br />
        </div>
        
        
         <div id="Submit">
            <a href="<?=$this->url(array("controller"=>"escolaridade","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a> 
            <input type="submit" value="Atualizar" />
        </div>
      </div> 
    </fieldset>
</form>