<div id="titulos">
    <h2>Desembarque->Pesca de Tarrafa</h2>
    <h3>Entrevista</h3>
</div>

<div id="esquerda-entrevista">
    <form  action="<?= $this->url(array("controller" => "tarrafa", "action" => "criar"), null, true) ?>">
        <fieldset id="Desembarque">
            <div id="esquerda">
                <div id="form-esq">
                    <label>ID da ficha diária:</label>
                    <input type="text" name="id_fichaDiaria" placeholder="ID" disabled="true" value="<?= $this->fichaDiaria['fd_id'] ?>" /><br />
                </div>
                <div id="form-esq">
                    <label>ID monitoramento:</label>
                    <input type="text" name="id_monitoramento" placeholder="ID"  value="<?= $this->monitoramento['mnt_id'] ?>" /><br />
                </div>
                <div id="form-esq">
                    <label for="tipo">ID Entrevista:</label>
                    <input type="text" placeholder = "ID" name="id_entrevista" disabled="true"/><br />
                </div>
            </div>
            <br/>
            <div id="esquerda">
                <legend><h4>Embarcação:</h4></legend>
                <div id="form-esq">
                    <label>Utilizou Barco?</label>
                    <input type="checkbox" id="nome" name="embarcada" checked="true"/><br />
                </div>
                <div id="form-esq">
                    <label>Motor?</label>
                    <input type="checkbox"  name="motor"/><br />
                </div>
                <div id="form-esq">
                    <label>Barco:</label>
                    <select name="nomeBarco" placeholder="Nome do Barco" />
                    <?php
                    foreach ($this->barcos as $key => $barco):
                        ?>
                        <option value="<?= $barco['bar_id'] ?>"><?= $barco['bar_nome'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>

                </div>
                <div id="form-esq">
                    <label>Tipo de Barco:</label>
                    <select name="tipoBarco" />
                    <?php
                    foreach ($this->tipoEmbarcacoes as $key => $tipoEmbarcacao):
                        ?>
                        <option value="<?= $tipoEmbarcacao['tte_id'] ?>"><?= $tipoEmbarcacao['tte_tipoembarcacao'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select>

                </div>

            </div>
            <div id="direita-entrevista">
                <div id="form-esq">    
                    <label>Pescador Entrevistado:</label>
                    <select name="pescadorEntrevistado" />
                    <?php
                    foreach ($this->pescadores as $key => $pescador):
                        ?>
                        <option value="<?= $pescador['tp_id'] ?>"><?= $pescador['tp_nome'] ?></option>
                        <?php
                    endforeach;
                    ?>
                    </select><br />
                </div>
                <div id="form-esq">
                    <label>Qtd de Pescadores:</label>
                    <input type="text"  name="numPescadores" placeholder="Quantidade de Pescadores "/><br />
                </div>
            </div>
            <div id="esquerda">
                <legend><h4>Tempo:</h4></legend>
                <div id="form-esq">
                    <label>Data:</label>
                    <input type="date" name="data"/>
                </div>
                <div id="form-esq">
                    <label>Tempo Gasto:</label>
                    <input type="time" name="tempoGasto"/>
                </div>
            </div>
            <br/>
            <div id="esquerda">
                <div id="form-esq">
                    <legend><h4>Esforço:</h4></legend>
                    <label>Roda(m):</label>
                    <input type="text"  name="roda" placeholder="Roda"/>
                </div>
                <div id="form-dir">    
                    <label>Altura(m):</label>
                    <input type="text"  name="altura" placeholder="Altura"/><br />
                </div>
            </div>
            <div id="direita-entrevista">
                <div id="form-dir">    
                    <label>Número de Lances:</label>
                    <input type="text"  name="numLances" placeholder="Lances"/><br />
                </div>
                <div id="form-dir">    
                    <label>Malha:</label>
                    <input type="text"  name="malha" placeholder="malha"/><br />
                </div>
            </div><br/>
            <div id="esquerda">
                <legend><h4>Outros dados:</h4></legend>
                <div id="form-esq">    
                    <label>Avistou:</label>
                    <input type="text" name="avistamento" placeholder="Avistamento"/><br />
                </div>
                <div id="form-esq">
                    <label for="tipo">Subamostra?:</label>
                    <input type="checkbox" name="subamostra" /><br />
                </div>
                <div id="form-esq">
                    <label for="tipo">Observação:</label>
                    <input type="text" name="observacao" placeholder="Observação" /><br />
                </div>
                <div id="Submit">
                    <input type="submit" value="Enviar"/>
                </div>
            </div>

    </form>
</div>
<br/>
<br/>
<form id="formulario" >
<fieldset class="noEditable"><legend>Pesqueiro:</legend>
    <fieldset class="noEditable"><legend>Pesqueiro e tempo no pesqueiro:</legend>
            <div id="base">
                <input onclick="jsInsertPesqueiroWithoutTime(this.form, '<?= $this->url(array("controller" => "tarrafa", "action" => "insertpesqueiro"), null, true) ?>', '<?=$this->entrevista['tar_id']?>')" type="button" value="Add row" />
                <select style="float:left;" name="nomePesqueiro">
                    <?php foreach ($this->pesqueiros as $key => $pesqueiro): ?>
                        <option value="<?= $pesqueiro['paf_id']; ?>"><?= $pesqueiro['paf_pesqueiro']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

        </fieldset>
        <br>
        <fieldset class="noEditable" id="itemArteTipoRows"><legend>Pesqueiros:</legend>
            <table id="pesqueiros">
                <tr>
                    <th width="5%">Id Entrevista</th>
                    <th width="50%">Pesqueiro</th>
                </tr>
                <?php
                foreach ($this->vTarrafa as $key => $vTarrafa):
                    ?>
                    <tr id="itemArrastoRows">
                        <td name="inputIdEntrevista"> <?= $vTarrafa['tar_id'] ?> </td>
                        <td name="inputPesqueiro"> <?= $vTarrafa['paf_pesqueiro'] ?> </td>
                        <td><input type="button" class="button-del" width="5%" onclick="jsDeletePesqueiro(<?= $this->entrevista['tar_id'] ?>, '<?= $this->url(array("controller" => "tarrafa", "action" => "deletepesqueiro"), null, true) ?>', <?= $vCalao['tar_paf_id'] ?>)"></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </fieldset>
</fieldset>
<fieldset class="noEditable"><legend>Espécies Capturadas:</legend>
        <fieldset class="noEditable"><legend>Dados das Espécies Capturadas:</legend>

            <div id="base">
                <input onclick="jsInsertEspecieCapturada(this.form, '<?= $this->url(array("controller" => "tarrafa", "action" => "insertespeciecapturada"), null, true) ?>','<?=$this->entrevista['tar_id']?>')" type="button" value="Add row" />
                <select style="float:left;" name="SelectEspecie">
                    <?php foreach ($this->especies as $key => $especie): ?>
                        <option value="<?= $especie['esp_id']; ?>"><?= $especie['esp_nome_comum']; ?></option>
                    <?php endforeach; ?>
                </select>
                <input style="float:left;" type="text" name="quantidade" placeholder="Quantidade" size="10px">
                <input style="float:left;" type="text" name="peso" placeholder="Peso" size="10px">
                <input style="float:left;" type="text" name="precokg" placeholder="Preço por kg" size="10px">

                <input type="hidden" name="id_entrevista"  value="<?= $this->entrevista['vp_id'] ?>"/>

            </div>

        </fieldset>
        <br>
         <fieldset class="noEditable" id="itemArteTipoRows"><legend>Espécies Capturadas:</legend>
                <table id="especiesCapturadas">
                    <tr>
                        <th width="20%">Id Entrevista</th>
                        <th width="30%">Espécie Capturada</th>
                        <th width="20%">Quantidade</th>
                        <th width="20%">Peso (kg)</th>
                        <th width="20%">Preço por kg</th>
                    </tr>
                    <?php
                    foreach ($this->vEspecieCapturadas as $key => $vEspecieCapturada):
                        ?>
                        <tr id="itemEmbarcacoesRows">
                            <td name="inputEntrevista"> <?= $vEspecieCapturada['tar_id'] ?> </td>
                            <td name="inputEspecie" > <?= $vEspecieCapturada['esp_nome_comum'] ?> </td>
                            <td name="inputQuantidade"> <?= $vEspecieCapturada['spc_quantidade'] ?> </td>
                            <td name="inputPeso"> <?= $vEspecieCapturada['spc_peso_kg'] ?> </td>
                            <td name="inputPreco"> <?= $vEspecieCapturada['spc_preco'] ?> </td>
                            <td><input type="button" class="button-del" width="5%" onclick="jsDeletePesqueiro(<?= $this->entrevista['vp_id'] ?>, '<?= $this->url(array("controller" => "vara-pesca", "action" => "deletespecie"), null, true) ?>', <?= $vEspecieCapturada['spc_tar_id'] ?>)"></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </fieldset>
    </fieldset>
    </form>
    <br/> <br/>
    <a href="<?= $this->url(array("controller" => "ficha-diaria", "action" => "editar","id" => $this->monitoramento['fd_id']), null, true) ?>" id="botao-ancora">Voltar à Ficha-Diária</a>
    