<h2>Desembarque--Tempo</h2>

<a href="<?=$this->url(array("controller"=>"tempo","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>


<form action="<?=$this->url(array("controller"=>"tempo","action"=>"atualizar"),null,true)?>" method="post"> 
    <fieldset id="Desembarque">
        <legend ><h3>Tempo:</h3></legend>
        <label for="id">ID:</label>
	<input type="text" name="id_tempo" id="id_tempo" value="<?= $this->tempo['TMP_ID']?>"/><br />
	<label for="tipo">Estado do Tempo:</label>
	<input type="text" id="estado_tempo" name="estado_tempo" value="<?= $this->tempo['TMP_Tempo']?>"/><br />
        <input type="submit" value="enviar"/>
    </fieldset>
</form>