<h2>Desembarque--Tempo</h2>

<a href="<?=$this->url(array("controller"=>"tempo","action"=>"novo"),null,true)?>" id="botao-ancora">Novo</a>

<table>
    <tr>
        <th>Tempo</th>
    </tr>
    
    <?php
    foreach ($this->dados as $key => $tempo):
    ?>
    <tr>
        <td><?= $tempo['TMP_Tempo'] ?></td>
        <td class="td-botao">
            <a href="<?=$this->url(array("controller"=>"tempo","action"=>"editar", "id" => $tempo['TMP_ID']),null,true)?>">
                <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                </ul>
            </a>
        </td>
        <td class="td-botao">
            <a href="<?=$this->url(array("controller"=>"tempo","action"=>"excluir", "id" => $tempo['TMP_ID']),null,true)?>">
                <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-trash"></span></li>
                </ul>
            </a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
