<h2>Desembarque->Tempos</h2>

<a href="<?=$this->url(array("controller"=>"tempo","action"=>"novo"),null,true)?>" id="botao-ancora">Novo</a>
<fieldset id="Desembarque"></fieldset>
<table>
    <tr>
        <th>ID</th>
        <th>Tempo</th>
    </tr>
    
    <?php
    foreach ($this->dados as $key => $tempo):
    ?>
    <tr>
        <td><?= $tempo['TMP_ID'] ?></td>
        <td><?= $tempo['TMP_Estado'] ?></td>
        <td class="td-botao">
            <a href="<?=$this->url(array("controller"=>"tempo","action"=>"editar", "id" => $tempo['TMP_ID']),null,true)?>">
                <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                </ul>
            </a>
        </td>
        <td class="td-botao">
            <a href="<?=$this->url(array("controller"=>"tempo","action"=>"excluir", "id" => $tempo['TMP_ID']),null,true)?>">
                <ul id="icons" class="ui-widget ui-helper-clearfix">
                    <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-trash"></span></li>
                </ul>
            </a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<br/><br/>
<a href="<?=$this->url(array("controller"=>"tempo","action"=>"relatorio"),null,true)?>" id="botao-ancora" target="_blank">Gerar Relatório</a>