<h2>Desembarque->Tempo</h2>
<h3>Novo</h3>
<a href="<?=$this->url(array("controller"=>"tempo","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>

<form action="<?=$this->url(array("controller"=>"tempo","action"=>"criar"),null,true)?>" method="post">
    <fieldset id="Desembarque">
       <div id="esquerda"> 
        <div id="form-esq">
            <label>Tempo: </label>
            <input type="text" name="tempo" placeholder="Tempo"/><br />
        </div>
        <div id="Submit">
            <input type="submit" value="Enviar"/>
        </div>
       </div>     
    </fieldset>
</form>