<h2>Desembarque--Tempo</h2>

<form action="<?=$this->url(array("controller"=>"tempo","action"=>"criar"),null,true)?>" method="post"> 
    <fieldset id="Desembarque">
        <legend ><h3>Tempo:</h3></legend>
        <label for="id">ID:</label>
	<input type="text" name="id_tempo" id="id_tempo"/><br />
	<label for="tipo">Estado do Tempo:</label>
	<input type="text" id="estado_tempo" name="estado_tempo"/><br />
        <input type="submit" value="enviar"/>
    </fieldset>
</form>