<div id="titulos">
    <h2>Perfil Social->Tipo Capturada</h2>
    <h3>Novo</h3>
</div>

<form action="<?=$this->url(array("controller"=>"tipo-capturada","action"=>"criar"),null,true)?>" method="post">
    <fieldset id="Social">
        <div id="esquerda">
            <div id="form-esq">
                <label>Área de Pesca: </label>
                <input type="text" name="tipoCapturada" placeholder="Tipo Capturada" /> <br/>
            </div>
        <div id="Submit">
            <a href="<?=$this->url(array("controller"=>"tipo-capturada","action"=>"index"),null,true)?>" id="botao-ancora">Voltar</a>
            <input type="submit" value="Cadastrar" />
        </div> 
        </div>
    </fieldset>
</form>